package admin

// SRE-03 (M half): the event-code table for the support bundle's events.json.
//
// supportEventCodes maps a fixed Warn/Error log message (the constant string a
// slog.Warn/Error call passes as its message) to a stable, lower_snake_case
// event code. The message text itself is never exported: supportEvents emits
// only the code, so a bundle cannot carry free-form text. Codes are derived
// from the literal alone — no runtime data — so none can embed a request value.
//
// The entries were generated from the message literals in this tree. They are
// hand-maintained from here: TestSupportEventCodes_EveryWarnErrorLiteralIsCoded
// parses the tree, and when a new Warn/Error message has no code it names the
// message and file, so an author adds the entry it needs. A message held in a
// struct field (a maintenance step's failLog, a voice toggle's updateLog) needs
// an entry for each constant that field is set to. Messages with a variable
// suffix are covered by supportEventPrefixCodes (support_redaction.go).
var supportEventCodes = map[string]string{ //nolint:gosec // G101: false positive — log messages and event codes, not credentials
	"ACME HTTP server error — HTTP-01 challenges and certificate renewal will fail until the next restart": "acme_http_server_error_http_01",
	"ACME HTTP server shutdown error": "acme_http_server_shutdown_error",
	"AllowedOrigins contains wildcard '*' — consider restricting to specific origins for production use": "allowed_origins_wildcard",
	"ChannelService.HandlePresenceUpdate":                                                                     "channelservice_handlepresenceupdate",
	"ChannelService.HandlePresenceUpdate custom status":                                                       "channelservice_handlepresenceupdate_custom_status",
	"ChannelService.HandlePresenceUpdate: could not read stored custom status":                                "channelservice_handlepresenceupdate_read_custom_status_failed",
	"ChannelService.ListVisibleChannels":                                                                      "channelservice_listvisiblechannels",
	"ChannelService.ListVisibleChannels GetChannelOverridesFor":                                               "channelservice_listvisiblechannels_getchanneloverridesfor",
	"ChannelService.ListVisibleChannels GetRoleForUser":                                                       "channelservice_listvisiblechannels_getroleforuser",
	"CleanupVoiceForChannel ChannelStates":                                                                    "cleanupvoiceforchannel_channelstates",
	"CleanupVoiceForChannel LeaveIfMatch":                                                                     "cleanupvoiceforchannel_leaveifmatch",
	"DMService.CreateDM":                                                                                      "dmservice_createdm",
	"DMService.CreateGroupDM":                                                                                 "dmservice_creategroupdm",
	"DMService.CreateGroupDM: failed to read participants after commit":                                       "dmservice_creategroupdm_read_participants_failed",
	"DeleteAccount failed":                                                                                    "deleteaccount_failed",
	"DeleteAccount: files pending":                                                                            "deleteaccount_files_pending",
	"DispatchV2 panic recovered":                                                                              "dispatchv2_panic_recovered",
	"DispatchV2: hardware fault, exiting for supervisor restart":                                              "dispatchv2_hardware_fault_exiting",
	"EmitEvents: unknown event type":                                                                          "emitevents_unknown_event_type",
	"FinalizeTimeoutLift: HasActiveTimeout":                                                                   "finalizetimeoutlift_hasactivetimeout",
	"LeaveVoiceChannelIfMatch exhausted retries — ghost state may persist":                                    "voice_cleanup_exhausted",
	"LeaveVoiceChannelIfMatch failed, retrying in background":                                                 "leavevoicechannelifmatch_failed_retrying_in_background",
	"LeaveVoiceChannelIfMatch retry failed":                                                                   "leavevoicechannelifmatch_retry_failed",
	"LeaveVoiceChannelIfMatch skipped due to missing join token":                                              "leavevoicechannelifmatch_skipped_missing_join_token",
	"MessageService.AddReaction":                                                                              "messageservice_addreaction",
	"MessageService.DeleteMessage DMAudience":                                                                 "messageservice_deletemessage_dmaudience",
	"MessageService.DeleteMessage DecrementMentionCounts":                                                     "messageservice_deletemessage_decrementmentioncounts",
	"MessageService.EditMessage DMAudience":                                                                   "messageservice_editmessage_dmaudience",
	"MessageService.EditMessage ReplaceMessageMentions":                                                       "messageservice_editmessage_replacemessagementions",
	"MessageService.GetMessages":                                                                              "messageservice_getmessages",
	"MessageService.GetMessagesAround":                                                                        "messageservice_getmessagesaround",
	"MessageService.GetReactionUsers":                                                                         "messageservice_getreactionusers",
	"MessageService.PurgeMessages":                                                                            "messageservice_purgemessages",
	"MessageService.PurgeMessages DecrementMentionCounts":                                                     "messageservice_purgemessages_decrementmentioncounts",
	"MessageService.RemoveReaction":                                                                           "messageservice_removereaction",
	"MessageService.SendMessage DMAudience":                                                                   "messageservice_sendmessage_dmaudience",
	"MessageService.SendMessage DeleteMessage (cleanup)":                                                      "messageservice_sendmessage_deletemessage_cleanup",
	"MessageService.SendMessage DeleteMessage (empty-after-link cleanup)":                                     "messageservice_sendmessage_deletemessage_empty_after_link",
	"MessageService.SendMessage GetAttachments":                                                               "messageservice_sendmessage_getattachments",
	"MessageService.SendMessage GetDMParticipantIDs":                                                          "messageservice_sendmessage_getdmparticipantids",
	"MessageService.SendMessage GetDMParticipants":                                                            "messageservice_sendmessage_getdmparticipants",
	"MessageService.SendMessage IsGroupDM":                                                                    "messageservice_sendmessage_isgroupdm",
	"MessageService.SendMessage LinkAttachments":                                                              "messageservice_sendmessage_linkattachments",
	"MessageService.SendMessage OpenDM":                                                                       "messageservice_sendmessage_opendm",
	"MessageService.SendMessage: first-contact gate failed":                                                   "messageservice_sendmessage_first_contact_gate_failed",
	"MessageService.SendMessage: recipient lookup for the first-contact gate failed":                          "messageservice_sendmessage_first_contact_recipient_lookup_failed",
	"MessageService.SendMessage: skipped attachments (not owned, already linked, or missing)":                 "messageservice_sendmessage_skipped_attachments",
	"MessageService.SendMessage: trust lookup failed":                                                         "messageservice_sendmessage_trust_lookup_failed",
	"MessageService.applyMentionCounts IncrementMentionCounts":                                                "messageservice_applymentioncounts_incrementmentioncounts",
	"MessageService.applyMentionCounts ListBlockersOf":                                                        "messageservice_applymentioncounts_listblockersof",
	"MessageService.applyMentionCounts readers":                                                               "messageservice_applymentioncounts_readers",
	"MessageService.handleReaction DMAudience":                                                                "messageservice_handlereaction_dmaudience",
	"MessageService.resolveMentions GetUserIDsByUsernames":                                                    "messageservice_resolvementions_getuseridsbyusernames",
	"PermissionService.getOrPopulate override fetch failed, denying":                                          "permissionservice_getorpopulate_override_fetch_failed",
	"PushDispatcher.Notify ListBlockersOf":                                                                    "pushdispatcher_notify_listblockersof",
	"PushDispatcher.Notify ListPushSubscriptionsForDispatch":                                                  "pushdispatcher_notify_listpushsubscriptionsfordispatch",
	"PushDispatcher.prune DeletePushSubscriptionByID":                                                         "pushdispatcher_prune_deletepushsubscriptionbyid",
	"PushDispatcher.recipientBlocksAuthor IsBlocked":                                                          "pushdispatcher_recipientblocksauthor_isblocked",
	"PushDispatcher.subscriptionStillCurrent ListPushSubscriptionsForDispatch":                                "pushdispatcher_subscriptionstillcurrent_listpushsubscriptions",
	"TLS certificate issuance failed — clients cannot connect over HTTPS until this is fixed":                 "tls_certificate_issuance_failed",
	"TOTP secret decryption failed — check TOTP_ENCRYPTION_KEY":                                               "totp_secret_decryption_failed",
	"TOTP secret returned as plaintext (data too short for nonce+tag)":                                        "totp_secret_plaintext_too_short_for_nonce_tag",
	"TOTP secret returned as plaintext (not valid hex) — consider encrypting legacy secrets":                  "totp_secret_plaintext_not_hex",
	"TOTP secret returned as plaintext (too short for encrypted format) — consider encrypting legacy secrets": "totp_secret_plaintext_too_short_for_encrypted_format",
	"UpdateProfile post-commit re-read failed; returning locally merged row":                                  "updateprofile_post_commit_re_read_failed",
	"UserService.ChangePassword DeleteOtherSessions":                                                          "userservice_changepassword_deleteothersessions",
	"admin erasure failed":                                                                                    "admin_erasure_failed",
	"admin erasure: files pending":                                                                            "admin_erasure_files_pending",
	"admin: roles_update broadcast skipped, role list unreadable":                                             "admin_roles_update_broadcast_skipped_role",
	"admin: token resolution failed":                                                                          "authentication_storage_failed",
	"admin_allowed_cidrs is checked against the connecting address and trusted_proxies is empty — behind a reverse proxy or a container port relay that address is the relay's (loopback or bridge), which the allowlist admits": "admin_allowed_cidrs_behind_relay_without_trusted_proxies",
	"api token revoked":                                      "api_token_revoked",
	"api tokens revoked by label":                            "api_tokens_revoked_by_label",
	"appeal decide: transaction error":                       "appeal_decide_transaction_error",
	"audit log dropped: queue full":                          "audit_log_dropped_queue_full",
	"audit log dropped: writer stopped":                      "audit_log_dropped_writer_stopped",
	"audit log write failed":                                 "audit_write_failed",
	"audit writer: flush lost audit entries":                 "audit_writer_flush_lost_audit_entries",
	"auth service returned a non-refusal error":              "auth_service_non_refusal_error",
	"auth: token resolution failed":                          "auth_token_resolution_failed",
	"backup failed integrity check — removing":               "backup_verification_failed",
	"backup maintenance: failed to remove stale backup temp": "backup_maintenance_remove_stale_temp_failed",
	"backup retention pruning failed":                        "backup_retention_pruning_failed",
	"backup retention: failed to remove expired backup":      "backup_retention_failed_to_remove_expired",
	"banned user login attempt":                              "banned_user_login_attempt",
	"block: shared-DM lookup for voice eviction failed":      "block_shared_dm_lookup_for_voice_eviction_failed",
	"broadcastDMOpen: marshal failed":                        "broadcastdmopen_marshal_failed",
	"buildDMChannelOpenFor called with nil recipient":        "builddmchannelopenfor_called_with_nil_recipient",
	"buildJSON marshal failed":                               "buildjson_marshal_failed",
	"buildReady GetAllVoiceStates":                           "buildready_getallvoicestates",
	"buildReady failed":                                      "buildready_failed",
	"channel deleted":                                        "channel_deleted",
	"channel_focus: read-state write failed":                 "channel_focus_read_state_write_failed",
	"config: admin_allowed_cidrs is customized but trusted_proxies is empty — behind a reverse proxy or Docker network the allowlist checks the proxy's private address, not the real client; set server.trusted_proxies to the proxy hop(s)": "config_admin_allowed_cidrs_without_trusted_proxies",
	"config: admin_allowed_cidrs is empty — the /admin IP perimeter is disabled, so AdminIPRestrict admits every address; set server.admin_allowed_cidrs to the addresses that should reach the admin panel":                                  "config_admin_allowed_cidrs_is_empty",
	"config: ignoring invalid CIDR entry (use address/prefix notation, e.g. 10.0.0.1/32)": "config_invalid_cidr_entry",
	"config: unknown key ignored — value has NO effect (typo?)":                           "config_unknown_key_ignored",
	"config: value out of range": "config_value_out_of_range",
	"could not write the boot marker; the next start cannot tell how this run ended": "could_not_write_the_boot_marker",
	"database file replaced — restarting to load the restored data":                  "database_file_replaced_restarting",
	"database restored from backup — closing DB":                                     "database_restored_from_backup_closing_db",
	"db: could not advance the author's read state past their message":               "db_advance_author_read_state_failed",
	"db: could not take the single-process lock; continuing unprotected":             "db_single_process_lock_failed",
	"disk space critically low — writes will start failing soon":                     "disk_space_critically_low",
	"disk space low": "disk_space_low",
	"erasure marker: erased account present in the database, erasing again":     "erasure_marker_erased_account_present",
	"erasure marker: pending marker's account present in the database, erasing": "erasure_marker_pending_account_present",
	"erasure markers replayed": "erasure_markers_replayed",
	"erasure markers: a marker names an id beyond the probe ceiling, so no safe sequence floor can be established; set the floor above the highest id this installation ever handed out and acknowledge it, in the marker file (docs/security.md, \"Erasure marker sequence floors\")":                                                                                                                                                                                                                                                                                                            "erasure_marker_sequence_floor_required",
	"erasure markers: this marker file holds markers but records no erasure key — it was written before the key was bound to the file — and the running key cannot be proven to be the one those markers were computed under. Adopting it unchecked is the failure this check exists to stop: a key regenerated since would silently become the file's key of record, and every marker would stop matching the account it guards. Confirm this is the original erasure key, then bless the file with the statement below, run against the marker file (docs/security.md, \"Erasure marker key\")": "erasure_marker_unbound_key",
	"erasure markers: this marker file was created under a different erasure key, so every marker in it names a subject the running key cannot match; the start-up replay would erase nothing and a restored backup would leave its erased accounts serving. Start with the erasure key this file was written under — or, if the key really was rotated and this one is now the key of record, repoint the file at it with the statement below, run against the marker file (docs/security.md, \"Erasure marker key\")":                                                                           "erasure_marker_key_mismatch",
	"erasure markers: upload storage unavailable at start-up; a replayed erasure journals its files": "erasure_markers_upload_storage_unavailable",
	"erasure replay: could not count the remaining admin-class accounts":                             "erasure_replay_count_admin_accounts_failed",
	"erasure replay: files pending": "erasure_replay_files_pending",
	"erasure replay: the erased account was the last admin-class account in the restored database — the backup predates the handover to another administrator; none remains": "erasure_replay_erased_last_admin_account",
	"erasure: WAL checkpoint failed":                                                                                   "erasure_wal_checkpoint_failed",
	"erasure: could not confirm the marker":                                                                            "erasure_could_not_confirm_the_marker",
	"erasure: could not discard the pending marker":                                                                    "erasure_discard_pending_marker_failed",
	"erasure: could not restore secure_delete":                                                                         "erasure_could_not_restore_secure_delete",
	"erasure: file removal failed":                                                                                     "erasure_file_removal_failed",
	"erasure: reconciliation could not remove a stranded file":                                                         "erasure_reconciliation_remove_stranded_file_failed",
	"erasure: replay purge failed":                                                                                     "erasure_replay_purge_failed",
	"erasure: the retried WAL checkpoint failed; the next tick tries again":                                            "erasure_the_retried_wal_checkpoint_failed",
	"erasure: the start-up WAL checkpoint failed; the maintenance tick retries":                                        "erasure_startup_wal_checkpoint_failed",
	"erasure: the start-up WAL checkpoint is still blocked; the maintenance tick retries":                              "erasure_startup_wal_checkpoint_blocked",
	"event dropped: persister stopped":                                                                                 "event_dropped_persister_stopped",
	"event persistence: failed to persist advanced ws seq floor; hub seq not advanced this boot":                       "event_persistence_persist_seq_floor_failed",
	"event persistence: failed to read MAX(events.seq); hub seq still advanced from the persisted floor for this boot": "event_persistence_read_max_seq_failed",
	"event persistence: failed to read persisted ws seq floor; hub seq not advanced this boot":                         "event_persistence_read_seq_floor_failed",
	"event persistence: stored ws seq floor is not a valid uint64, resetting to 0":                                     "event_persistence_seq_floor_invalid",
	"event persister: flush lost events":                                                                               "event_persister_flush_lost_events",
	"event pruner did not exit before shutdown timeout":                                                                "event_pruner_shutdown_timeout",
	"event pruner: PruneEventsOlderThan failed":                                                                        "event_prune_failed",
	"expired session cleanup failed":                                                                                   "expired_session_cleanup_failed",
	"failed to check NSFW acknowledgement":                                                                             "failed_to_check_nsfw_acknowledgement",
	"failed to check avatar file":                                                                                      "failed_to_check_avatar_file",
	"failed to clean up orphaned avatar file":                                                                          "failed_to_clean_up_orphaned_avatar",
	"failed to clean up orphaned emoji file":                                                                           "failed_to_clean_up_orphaned_emoji",
	"failed to clean up orphaned upload file":                                                                          "failed_to_clean_up_orphaned_upload",
	"failed to clear custom status on logout":                                                                          "failed_to_clear_custom_status_on_logout",
	"failed to clear stale voice states":                                                                               "failed_to_clear_stale_voice_states",
	"failed to close database before restore — restarting anyway, DB pools are closed either way":                      "failed_to_close_database_before_restore",
	"failed to create LiveKit client, voice disabled":                                                                  "failed_to_create_livekit_client",
	"failed to create attachment record":                                                                               "failed_to_create_attachment_record",
	"failed to create avatar attachment record":                                                                        "failed_to_create_avatar_attachment_record",
	"failed to create file storage":                                                                                    "failed_to_create_file_storage",
	"failed to create file storage for maintenance; orphan file cleanup disabled":                                      "failed_to_create_maintenance_file_storage",
	"failed to decode image dimensions":                                                                                "failed_to_decode_image_dimensions",
	"failed to decrypt TOTP secret":                                                                                    "failed_to_decrypt_totp_secret",
	"failed to delete orphan file":                                                                                     "failed_to_delete_orphan_file",
	"failed to determine executable path":                                                                              "failed_to_determine_executable_path",
	"failed to encrypt TOTP secret":                                                                                    "failed_to_encrypt_totp_secret",
	"failed to fetch user after registration":                                                                          "failed_to_fetch_user_after_registration",
	"failed to issue log stream ticket":                                                                                "failed_to_issue_log_stream_ticket",
	"failed to issue two-factor challenge":                                                                             "failed_to_issue_two_factor_challenge",
	"failed to load TOTP encryption key":                                                                               "failed_to_load_totp_encryption_key",
	"failed to load emoji for broadcast":                                                                               "failed_to_load_emoji_for_broadcast",
	"failed to read server info":                                                                                       "failed_to_read_server_info",
	"failed to remove emoji file":                                                                                      "failed_to_remove_emoji_file",
	"failed to remove old binary":                                                                                      "failed_to_remove_old_binary",
	"failed to reset stale user statuses":                                                                              "failed_to_reset_stale_user_statuses",
	"failed to resolve attachment":                                                                                     "failed_to_resolve_attachment",
	"failed to stage two-factor enrolment":                                                                             "failed_to_stage_two_factor_enrolment",
	"list sessions: failed to mark seen":                                                                               "list_sessions_failed_to_mark_seen",
	"failed to start LiveKit process":                                                                                  "failed_to_start_livekit_process",
	"failed to touch api token":                                                                                        "failed_to_touch_api_token",
	"failed to touch session":                                                                                          "failed_to_touch_session",
	"generated random LiveKit API key — voice tokens will break on restart; set voice.livekit_api_key in config.yaml for stable operation": "generated_random_livekit_api_key",
	"generated random LiveKit API secret — set voice.livekit_api_secret in config.yaml for stable operation":                               "generated_random_livekit_api_secret",
	"gif proxy: decoding upstream response failed":                 "gif_proxy_decoding_upstream_response_failed",
	"gif proxy: upstream request failed":                           "gif_proxy_upstream_request_failed",
	"gif proxy: upstream returned non-200":                         "gif_proxy_upstream_returned_non_200",
	"handleListChannels":                                           "handlelistchannels",
	"handleRenameGroupDM: participant lookup failed":               "handlerenamegroupdm_participant_lookup_failed",
	"http handler panic recovered":                                 "http_handler_panic_recovered",
	"http handler: hardware fault, exiting for supervisor restart": "http_handler_hardware_fault_exiting",
	"http request": "http_request",
	"hub: BroadcastMemberUnban GetUserByID failed":                                                                 "hub_broadcastmemberunban_getuserbyid_failed",
	"hub: RearmTimeoutExpiries could not list active timeouts":                                                     "hub_rearmtimeoutexpiries_list_timeouts_failed",
	"hub: RefreshAllChannelVisibility could not list channels":                                                     "hub_refreshallchannelvisibility_list_channels_failed",
	"hub: RefreshChannelVisibility could not resolve permissions, revoking":                                        "hub_refreshchannelvisibility_resolve_permissions_failed",
	"hub: RefreshUserChannels could not list channels":                                                             "hub_refreshuserchannels_could_not_list_channels",
	"hub: closing stale connection (no activity)":                                                                  "socket_stale_closed",
	"hub: kicking stale connection for re-registering user":                                                        "hub_kicking_stale_connection",
	"hub: panic recovered":                                                                                         "hub_panic_recovered",
	"hub: role change channel lookup failed, closing socket":                                                       "hub_role_change_channel_lookup_failed",
	"hub: role change visibility unresolved, closing socket":                                                       "hub_role_change_visibility_unresolved_closing",
	"hub: stopping and exiting for supervisor restart":                                                             "hub_stopping_for_supervisor_restart",
	"hub: topic rate limit shed a content frame, forcing resync on reconnect":                                      "hub_topic_rate_limit_shed_forcing_resync",
	"hub: topic rate limit exceeded, dropping message":                                                             "hub_topic_rate_limit_exceeded",
	"ignoring invalid CIDR entry (use address/prefix notation, e.g. 10.0.0.1/32)":                                  "config_invalid_cidr_entry",
	"invalid LiveKit URL — falling back to localhost:7880":                                                         "livekit_invalid_url",
	"legacy attachment access denied (NULL uploader_id)":                                                           "legacy_attachment_access_denied_null_uploader",
	"livekit proxy: backend dial failed":                                                                           "livekit_proxy_backend_dial_failed",
	"livekit proxy: frontend accept failed":                                                                        "livekit_proxy_frontend_accept_failed",
	"livekit proxy: origin rejected":                                                                               "livekit_proxy_origin_rejected",
	"livekit webhook: GetVoiceState failed, skipping rogue-participant check":                                      "livekit_webhook_getvoicestate_failed",
	"livekit webhook: LeaveVoiceChannel exhausted retries":                                                         "livekit_webhook_leavevoicechannel_exhausted_retries",
	"livekit webhook: LeaveVoiceChannelIfMatch failed (client gone)":                                               "livekit_webhook_leavevoicechannelifmatch_failed_client_gone",
	"livekit webhook: LeaveVoiceChannelIfMatch failed (stale DB row)":                                              "livekit_webhook_leavevoicechannelifmatch_failed_stale_row",
	"livekit webhook: failed to reconcile participant permissions":                                                 "livekit_webhook_reconcile_participant_permissions_failed",
	"livekit webhook: failed to remove rogue participant":                                                          "livekit_webhook_remove_rogue_participant_failed",
	"livekit webhook: failed to remove stale participant":                                                          "livekit_webhook_remove_stale_participant_failed",
	"livekit webhook: missing Authorization header":                                                                "livekit_webhook_missing_authorization_header",
	"livekit webhook: participant_joined bad identity":                                                             "livekit_webhook_participant_joined_bad_identity",
	"livekit webhook: participant_joined bad room":                                                                 "livekit_webhook_participant_joined_bad_room",
	"livekit webhook: participant_left bad identity":                                                               "livekit_webhook_participant_left_bad_identity",
	"livekit webhook: participant_left bad room":                                                                   "livekit_webhook_participant_left_bad_room",
	"livekit webhook: rogue participant_joined — no matching voice state, removing":                                "livekit_webhook_rogue_participant_joined",
	"livekit webhook: stale join token on participant_joined, removing":                                            "livekit_webhook_stale_join_token",
	"livekit webhook: verification failed":                                                                         "livekit_webhook_verification_failed",
	"livekit: auto-download failed — voice stays offline until livekit-server is available":                        "livekit_download_failed",
	"livekit: companion may outlive this process if it exits without shutting down":                                "livekit_companion_may_outlive_this_process",
	"livekit: ensure the keys entry in your livekit.yaml matches voice.livekit_api_key / voice.livekit_api_secret": "livekit_keys_mismatch_hint",
	"livekit: process exited unexpectedly":                                                                         "livekit_process_exited",
	"livekit: retrying download":                                                                                   "livekit_retrying_download",
	"livekit: too many rapid failures, giving up":                                                                  "livekit_restart_exhausted",
	"log stream: failed to clear write deadline; stream may be cut by WriteTimeout":                                "log_stream_clear_write_deadline_failed",
	"login: GetUserByUsername failed":                                                                              "login_getuserbyusername_failed",
	"maintenance loop did not exit before shutdown timeout":                                                        "maintenance_loop_shutdown_timeout",
	"maintenance loop: circuit breaker open, skipping tick":                                                        "maintenance_circuit_open",
	"message delivery attachments lookup":                                                                          "message_delivery_attachments_lookup",
	"notifyDMRequestTransition: marshal failed":                                                                    "notifydmrequesttransition_marshal_failed",
	"notifyDMRequestTransition: sender lookup failed, dropping the dm_request push":                                "notifydmrequesttransition_sender_lookup_failed",
	"notifyNSFWAck: marshal failed":                                                                                "notifynsfwack_marshal_failed",
	"partial-auth: consuming a persisted challenge failed":                                                         "partial_auth_consuming_a_persisted_challenge",
	"partial-auth: deleting an exhausted challenge failed":                                                         "partial_auth_deleting_an_exhausted_challenge",
	"partial-auth: persisting a failure count failed":                                                              "partial_auth_persisting_a_failure_count",
	"partial-auth: persisting a restored challenge failed":                                                         "partial_auth_persisting_a_restored_challenge",
	"partial-auth: reading a persisted challenge failed":                                                           "partial_auth_reading_a_persisted_challenge",
	"pending enrolment: deleting a persisted secret failed":                                                        "pending_enrolment_deleting_a_persisted_secret",
	"pending enrolment: reading a persisted secret failed":                                                         "pending_enrolment_reading_a_persisted_secret",
	"pending enrolment: unsealing a persisted secret failed":                                                       "pending_enrolment_unsealing_a_persisted_secret",
	"plugin disable failed":                                                                                        "plugin_disable_failed",
	"plugin enable failed":                                                                                         "plugin_enable_failed",
	"plugin install failed":                                                                                        "plugin_install_failed",
	"plugin list failed":                                                                                           "plugin_list_failed",
	"plugin loader: failed to scan directory":                                                                      "plugin_loader_failed_to_scan_directory",
	"plugin lookup failed":                                                                                         "plugin_lookup_failed",
	"plugin runtime init failed; continuing without plugins":                                                       "plugin_runtime_init_failed",
	"plugin uninstall failed":                                                                                      "plugin_uninstall_failed",
	"plugin: activation failed":                                                                                    "plugin_activation_failed",
	"plugin: could not preserve enabled flag across runtime-less upgrade":                                          "plugin_could_not_preserve_enabled_flag",
	"plugin: disable failed during uninstall":                                                                      "plugin_disable_failed_during_uninstall",
	"plugin: enabled row has no on-disk manifest, skipping":                                                        "plugin_enabled_row_missing_manifest",
	"plugin: failed to install from disk":                                                                          "plugin_failed_to_install_from_disk",
	"plugin: failed to remove backed-up previous version after a successful upgrade":                               "plugin_remove_backed_up_version_failed",
	"plugin: failed to remove half-installed upgrade after installFromDisk error":                                  "plugin_remove_half_installed_upgrade_failed",
	"plugin: failed to remove plugin directory after uninstall":                                                    "plugin_failed_to_remove_plugin_directory",
	"plugin: failed to remove stale staging dir":                                                                   "plugin_failed_to_remove_stale_staging",
	"plugin: failed to restore previous plugin version after a failed upgrade":                                     "plugin_failed_to_restore_previous_plugin",
	"plugin: reactivate after upgrade failed":                                                                      "plugin_reactivate_after_upgrade_failed",
	"plugin: skipping command binding":                                                                             "plugin_skipping_command_binding",
	"plugin: some plugin directories failed to scan and were skipped":                                              "plugin_directories_scan_failed",
	"port in use, retrying...":                                                                                     "port_in_use_retrying",
	"pprof listener error":                                                                                         "pprof_listener_error",
	"pre-restore WAL checkpoint failed":                                                                            "pre_restore_wal_checkpoint_failed",
	"pre-restore backup failed — aborting restore":                                                                 "restore_safety_backup_failed",
	"ratelimit: failed to clean up expired persisted lockouts":                                                     "ratelimit_clean_up_expired_lockouts_failed",
	"ratelimit: failed to delete persisted lockout; it may reappear after a restart":                               "ratelimit_failed_to_delete_persisted_lockout",
	"ratelimit: failed to load persisted lockouts; starting with none":                                             "ratelimit_failed_to_load_persisted_lockouts",
	"ratelimit: failed to persist lockout; it will not survive a restart":                                          "ratelimit_persist_lockout_failed",
	"recovery assist: GetRoleByID failed":                                                                          "recovery_assist_getrolebyid_failed",
	"recovery assist: GetUserByID (actor) failed":                                                                  "recovery_assist_getuserbyid_actor_failed",
	"recovery assist: GetUserByID failed":                                                                          "recovery_assist_getuserbyid_failed",
	"recovery assist: UpsertRecoveryAssist failed":                                                                 "recovery_assist_upsertrecoveryassist_failed",
	"recovery codes: consuming failed":                                                                             "recovery_codes_consuming_failed",
	"recovery codes: counting the remainder failed":                                                                "recovery_codes_counting_the_remainder_failed",
	"recovery codes: deleting after 2FA disable failed":                                                            "recovery_codes_delete_after_2fa_disable_failed",
	"recovery codes: generation failed":                                                                            "recovery_codes_generation_failed",
	"recovery codes: listing failed":                                                                               "recovery_codes_listing_failed",
	"recovery codes: storing failed":                                                                               "recovery_codes_storing_failed",
	"recovery kit: store failed":                                                                                   "recovery_kit_store_failed",
	"recovery locked after repeated failures":                                                                      "recovery_locked_after_repeated_failures",
	"recovery: GetRecoveryAssist failed":                                                                           "recovery_getrecoveryassist_failed",
	"recovery: GetRecoveryKit failed":                                                                              "recovery_getrecoverykit_failed",
	"recovery: GetUserByUsername failed":                                                                           "recovery_getuserbyusername_failed",
	"recovery: redeem failed":                                                                                      "recovery_redeem_failed",
	"recovery: session issue failed after redeem":                                                                  "recovery_session_issue_failed_after_redeem",
	"register: account creation failed":                                                                            "register_account_creation_failed",
	"registration_mode holds an unknown value; treating registration as closed":                                    "registration_mode_unknown_value",
	"report event not recorded":                                                                                    "report_event_not_recorded",
	"report evidence: failed to check NSFW acknowledgement":                                                        "report_evidence_failed_to_check_nsfw",
	"report evidence: failed to read source channel":                                                               "report_evidence_failed_to_read_source",
	"restart backstop fired — teardown exceeded its budget, exiting for handoff":                                   "restart_backstop_fired",
	"restart requested but no restart coordinator is wired — restart the server manually":                          "restart_requested_but_no_restart_coordinator",
	"restart: cannot determine executable path — manual restart required":                                          "restart_cannot_determine_executable_path_manual",
	"restart: spawning the replacement process FAILED — manual restart required":                                   "restart_spawning_the_replacement_process_failed",
	"restore copy failed — rolling back to the pre-restore safety copy":                                            "restore_copy_failed_rolling_back",
	"restore refused: backup failed integrity check":                                                               "restore_verification_failed",
	"restore refused: backup schema is newer than this server":                                                     "restore_refused_backup_schema_is_newer",
	"restore refused: could not preserve message retry cutoff":                                                     "restore_refused_preserve_retry_cutoff_failed",
	"restore refused: could not read backup schema version":                                                        "restore_refused_read_schema_version_failed",
	"retention marker: messages present past the recorded cutoff, removed again":                                   "retention_marker_messages_past_cutoff",
	"retention markers replayed":                                                                                   "retention_markers_replayed",
	"retention: journaled replay purge failed again":                                                               "retention_journaled_replay_purge_failed_again",
	"retention: replay purge failed, journaled for the next tick":                                                  "retention_replay_purge_failed",
	"retention: resuming unfinished runs":                                                                          "retention_resuming_unfinished_runs",
	"role deleted":                                                                                                 "role_deleted",
	"role service: failed to list role members":                                                                    "role_service_list_role_members_failed",
	"rollback from the pre-restore safety copy failed — recover manually":                                          "restore_rollback_failed",
	"scheduled backup failed":                                                                                      "scheduled_backup_failed",
	"server exited with error":                                                                                     "server_exited_with_error",
	"server.browser_client_enabled is set, but this build hosts no browser client — the key has no effect yet: no route is mounted and no asset is served": "server_browser_client_enabled_no_effect",
	"service error": "service_error",
	"session cap: failed to evict oldest sessions":                                      "session_cap_failed_to_evict_oldest",
	"session sweep: batch session lookup failed":                                        "session_storage_failed",
	"setup restart skipped: another restart-sensitive operation is already in progress": "setup_restart_skipped_operation_in_progress",
	"setup wizard: saving settings failed":                                              "setup_wizard_saving_settings_failed",
	"setup wizard: writing config failed":                                               "setup_wizard_writing_config_failed",
	"setup: failed to create session":                                                   "setup_failed_to_create_session",
	"setup: failed to create the default text channel":                                  "setup_default_text_channel_failed",
	"setup: failed to create the default voice channel":                                 "setup_default_voice_channel_failed",
	"setup: failed to generate bootstrap invite":                                        "setup_failed_to_generate_bootstrap_invite",
	"setup: failed to generate session token":                                           "setup_failed_to_generate_session_token",
	"shutdown step failed after an earlier failure":                                     "shutdown_step_failed_after_earlier_failure",
	"storage: could not release a charge; the next recount will":                        "storage_could_not_release_a_charge",
	"storage: could not resize a reservation to the bytes written":                      "storage_could_not_resize_a_reservation",
	"storage: failed to remove partial file":                                            "storage_failed_to_remove_partial_file",
	"sweepStaleVoiceStates: AllStates failed":                                           "sweepstalevoicestates_allstates_failed",
	"sweepStaleVoiceStates: LeaveIfMatch failed":                                        "sweepstalevoicestates_leaveifmatch_failed",
	"sweepStaleVoiceStates: evicted participant whose CONNECT_VOICE was revoked":        "sweepstalevoicestates_evicted_revoked_participant",
	"sweepStaleVoiceStates: permission check failed, skipping this tick":                "sweepstalevoicestates_permission_check_failed",
	"sweepStaleVoiceStates: removed ghost voice state":                                  "voice_ghost_removed",
	"telemetry init failed; continuing without OpenTelemetry":                           "telemetry_init_failed",
	"telemetry shutdown returned error":                                                 "telemetry_shutdown_returned_error",
	"telemetry.enabled is set but this build has no OpenTelemetry SDK; rebuild with -tags otel for the configured exporter to take effect":                                                 "telemetry_enabled_without_otel_sdk",
	"the erasure history is absent: the marker file was missing at start-up, so nothing can name which accounts were erased before it was lost and a restored backup may serve them again": "erasure_history_absent",
	"the previous run did not shut down cleanly":                                   "previous_run_unclean_shutdown",
	"totp: recording a used code failed; refusing the code":                        "totp_recording_a_used_code_failed",
	"totp: releasing a used code failed":                                           "totp_releasing_a_used_code_failed",
	"unknown logging.level, keeping info":                                          "unknown_logging_level_keeping_info",
	"unknown server.restart_mode, using auto detection":                            "unknown_server_restart_mode_using_auto",
	"update check failed":                                                          "update_check_failed",
	"update check failed during apply":                                             "update_check_failed_during_apply",
	"update download/verify failed":                                                "update_download_verify_failed",
	"update: CRITICAL — recovery rename also failed, server binary may be missing": "update_critical_recovery_rename_also_failed",
	"update: committing staged binary failed, restoring original binary":           "update_commit_staged_binary_failed",
	"update: rename current to old failed":                                         "update_rename_current_to_old_failed",
	"update: staged binary re-verification failed, aborting update":                "update_staged_binary_re_verification_failed",
	"update: writing the outcome audit row failed":                                 "update_outcome_audit_row_failed",
	"upload.max_size_mb is 0, uploads are disabled":                                "upload_max_size_zero_uploads_disabled",
	"using default or placeholder LiveKit credentials — voice will be disabled; set voice.livekit_api_key and voice.livekit_api_secret in config.yaml (or LIVEKIT_API_KEY / LIVEKIT_API_SECRET in .env under Docker)": "using_default_or_placeholder_livekit_credentials",
	"verify-totp: GetUserByID failed":                                   "verify_totp_getuserbyid_failed",
	"voice permission reconciliation deferred":                          "voice_permission_reconcile_deferred",
	"voice reconcile: AllStates failed":                                 "voice_reconcile_allstates_failed",
	"voice reconcile: LeaveIfMatch failed":                              "voice_reconcile_leaveifmatch_failed",
	"voice reconcile: ListParticipants failed, skipping room":           "voice_reconcile_listparticipants_failed",
	"voice reconcile: leaving unparseable SFU identity":                 "voice_reconcile_leaving_unparseable_sfu_identity",
	"voice reconcile: re-reading orphan's voice state failed, skipping": "voice_reconcile_reread_orphan_voice_state_failed",
	"voice reconcile: reaped voice membership with no SFU participant":  "voice_reconcile_reaped_membership_without_participant",
	"voice reconcile: removing orphan participant failed":               "voice_reconcile_remove_orphan_participant_failed",
	"voice.node_ip is ignored while voice.advertise_internal_ip is on — LiveKit detects its public address over STUN instead": "voice_node_ip_ignored_with_advertise_internal_ip",
	"voice.node_ip is not a public address — remote clients will join voice and then hear no audio":                           "voice_node_ip_not_public",
	"voice: reading state for a server-deafen rollback":                                                                       "voice_read_state_for_server_deafen_rollback_failed",
	"voice: restoring an owned server mute after a channel switch":                                                            "voice_restoring_owned_server_mute_after_switch",
	"voice: restoring server deafen after a channel switch":                                                                   "voice_restoring_server_deafen_after_switch",
	"voice: restoring server mute after a channel switch":                                                                     "voice_restoring_server_mute_after_switch",
	"voice: rolling back a server deafen":                                                                                     "voice_rolling_back_a_server_deafen",
	"waf: CRS detect-mode matches":                                                                                            "waf_crs_detect_mode_matches",
	"waf: CRS rule matched":                                                                                                   "waf_crs_rule_matched",
	"waf: failed to create WAF engine, continuing without WAF":                                                                "waf_failed_to_create_waf_engine",
	"waf: failed to load OWASP CRS, continuing with inline rules only":                                                        "waf_failed_to_load_owasp_crs",
	"waf: request blocked":                                                                                                    "waf_request_blocked",
	"waf: unknown server.waf_crs_mode, falling back to detect":                                                                "waf_unknown_server_waf_crs_mode",
	"wireAuth: bundle has no erasure runner; account deletion will run through AuthService's private runner, which records no deletion marker — a restore can resurrect an erased account": "wireauth_bundle_has_no_erasure_runner",
	"writeJSON: failed to encode response":                   "writejson_failed_to_encode_response",
	"ws MuteForTimeout MuteForTimeoutSession":                "ws_mutefortimeout_mutefortimeoutsession",
	"ws MuteForTimeout MuteParticipant failed, rolling back": "ws_mutefortimeout_muteparticipant_failed_rolling_back",
	"ws MuteForTimeout rollback failed":                      "ws_mutefortimeout_rollback_failed",
	"ws SetServerMuteLocked MuteParticipant failed":          "ws_setservermutelocked_muteparticipant_failed",
	"ws StampConnect": "ws_stampconnect",
	"ws UnmuteForTimeout ClearServerMuteOwnedBy": "ws_unmutefortimeout_clearservermuteownedby",
	"ws UnmuteForTimeout MuteParticipant failed": "ws_unmutefortimeout_muteparticipant_failed",
	"ws auth failed": "ws_auth_failed",
	"ws closing unresponsive connection (no pong)":                                                                  "ws_closing_unresponsive_connection_no_pong",
	"ws command parse error":                                                                                        "ws_command_parse_error",
	"ws fresh connect: LeaveVoiceChannelIfMatch failed":                                                             "ws_fresh_connect_leavevoicechannelifmatch_failed",
	"ws handleFreshConnect: computeAllowedChannels failed, skipping voice channel subscription":                     "ws_handlefreshconnect_computeallowedchannels_failed",
	"ws handleMessage invalid JSON":                                                                                 "ws_handlemessage_invalid_json",
	"ws handleMessage unknown type":                                                                                 "ws_handlemessage_unknown_type",
	"ws handleReconnect: buffer window closed just before registration, forcing full ready":                         "ws_handlereconnect_buffer_window_closed_before_registration",
	"ws handleReconnect: cold-tier contiguity probe failed, forcing full ready":                                     "ws_handlereconnect_cold_tier_contiguity_probe_failed",
	"ws handleReconnect: cold-tier oldest-seq probe failed, forcing full ready":                                     "ws_handlereconnect_cold_tier_oldest_seq_probe_failed",
	"ws handleReconnect: cold-tier replay has an interior gap, forcing full ready":                                  "ws_handlereconnect_cold_tier_replay_gap",
	"ws handleReconnect: cold-tier replay hit the row cap, forcing full ready":                                      "ws_handlereconnect_cold_tier_replay_row_cap",
	"ws handleReconnect: cold-tier replay query failed":                                                             "ws_handlereconnect_cold_tier_replay_query_failed",
	"ws handleReconnect: computeAllowedChannels failed, falling back to full ready":                                 "ws_handlereconnect_computeallowedchannels_failed",
	"ws handleReconnect: computeReadableChannels failed, falling back to full ready":                                "ws_handlereconnect_computereadablechannels_failed",
	"ws handleReconnect: resync watermark moved during handshake, forcing full ready":                               "ws_handlereconnect_resync_watermark_moved_during_handshake",
	"ws handleReconnect: retention pruning left a gap before last_seq, forcing full ready":                          "ws_handlereconnect_retention_pruning_gap",
	"ws handleReconnect: ring buffer cannot cover the post-flush tail just before registration, forcing full ready": "ws_handlereconnect_ring_buffer_gap_before_registration",
	"ws handleReconnect: ring buffer cannot cover the post-flush tail, forcing full ready":                          "ws_handlereconnect_ring_buffer_gap",
	"ws handleReconnect: user re-read failed, falling back to full ready":                                           "ws_handlereconnect_user_re_read_failed",
	"ws handleReconnect: visibility changed during handshake, forcing full ready":                                   "ws_handlereconnect_visibility_changed_during_handshake",
	"ws handleVoiceJoin ChannelStates":                                                                              "ws_handlevoicejoin_channelstates",
	"ws handleVoiceJoin GenerateToken":                                                                              "ws_handlevoicejoin_generatetoken",
	"ws handleVoiceJoin Join":                                                                                       "ws_handlevoicejoin_join",
	"ws handleVoiceJoin State":                                                                                      "ws_handlevoicejoin_state",
	"ws handleVoiceJoin invalid voice quality, using default":                                                       "ws_handlevoicejoin_invalid_voice_quality",
	"ws handleVoiceJoin: RemoveParticipant after supersession failed (may already be gone)":                         "ws_handlevoicejoin_removeparticipant_after_supersession_failed",
	"ws handleVoiceModDeafenV2 SetServerDeafen":                                                                     "ws_handlevoicemoddeafenv2_setserverdeafen",
	"ws handleVoiceModDeafenV2 SetServerMute":                                                                       "ws_handlevoicemoddeafenv2_setservermute",
	"ws handleVoiceModMoveV2 CountInChannel":                                                                        "ws_handlevoicemodmovev2_countinchannel",
	"ws handleVoiceModMoveV2 GetChannel":                                                                            "ws_handlevoicemodmovev2_getchannel",
	"ws handleVoiceModMoveV2 channelSubject":                                                                        "ws_handlevoicemodmovev2_channelsubject",
	"ws handleVoiceModMuteV2 SetServerMute":                                                                         "ws_handlevoicemodmutev2_setservermute",
	"ws handleVoiceTokenRefreshV2 GenerateToken":                                                                    "ws_handlevoicetokenrefreshv2_generatetoken",
	"ws handleVoiceTokenRefreshV2 GetVoiceState":                                                                    "ws_handlevoicetokenrefreshv2_getvoicestate",
	"ws handler internal error":                                                                                     "socket_handler_failed",
	"ws liveVoiceEventsSince: cold-tier supplement exceeds the row cap, skipping truncated window":                  "ws_livevoiceeventssince_cold_tier_supplement_over_cap",
	"ws liveVoiceEventsSinceForUser: cold-tier supplement exceeds the row cap, skipping truncated window":           "ws_livevoiceeventssinceforuser_cold_tier_supplement_over_cap",
	"ws no V2 handler for constructed command":                                                                      "ws_no_v2_handler_for_command",
	"ws plugin broadcast permission denied":                                                                         "ws_plugin_broadcast_permission_denied",
	"ws post-register session recheck: lookup failed, skipping":                                                     "ws_post_register_session_recheck_lookup_failed",
	"ws refuseIfServerSilenced GetVoiceState":                                                                       "ws_refuseifserversilenced_getvoicestate",
	"ws rollbackVoiceJoin LeaveIfMatch":                                                                             "ws_rollbackvoicejoin_leaveifmatch",
	"ws service internal error":                                                                                     "message_service_failed",
	"ws session recheck: lookup failed, skipping":                                                                   "ws_session_recheck_lookup_failed_skipping",
	"ws too many invalid messages, closing connection":                                                              "ws_too_many_invalid_messages_closing",
	"ws upgrade failed":                                "ws_upgrade_failed",
	"ws voiceModTarget GetChannel":                     "ws_voicemodtarget_getchannel",
	"ws voiceModTarget State":                          "ws_voicemodtarget_state",
	"ws voiceModTarget channelSubject":                 "ws_voicemodtarget_channelsubject",
	"ws voiceStateBroadcast GetVoiceState":             "ws_voicestatebroadcast_getvoicestate",
	"ws voice_join refused":                            "voice_join_refused",
	"ws voice_join: capacity pre-check failed":         "ws_voice_join_capacity_pre_check_failed",
	"ws voice_join: permission lookup failed, denying": "ws_voice_join_permission_lookup_failed",
	"ws writePump error":                               "socket_write_failed",
	"ws: allowed_origins contains wildcard '*' — accepting connections from ANY origin (insecure)": "ws_allowed_origins_wildcard",
	"ws: buildReady HasNSFWAcknowledgement failed, reporting unacknowledged":                       "ws_buildready_hasnsfwacknowledgement_failed",
	"ws: channelNSFWFilter GetChannel failed, denying all recipients":                              "ws_channelnsfwfilter_getchannel_failed",
	"ws: channelNSFWFilter ListNSFWAcknowledgedUserIDs failed, denying":                            "ws_channelnsfwfilter_listnsfwacknowledgeduserids_failed",
	"ws: channelReadAudience GetChannel failed, denying":                                           "ws_channelreadaudience_getchannel_failed_denying",
	"ws: channelReadAudience GetDMParticipantIDs failed, denying":                                  "ws_channelreadaudience_getdmparticipantids_failed",
	"ws: client high+normal buffers full, closing connection":                                      "ws_client_high_normal_buffers_full",
	"ws: client send buffer full (trySend), closing connection to force reconnect":                 "ws_client_send_buffer_full_trysend",
	"ws: client send buffer full, closing connection to force reconnect":                           "ws_client_send_buffer_full_closing",
	"ws: failed to send auth_ok":                                                                   "ws_failed_to_send_auth_ok",
	"ws: failed to send auth_ok (reconnect)":                                                       "ws_failed_to_send_auth_ok_reconnect",
	"ws: failed to send ready payload":                                                             "ws_failed_to_send_ready_payload",
	"ws: failed to send replay event":                                                              "ws_failed_to_send_replay_event",
	"ws: frameReadableNow GetChannel failed, dropping frame":                                       "ws_framereadablenow_getchannel_failed",
	"ws: frameReadableNow HasNSFWAcknowledgement failed, dropping frame":                           "ws_framereadablenow_hasnsfwacknowledgement_failed",
	"ws: frameReadableNow found no such channel, dropping frame":                                   "ws_framereadablenow_found_no_such_channel",
	"ws: requirePerm GetRoleForUser failed":                                                        "ws_requireperm_getroleforuser_failed",
	"ws: requirePerm called with nil dependency":                                                   "ws_requireperm_called_with_nil_dependency",
	"ws: role lookup failed during handshake, closing connection":                                  "ws_role_lookup_failed_during_handshake",
	"ws: role lookup failed, disconnecting":                                                        "ws_role_lookup_failed_disconnecting",
	"ws: user re-read failed, disconnecting":                                                       "ws_user_re_read_failed_disconnecting",
	"backup maintenance failed":                                                                    "backup_maintenance_failed",
	"retention sweep failed":                                                                       "retention_failed",
	"report content retention failed":                                                              "report_retention_failed",
	"moderation action retention failed":                                                           "moderation_retention_failed",
	"failed to delete expired sessions":                                                            "maintenance_expired_sessions_failed",
	"failed to delete expired message delivery receipts":                                           "maintenance_delivery_receipts_failed",
	"failed to clean up expired second-factor state":                                               "maintenance_second_factor_cleanup_failed",
	"push subscription sweep failed":                                                               "maintenance_push_subscriptions_failed",
	"failed to delete orphaned attachments":                                                        "maintenance_orphaned_attachments_failed",
	"orphaned voice mute reconciliation failed":                                                    "maintenance_voice_mute_reconciliation_failed",
	"erasure jobs still pending":                                                                   "maintenance_erasure_pending",
	"storage reconciliation failed":                                                                "maintenance_storage_reconciliation_failed",
	"storage recount failed":                                                                       "maintenance_storage_recount_failed",
	"ws handleVoiceMuteV2 UpdateVoiceMute":                                                         "ws_voice_mute_update_failed",
	"ws handleVoiceDeafenV2 UpdateVoiceDeafen":                                                     "ws_voice_deafen_update_failed",
	"ws handleVoiceCameraV2 UpdateVoiceCamera":                                                     "ws_voice_camera_disable_failed",
	"ws handleVoiceScreenshareV2 UpdateVoiceScreenshare":                                           "ws_voice_screenshare_disable_failed",
	"ws enableVideoSlot GetChannel":                                                                "ws_video_slot_getchannel_failed",
	"ws enableVideoSlot EnableIfUnderLimit":                                                        "ws_video_slot_reserve_failed",
	"ws enableVideoSlot unconditional enable":                                                      "ws_video_slot_enable_failed",
	"RemoveParticipant failed (may already be gone)":                                               "livekit_remove_participant_failed",
	"upload refused: server storage below its reserved headroom":                                   "upload_refused_low_disk",
	"upload failed: server storage error":                                                          "upload_storage_error",
	"upload rejected":                                                                              "upload_rejected",
	"auto-generated key saved to disk":                                                             "key_auto_generated",
	"livekit companion output":                                                                     "livekit_companion_log",
	"database backup created":                                                                      "backup_created",
}
