package config

// SettingCopy is the owner-facing text for one panel-editable key: a plain
// label, what the setting does, the value most owners should run and why, and
// what changing it affects. Every override applies at the next restart, so the
// page states that once instead of per key. The completeness test pins that
// every editable key has a full entry.
type SettingCopy struct {
	Label       string `json:"label"`
	Description string `json:"description"`
	Recommended string `json:"recommended"`
	Effect      string `json:"effect"`
}

// SettingCopyFor returns the copy for an editable key.
func SettingCopyFor(key string) (SettingCopy, bool) {
	c, ok := settingCopy[key]
	return c, ok
}

func sc(label, description, recommended, effect string) SettingCopy {
	return SettingCopy{Label: label, Description: description, Recommended: recommended, Effect: effect}
}

var settingCopy = map[string]SettingCopy{
	// Attention panel thresholds.
	"attention.delivery_drops_per_min": sc("Message-drop warning rate",
		"Warn when the server drops or sheds this many live messages per minute.",
		"1 (default). Raise it only if the warning fires on a busy server that is otherwise healthy.",
		"Lower values warn sooner; higher values stay quiet longer. Only the Attention panel is affected."),
	"attention.disk_warn_free_mb": sc("Low-disk warning level (MB)",
		"Warn when free space on the data drive falls below this many megabytes.",
		"1024 (default), or about 5 to 10% of the drive. 0 leaves only the critical level.",
		"A higher value gives more notice before uploads are refused; it never blocks anything itself."),
	"attention.reconnects_per_min": sc("Reconnect warning rate",
		"Warn when clients reconnect more than this many times per minute.",
		"30 (default). Raise it for a large community.",
		"Many reconnects usually mean a network or proxy problem. Only the Attention panel is affected."),
	"attention.writer_wait_ms_per_min": sc("Database-wait warning (ms per minute)",
		"Warn when requests spend this many milliseconds a minute waiting for the database writer.",
		"5000 (default).",
		"Lower warns about smaller slowdowns; higher hides them. Only the Attention panel is affected."),

	// Database.
	"database.max_readers": sc("Database read connections",
		"How many read connections the database keeps open. 0 chooses automatically.",
		"0 (default). The automatic size suits almost every server.",
		"More connections use more memory and rarely add speed. Fewer can slow busy servers."),
	"database.type": sc("Database type",
		"The database engine. SQLite is the only supported one.",
		"sqlite (the only value).",
		"Nothing to change; any other value is refused."),
	"database.path": sc("Database file location",
		"Where the SQLite database file is stored.",
		"data/chatserver.db (default). Change it only when moving the data to another drive.",
		"Pointing at a different path starts with whatever database is there, not your current one. Copy the file first."),

	// Event persistence.
	"event_persistence.batch_flush_ms": sc("Event save delay (ms)",
		"The longest wait before buffered events are written to the event log.",
		"100 (default).",
		"Higher values write less often but could lose more recent events if the server crashes."),
	"event_persistence.batch_size": sc("Event save batch size",
		"The most events written to the event log in one go.",
		"50 (default).",
		"Larger batches are slightly more efficient; smaller ones keep the log more current."),
	"event_persistence.enabled": sc("Keep event log on disk",
		"Saves recent events so clients that reconnect after a longer gap can catch up.",
		"On (default).",
		"Off keeps only a short in-memory history, so members who were offline a while get a full reload instead."),
	"event_persistence.pruner_interval_minutes": sc("Event log cleanup interval (minutes)",
		"How often old events are removed from the event log.",
		"60 (default).",
		"Shorter intervals keep the log tidier at slightly more background work."),
	"event_persistence.replay_cold_limit": sc("Catch-up limit after reconnect",
		"The most saved events replayed to one client that reconnects.",
		"5000 (default).",
		"Beyond this, the client does a full reload instead. Higher bridges longer gaps but costs more per reconnect."),
	"event_persistence.replay_ring_size": sc("Recent-event memory size",
		"How many of the latest events are kept in memory for fast reconnects.",
		"1000 (default).",
		"Higher uses a little more memory and lets more reconnects skip the disk."),
	"event_persistence.retention_hours": sc("Event log retention (hours)",
		"How long saved events are kept for reconnecting clients.",
		"24 (default).",
		"Longer lets members who were offline for days catch up quickly, at the cost of disk space."),

	// Logging.
	"logging.level": sc("Log detail level",
		"How much the server writes to its logs.",
		"info (default). Use debug only while troubleshooting.",
		"debug is very verbose and may fill the disk; warn and error hide routine events."),

	// Moderation.
	"moderation.action_retention_days": sc("Warning and timeout history (days)",
		"How long old warnings and timeouts are kept before being retired.",
		"90 (default). 0 keeps them forever.",
		"Shorter protects privacy; longer keeps a fuller record for moderators. Bans and kicks are always kept."),
	"moderation.report_retention_days": sc("Closed report detail (days)",
		"How long a closed report's evidence and notes are kept.",
		"180 (default). 0 keeps them forever.",
		"After this the report's outcome is kept but its evidence and notes are deleted."),

	// Plugins.
	"plugins.cpu_budget_ms": sc("Plugin time limit (ms)",
		"The most processing time one plugin call may use.",
		"100 (default).",
		"Higher lets heavy plugins finish but can slow the server if a plugin misbehaves."),
	"plugins.directory": sc("Plugins folder",
		"Where plugin packages are loaded from.",
		"data/plugins (default).",
		"Only plugins you trust should be in this folder; they run inside the server."),
	"plugins.enabled": sc("Enable plugins",
		"Loads plugins from the plugins folder at startup.",
		"Off (default) unless you use plugins.",
		"On runs third-party code in the server's sandbox. Leave it off if you do not need it."),
	"plugins.http_allowlist": sc("Websites plugins may contact",
		"Comma-separated host names plugins may make web requests to.",
		"Empty (default). Add only hosts a plugin truly needs.",
		"Empty means plugins cannot reach the internet. Each host you add widens what plugins can send out."),
	"plugins.max_memory_mb": sc("Plugin memory limit (MB)",
		"The most memory one plugin may use.",
		"64 (default).",
		"Higher lets bigger plugins run but raises the server's memory use."),

	// Push.
	"push.contact": sc("Push contact address",
		"An email address sent to push services so they can reach you about problems.",
		"Your admin email, if push is on. Empty is fine otherwise.",
		"Some push services refuse requests without one. It is shared with those services, not with members."),
	"push.dispatch_enabled": sc("Send push notifications",
		"Lets the server send notifications to members' devices through their browser's push service.",
		"Off (default). Turn on together with Enable push.",
		"On makes the server contact outside push services. Has no effect unless Enable push is also on."),
	"push.enabled": sc("Enable push registration",
		"Lets members' devices register for push notifications.",
		"Off (default) until you want push.",
		"Off hides push from members. Turning it off later keeps existing registrations but sends nothing."),
	"push.subscription_ttl_days": sc("Push registration lifetime (days)",
		"Removes a device's push registration if it has not checked in for this long.",
		"90 (default).",
		"Shorter cleans up sooner but may drop phones that are rarely opened; they simply re-register."),

	// Security.
	"security.auth_rate_limit_multiplier": sc("Sign-in limit multiplier",
		"Scales how many sign-in and registration attempts one IP address gets. 0 means 1.",
		"1 (default). Raise it only if many members share one address, such as a school or office.",
		"Higher lets shared networks in but makes guessing passwords easier. Lower is stricter."),
	"security.expensive_auth_concurrency": sc("Simultaneous password checks",
		"The most password checks run at once. 0 chooses twice the CPU count.",
		"0 (default).",
		"Lower protects a small server from a sign-in flood but can make real sign-ins queue up."),

	// Server.
	"server.admin_allowed_cidrs": sc("Who can open this admin panel",
		"Network ranges (CIDR, comma-separated) allowed to reach the admin panel.",
		"Your home or office network only. The default allows local and private networks.",
		"A wrong value can lock you out of this panel, so a typed confirmation is required."),
	"server.allowed_origins": sc("Allowed web origins",
		"Websites allowed to connect to the server from a browser.",
		"Empty (default) unless you host a browser client.",
		"Each entry lets that site talk to your server. Add only sites you control."),
	"server.browser_client_enabled": sc("Host a browser client",
		"Lets this server host a web version of the client.",
		"Off (default). This build ships no browser files yet.",
		"Currently hosts nothing; reserved for a later release."),
	"server.livekit_webhook_allowed_cidrs": sc("Networks allowed to send voice events",
		"Network ranges allowed to call the voice server's webhook.",
		"Empty (default) to reuse the admin ranges. Set it when voice runs on another machine.",
		"Too narrow stops voice-room updates from reaching the server."),
	"server.max_ws_connections": sc("Maximum live connections",
		"The most members that can be connected at once. 0 means no limit.",
		"0 (default), or a number matched to your server's memory for a large community.",
		"Members over the limit are refused until others disconnect."),
	"server.metrics_allowed_cidrs": sc("Networks allowed to read metrics",
		"Network ranges allowed to read the metrics endpoints.",
		"Empty (default) to reuse the admin ranges. Add your monitoring server if you have one.",
		"Wider exposes server statistics to more machines."),
	"server.min_free_disk_mb": sc("Reserved free disk space (MB)",
		"Uploads are refused and health shows degraded when free space falls below this.",
		"256 (default). 0 turns the safety margin off.",
		"Higher stops uploads earlier and protects the database from a full disk."),
	"server.pprof_block_profile_rate": sc("Profiler: blocking sample rate",
		"How often the profiler samples blocked time while profiling is on.",
		"100000 (default). Leave it unless a developer asks.",
		"Only matters when Enable profiler is on. Lower numbers sample more and cost more CPU."),
	"server.pprof_enabled": sc("Enable profiler",
		"Opens a developer profiling page on this machine only.",
		"Off (default). Turn on only while troubleshooting.",
		"Reachable from the server itself, never the network. It adds some overhead while on."),
	"server.pprof_mutex_profile_fraction": sc("Profiler: lock sample rate",
		"How often the profiler samples lock contention while profiling is on.",
		"5 (default). Leave it unless a developer asks.",
		"Only matters when Enable profiler is on. 0 turns this sampling off."),
	"server.port": sc("Server port",
		"The port the server listens on for members and this panel.",
		"8443 (default). Change it only if that port is already in use.",
		"Members must connect to the new port, and your router or firewall rules must follow. A typed confirmation is required."),
	"server.reachability_report_enabled": sc("Detailed network report",
		"Adds the full list of server network addresses to the connection diagnostics.",
		"Off (default). Turn on when working out port forwarding.",
		"The report reveals your network layout, but only to admins."),
	"server.restart_mode": sc("How the server restarts",
		"Whether restarts are left to a service manager or the server relaunches itself.",
		"auto (default). Use supervised under NSSM or a similar manager.",
		"The wrong mode can leave the server stopped after an update or restart. A typed confirmation is required."),
	"server.trusted_proxies": sc("Trusted reverse proxies",
		"Addresses of proxies in front of the server whose client-IP headers are believed.",
		"Empty (default) with no proxy. List only your own proxy's address.",
		"Trusting the wrong address lets people fake their IP and bypass limits. A typed confirmation is required."),
	"server.waf_crs_mode": sc("Web firewall rule mode",
		"How strict the web firewall's rule set is when the firewall is on.",
		"detect (default): log suspicious requests without blocking.",
		"block can wrongly reject normal chat messages; try it only after watching detect for a while."),
	"server.waf_enabled": sc("Enable web firewall",
		"Screens incoming requests for common attacks.",
		"Off (default). Turn on if the server is exposed to the internet.",
		"Adds a little processing to every request. Pair it with detect mode first."),
	"server.waf_paranoia_level": sc("Web firewall strictness",
		"How aggressively the firewall's rule set matches, from 1 to 4.",
		"2 (default).",
		"Higher catches more but wrongly blocks more normal traffic. Only matters when the firewall is on."),

	// TLS.
	"tls.acme_cache_dir": sc("Certificate cache folder",
		"Where automatically obtained certificates are stored.",
		"data/acme_certs (default).",
		"A new folder starts with no certificates and re-requests them. A typed confirmation is required."),
	"tls.cert_file": sc("Certificate file",
		"The HTTPS certificate file used in manual mode.",
		"Leave as is unless you bring your own certificate.",
		"A wrong path stops secure connections from starting. A typed confirmation is required."),
	"tls.domain": sc("Domain name",
		"The public domain for automatic certificates.",
		"Your domain, when using automatic certificates.",
		"It must point at this server or certificates will fail. A typed confirmation is required."),
	"tls.key_file": sc("Certificate key file",
		"The private key file that matches the certificate, in manual mode.",
		"Leave as is unless you bring your own certificate.",
		"A wrong path stops secure connections from starting. A typed confirmation is required."),
	"tls.mode": sc("Secure connection mode",
		"How the server gets its HTTPS certificate: off, self_signed, manual or acme.",
		"self_signed (default) for private use. acme for a public domain.",
		"off sends everything unencrypted. A wrong mode can stop members connecting. A typed confirmation is required."),

	// Telemetry.
	"telemetry.enabled": sc("Enable telemetry export",
		"Turns on detailed performance data for monitoring tools.",
		"Off (default) unless you run a monitoring system.",
		"On adds some overhead. Choose where it goes under Telemetry destination."),
	"telemetry.exporter": sc("Telemetry destination",
		"Where performance data goes: none, prometheus or otlp.",
		"none (default).",
		"otlp sends data to the endpoint below. Only matters when telemetry is on."),
	"telemetry.otlp_endpoint": sc("OTLP collector address",
		"The address of the collector that receives data in otlp mode.",
		"Your collector's host:port. Empty otherwise.",
		"Data is sent there, so use a collector you trust."),
	"telemetry.otlp_insecure": sc("Allow unencrypted OTLP",
		"Sends telemetry without encryption.",
		"Off (default). Use only on a private network.",
		"On exposes performance data in transit to anyone on the path."),
	"telemetry.service_name": sc("Telemetry service name",
		"The name that tags this server in monitoring tools.",
		"owncord-server (default). Change it if you run several servers.",
		"Only affects how the server is labelled in your monitoring."),

	// Upload.
	"upload.max_size_mb": sc("Largest upload (MB)",
		"The biggest file one member can upload.",
		"100 (default). Keep it modest on a small drive.",
		"Higher allows big files but fills storage faster."),
	"upload.storage_dir": sc("Upload storage folder",
		"Where uploaded files and avatars are stored.",
		"data/uploads (default).",
		"Existing uploads are not moved, so old files show as missing until you copy them. A typed confirmation is required."),
	"upload.user_quota_mb": sc("Storage limit per member (MB)",
		"The total upload space each member may use. 0 means no limit.",
		"0 (default), or a limit that fits your drive.",
		"Members at their limit cannot upload until they delete files."),

	// Backup.
	"backup.dir": sc("Backup folder",
		"Where database backups are written.",
		"data/backups (default). Better on a separate drive.",
		"Backups on the same drive are lost with it. Existing backups are not moved. A typed confirmation is required."),

	// GIF, GitHub.
	"gif.api_key": sc("GIF service key",
		"The Klipy key that turns on the GIF picker. Write-only.",
		"Empty (default) unless you want GIFs.",
		"Empty hides the GIF picker. Clearing it turns GIFs off."),
	"github.owner": sc("Update source: owner",
		"The GitHub account that publishes updates.",
		"J3vb (default).",
		"Changing it makes the server fetch updates from someone else."),
	"github.repo": sc("Update source: repository",
		"The GitHub repository that publishes updates.",
		"OwnCord (default).",
		"Changing it makes the server fetch updates from a different project."),
	"github.token": sc("GitHub access token",
		"An optional token for update checks, such as for a private repository. Write-only.",
		"Empty (default).",
		"Without one, update checks use GitHub's public limits."),

	// Voice.
	"voice.advertise_internal_ip": sc("Allow voice on the local network",
		"Also offers the server's local address so people on your LAN can join voice.",
		"Off (default). Turn on when members join from home and away.",
		"Makes the server's public address setting be ignored."),
	"voice.auto_download_livekit": sc("Download voice server automatically",
		"Fetches and runs the LiveKit voice server for you.",
		"On for fresh installs; off if you run your own.",
		"On downloads a checked release from GitHub. Off needs a voice server you run yourself."),
	"voice.livekit_api_key": sc("Voice server key",
		"The key the server uses to talk to LiveKit. Write-only.",
		"A long random value, never a default one.",
		"A mismatch with LiveKit's own key stops voice working."),
	"voice.livekit_api_secret": sc("Voice server secret",
		"The secret that goes with the voice server key. Write-only.",
		"A long random value, at least 32 characters.",
		"A mismatch with LiveKit's own secret stops voice working."),
	"voice.livekit_binary": sc("Voice server program path",
		"The livekit-server program to start. Empty uses the automatic download if on, else an external server.",
		"Empty (default) with automatic download.",
		"The server runs this file, so only point it at one you trust. A typed confirmation is required."),
	"voice.livekit_url": sc("Voice server address",
		"The WebSocket address of the LiveKit voice server.",
		"ws://localhost:7880 (default) for a voice server on the same machine.",
		"A wrong address means no one can join voice."),
	"voice.livekit_version": sc("Voice server version",
		"Which LiveKit release to download. Empty uses the tested version.",
		"Empty (default).",
		"A different version may not be tested with OwnCord."),
	"voice.node_ip": sc("Public IP for voice",
		"The public address given to voice clients. Empty detects it automatically.",
		"Empty (default). Set it only if detection fails.",
		"A wrong address stops people outside your network from joining voice."),
	"voice.quality": sc("Voice and video quality",
		"The quality level for calls: low, medium or high.",
		"medium (default). Use low on slow connections.",
		"High looks and sounds better but uses more bandwidth for everyone."),
	"voice.udp_port": sc("Voice media port",
		"Sends all voice traffic through one UDP port. 0 uses the 50000 to 60000 range.",
		"0 (default), or one port if you want to forward just one.",
		"Forward this port on your router. If you run your own LiveKit, set the same port in its livekit.yaml. 7880/7881 are not allowed."),
}
