//go:build postgres

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocks.sql

package pgdbgen

import (
	"context"
)

const blockUser = `-- name: BlockUser :exec

INSERT INTO user_blocks (blocker_id, blocked_id) VALUES ($1, $2)
ON CONFLICT (blocker_id, blocked_id) DO NOTHING
`

type BlockUserParams struct {
	BlockerID int64 `json:"blockerId"`
	BlockedID int64 `json:"blockedId"`
}

// PostgreSQL variants of the sqlite user block queries.
// `INSERT OR IGNORE` becomes `INSERT ... ON CONFLICT DO NOTHING`.
func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.Exec(ctx, blockUser, arg.BlockerID, arg.BlockedID)
	return err
}

const isBlocked = `-- name: IsBlocked :one
SELECT 1 FROM user_blocks WHERE blocker_id = $1 AND blocked_id = $2 LIMIT 1
`

type IsBlockedParams struct {
	BlockerID int64 `json:"blockerId"`
	BlockedID int64 `json:"blockedId"`
}

func (q *Queries) IsBlocked(ctx context.Context, arg IsBlockedParams) (int32, error) {
	row := q.db.QueryRow(ctx, isBlocked, arg.BlockerID, arg.BlockedID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const isEitherBlocked = `-- name: IsEitherBlocked :one
SELECT 1 FROM user_blocks
WHERE (blocker_id = $1 AND blocked_id = $2)
   OR (blocker_id = $3 AND blocked_id = $4)
LIMIT 1
`

type IsEitherBlockedParams struct {
	BlockerID   int64 `json:"blockerId"`
	BlockedID   int64 `json:"blockedId"`
	BlockerID_2 int64 `json:"blockerId2"`
	BlockedID_2 int64 `json:"blockedId2"`
}

func (q *Queries) IsEitherBlocked(ctx context.Context, arg IsEitherBlockedParams) (int32, error) {
	row := q.db.QueryRow(ctx, isEitherBlocked,
		arg.BlockerID,
		arg.BlockedID,
		arg.BlockerID_2,
		arg.BlockedID_2,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const unblockUser = `-- name: UnblockUser :exec
DELETE FROM user_blocks WHERE blocker_id = $1 AND blocked_id = $2
`

type UnblockUserParams struct {
	BlockerID int64 `json:"blockerId"`
	BlockedID int64 `json:"blockedId"`
}

func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) error {
	_, err := q.db.Exec(ctx, unblockUser, arg.BlockerID, arg.BlockedID)
	return err
}
