//go:build postgres

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reactions.sql

package pgdbgen

import (
	"context"
)

const addReaction = `-- name: AddReaction :exec

INSERT INTO reactions (message_id, user_id, emoji) VALUES ($1, $2, $3)
`

type AddReactionParams struct {
	MessageID int64  `json:"messageId"`
	UserID    int64  `json:"userId"`
	Emoji     string `json:"emoji"`
}

// PostgreSQL variants of the sqlite reactions queries.
func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) error {
	_, err := q.db.Exec(ctx, addReaction, arg.MessageID, arg.UserID, arg.Emoji)
	return err
}

const getReactionCounts = `-- name: GetReactionCounts :many
SELECT emoji, COUNT(*) AS count
FROM reactions WHERE message_id = $1
GROUP BY emoji
`

type GetReactionCountsRow struct {
	Emoji string `json:"emoji"`
	Count int64  `json:"count"`
}

func (q *Queries) GetReactionCounts(ctx context.Context, messageID int64) ([]GetReactionCountsRow, error) {
	rows, err := q.db.Query(ctx, getReactionCounts, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReactionCountsRow{}
	for rows.Next() {
		var i GetReactionCountsRow
		if err := rows.Scan(&i.Emoji, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReaction = `-- name: RemoveReaction :execrows
DELETE FROM reactions WHERE message_id = $1 AND user_id = $2 AND emoji = $3
`

type RemoveReactionParams struct {
	MessageID int64  `json:"messageId"`
	UserID    int64  `json:"userId"`
	Emoji     string `json:"emoji"`
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeReaction, arg.MessageID, arg.UserID, arg.Emoji)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
