// Generated by scripts/gen-emoji-data.mjs from Unicode emoji-test.txt 15.1. Do not edit.
// Each row is `emoji|skin-tone segments|keywords`; the first keyword is the
// emoji's name. Loaded lazily through emojiCatalog.ts, never imported directly.

export const EMOJI_GROUPS: readonly (readonly [
  (
    | "smileys"
    | "people"
    | "nature"
    | "food"
    | "travel"
    | "activities"
    | "objects"
    | "symbols"
    | "flags"
  ),
  string,
])[] = [
  [
    "smileys",
    `😀||grinning face happy smile grinning_face
😃||smiley face happy smile grinning_face_with_big_eyes
😄||smile happy grin grinning_face_with_smiling_eyes
😁||beaming grin teeth smile beaming_face_with_smiling_eyes
😆||laughing happy squint smile grinning_squinting_face
😅||sweat smile nervous grinning_face_with_sweat
🤣||rofl laughing rolling floor rolling_on_the_floor_laughing
😂||joy tears laughing cry happy face_with_tears_of_joy
🙂||slightly smiling slightly_smiling_face
🙃||upside_down_face
🫠||melting_face
😉||winking_face
😊||blush happy smile shy smiling_face_with_smiling_eyes
😇||innocent angel halo smiling_face_with_halo
🥰||love hearts face smiling smiling_face_with_hearts
😍||heart eyes love smiling_face_with_heart_eyes
🤩||star struck excited star_struck
😘||kiss blowing wink face_blowing_a_kiss
😗||kissing face kissing_face
☺️||smiling_face
😚||kissing_face_with_closed_eyes
😙||kissing_face_with_smiling_eyes
🥲||smiling_face_with_tear
😋||yummy delicious tongue food face_savoring_food
😛||tongue out face_with_tongue
😜||wink tongue playful winking_face_with_tongue
🤪||zany crazy wild zany_face
😝||squinting tongue squinting_face_with_tongue
🤑||money face rich dollar money_mouth_face
🤗||hugging hug hands smiling_face_with_open_hands
🤭||hand over mouth oops giggle face_with_hand_over_mouth
🫢||face_with_open_eyes_and_hand_over_mouth
🫣||face_with_peeking_eye
🤫||shushing quiet secret shh shushing_face
🤔||thinking hmm wonder thinking_face
🫡||saluting_face
🤐||zipper mouth shut secret zipper_mouth_face
🤨||raised eyebrow skeptical face_with_raised_eyebrow
😐||neutral face blank neutral_face
😑||expressionless blank expressionless_face
😶||no mouth silent mute face_without_mouth
🫥||dotted_line_face
😶‍🌫️||face_in_clouds
😏||smirk smug smirking_face
😒||unamused bored annoyed unamused_face
🙄||eye roll whatever face_with_rolling_eyes
😬||grimace awkward teeth grimacing_face
😮‍💨||face_exhaling
🤥||lying pinocchio nose lying_face
🫨||shaking_face
🙂‍↔️||head_shaking_horizontally
🙂‍↕️||head_shaking_vertically
😌||relieved calm peaceful relieved_face
😔||pensive sad thoughtful pensive_face
😪||sleepy tired sleepy_face
🤤||drooling hungry drooling_face
😴||sleeping zzz tired sleeping_face
😷||mask sick medical face face_with_medical_mask
🤒||thermometer sick fever face_with_thermometer
🤕||bandage hurt injured face_with_head_bandage
🤢||nauseous sick green nauseated_face
🤮||vomiting throw up sick face_vomiting
🤧||sneezing_face
🥵||hot face overheated hot_face
🥶||cold face freezing cold_face
🥴||woozy drunk dizzy woozy_face
😵||dizzy spiral knocked out face_with_crossed_out_eyes
😵‍💫||face_with_spiral_eyes
🤯||mind blown exploding head exploding_head
🤠||cowboy hat yeehaw cowboy_hat_face
🥳||party celebration birthday partying_face
🥸||disguised_face
😎||sunglasses cool smiling_face_with_sunglasses
🤓||nerd glasses geek nerd_face
🧐||monocle detective inspect face_with_monocle
😕||confused puzzled confused_face
🫤||face_with_diagonal_mouth
😟||worried concerned worried_face
🙁||frowning sad slightly_frowning_face
☹️||frowning_face
😮||open mouth surprised face_with_open_mouth
😯||hushed_face
😲||astonished shocked wow astonished_face
😳||flushed embarrassed flushed_face
🥺||pleading puppy eyes please pleading_face
🥹||face_holding_back_tears
😦||frowning_face_with_open_mouth
😧||anguished_face
😨||fearful_face
😰||anxious_face_with_sweat
😥||sad_but_relieved_face
😢||crying sad tear crying_face
😭||sobbing crying loud loudly_crying_face
😱||face_screaming_in_fear
😖||confounded_face
😣||persevering_face
😞||disappointed_face
😓||downcast_face_with_sweat
😩||weary_face
😫||tired_face
🥱||yawning_face
😤||steam nose angry huffing face_with_steam_from_nose
😡||rage furious red enraged_face
😠||angry mad angry_face
🤬||cursing swearing symbols angry face_with_symbols_on_mouth
😈||smiling_face_with_horns
👿||angry_face_with_horns
💀||skull dead death skeleton
☠️||skull_and_crossbones
💩||pile_of_poo
🤡||clown_face
👹||ogre
👺||goblin
👻||ghost
👽||alien
👾||alien_monster
🤖||robot
😺||grinning_cat
😸||grinning_cat_with_smiling_eyes
😹||cat_with_tears_of_joy
😻||smiling_cat_with_heart_eyes
😼||cat_with_wry_smile
😽||kissing_cat
🙀||weary_cat
😿||crying_cat
😾||pouting_cat
🙈||see_no_evil_monkey
🙉||hear_no_evil_monkey
🙊||speak_no_evil_monkey
💌||love_letter
💘||heart_with_arrow
💝||heart_with_ribbon
💖||sparkling_heart
💗||growing_heart
💓||beating_heart
💞||revolving_hearts
💕||two_hearts
💟||heart_decoration
❣️||heart_exclamation
💔||broken_heart
❤️‍🔥||heart_on_fire
❤️‍🩹||mending_heart
❤️||red heart love red_heart
🩷||pink_heart
🧡||orange heart love orange_heart
💛||yellow heart love yellow_heart
💚||green heart love green_heart
💙||blue heart love blue_heart
🩵||light_blue_heart
💜||purple heart love purple_heart
🤎||brown_heart
🖤||black heart dark love black_heart
🩶||grey_heart
🤍||white heart love white_heart
💋||kiss_mark
💯||hundred percent perfect score hundred_points
💢||anger symbol mad anger_symbol
💥||boom collision crash
💫||dizzy star shooting
💦||sweat_droplets
💨||dashing_away
🕳️||hole
💬||speech bubble chat talk speech_balloon
👁️‍🗨️||eye speech bubble witness eye_in_speech_bubble
🗨️||speech balloon left left_speech_bubble
🗯️||right_anger_bubble
💭||thought_balloon
💤||sleeping zzz tired`,
  ],
  [
    "people",
    `👋|0|wave hello hi bye hand waving_hand
🤚|0|raised back hand raised_back_of_hand
🖐️|0|hand fingers splayed five hand_with_fingers_splayed
✋|0|raised hand stop high five raised_hand
🖖|0|vulcan spock vulcan_salute
🫱|0|rightwards_hand
🫲|0|leftwards_hand
🫳|0|palm_down_hand
🫴|0|palm_up_hand
🫷|0|leftwards_pushing_hand
🫸|0|rightwards_pushing_hand
👌|0|ok okay perfect ok_hand
🤌|0|pinched fingers italian pinched_fingers
🤏|0|pinching small little pinching_hand
✌️|0|peace victory two victory_hand
🤞|0|crossed fingers luck hope crossed_fingers
🫰|0|hand_with_index_finger_and_thumb_crossed
🤟|0|love you gesture rock love_you_gesture
🤘|0|rock on horns metal sign_of_the_horns
🤙|0|call me hang loose shaka call_me_hand
👈|0|pointing left backhand_index_pointing_left
👉|0|pointing right backhand_index_pointing_right
👆|0|pointing up backhand_index_pointing_up
🖕|0|middle_finger
👇|0|pointing down backhand_index_pointing_down
☝️|0|index pointing up index_pointing_up
🫵|0|index_pointing_at_the_viewer
👍|0|thumbs up like good yes thumbs_up
👎|0|thumbs down dislike bad no thumbs_down
✊|0|raised fist power raised_fist
👊|0|fist bump punch oncoming_fist
🤛|0|left fist bump left_facing_fist
🤜|0|right fist bump right_facing_fist
👏|0|clap applause bravo clapping_hands
🙌|0|raising hands hooray celebrate raising_hands
🫶|0|heart_hands
👐|0|open hands jazz open_hands
🤲|0|palms up together prayer palms_up_together
🤝|0|handshake deal agreement
🙏|0|pray thanks please folded hands folded_hands
✍️|0|writing_hand
💅|0|nail_polish
🤳|0|selfie
💪|0|flexed_biceps
🦾||mechanical_arm
🦿||mechanical_leg
🦵|0|leg
🦶|0|foot
👂|0|ear
🦻|0|ear_with_hearing_aid
👃|0|nose
🧠||brain
🫀||anatomical_heart
🫁||lungs
🦷||tooth
🦴||bone
👀||eyes
👁️||eye
👅||tongue
👄||mouth
🫦||biting_lip
👶|0|baby
🧒|0|child
👦|0|boy
👧|0|girl
🧑|0|person
👱|0|person_blond_hair
👨|0|man
🧔|0|person_beard
🧔‍♂️|0|man_beard
🧔‍♀️|0|woman_beard
👨‍🦰|0|man_red_hair
👨‍🦱|0|man_curly_hair
👨‍🦳|0|man_white_hair
👨‍🦲|0|man_bald
👩|0|woman
👩‍🦰|0|woman_red_hair
🧑‍🦰|0|person_red_hair
👩‍🦱|0|woman_curly_hair
🧑‍🦱|0|person_curly_hair
👩‍🦳|0|woman_white_hair
🧑‍🦳|0|person_white_hair
👩‍🦲|0|woman_bald
🧑‍🦲|0|person_bald
👱‍♀️|0|woman_blond_hair
👱‍♂️|0|man_blond_hair
🧓|0|older_person
👴|0|old_man
👵|0|old_woman
🙍|0|person_frowning
🙍‍♂️|0|man_frowning
🙍‍♀️|0|woman_frowning
🙎|0|person_pouting
🙎‍♂️|0|man_pouting
🙎‍♀️|0|woman_pouting
🙅|0|person_gesturing_no
🙅‍♂️|0|man_gesturing_no
🙅‍♀️|0|woman_gesturing_no
🙆|0|person_gesturing_ok
🙆‍♂️|0|man_gesturing_ok
🙆‍♀️|0|woman_gesturing_ok
💁|0|person_tipping_hand
💁‍♂️|0|man_tipping_hand
💁‍♀️|0|woman_tipping_hand
🙋|0|person_raising_hand
🙋‍♂️|0|man_raising_hand
🙋‍♀️|0|woman_raising_hand
🧏|0|deaf_person
🧏‍♂️|0|deaf_man
🧏‍♀️|0|deaf_woman
🙇|0|person_bowing
🙇‍♂️|0|man_bowing
🙇‍♀️|0|woman_bowing
🤦|0|person_facepalming
🤦‍♂️|0|man_facepalming
🤦‍♀️|0|woman_facepalming
🤷|0|person_shrugging
🤷‍♂️|0|man_shrugging
🤷‍♀️|0|woman_shrugging
🧑‍⚕️|0|health_worker
👨‍⚕️|0|man_health_worker
👩‍⚕️|0|woman_health_worker
🧑‍🎓|0|student
👨‍🎓|0|man_student
👩‍🎓|0|woman_student
🧑‍🏫|0|teacher
👨‍🏫|0|man_teacher
👩‍🏫|0|woman_teacher
🧑‍⚖️|0|judge
👨‍⚖️|0|man_judge
👩‍⚖️|0|woman_judge
🧑‍🌾|0|farmer
👨‍🌾|0|man_farmer
👩‍🌾|0|woman_farmer
🧑‍🍳|0|cook
👨‍🍳|0|man_cook
👩‍🍳|0|woman_cook
🧑‍🔧|0|mechanic
👨‍🔧|0|man_mechanic
👩‍🔧|0|woman_mechanic
🧑‍🏭|0|factory_worker
👨‍🏭|0|man_factory_worker
👩‍🏭|0|woman_factory_worker
🧑‍💼|0|office_worker
👨‍💼|0|man_office_worker
👩‍💼|0|woman_office_worker
🧑‍🔬|0|scientist
👨‍🔬|0|man_scientist
👩‍🔬|0|woman_scientist
🧑‍💻|0|technologist
👨‍💻|0|man_technologist
👩‍💻|0|woman_technologist
🧑‍🎤|0|singer
👨‍🎤|0|man_singer
👩‍🎤|0|woman_singer
🧑‍🎨|0|artist
👨‍🎨|0|man_artist
👩‍🎨|0|woman_artist
🧑‍✈️|0|pilot
👨‍✈️|0|man_pilot
👩‍✈️|0|woman_pilot
🧑‍🚀|0|astronaut
👨‍🚀|0|man_astronaut
👩‍🚀|0|woman_astronaut
🧑‍🚒|0|firefighter
👨‍🚒|0|man_firefighter
👩‍🚒|0|woman_firefighter
👮|0|police_officer
👮‍♂️|0|man_police_officer
👮‍♀️|0|woman_police_officer
🕵️|0|detective
🕵️‍♂️|0|man_detective
🕵️‍♀️|0|woman_detective
💂|0|guard
💂‍♂️|0|man_guard
💂‍♀️|0|woman_guard
🥷|0|ninja
👷|0|construction_worker
👷‍♂️|0|man_construction_worker
👷‍♀️|0|woman_construction_worker
🫅|0|person_with_crown
🤴|0|prince
👸|0|princess
👳|0|person_wearing_turban
👳‍♂️|0|man_wearing_turban
👳‍♀️|0|woman_wearing_turban
👲|0|person_with_skullcap
🧕|0|woman_with_headscarf
🤵|0|person_in_tuxedo
🤵‍♂️|0|man_in_tuxedo
🤵‍♀️|0|woman_in_tuxedo
👰|0|person_with_veil
👰‍♂️|0|man_with_veil
👰‍♀️|0|woman_with_veil
🤰|0|pregnant_woman
🫃|0|pregnant_man
🫄|0|pregnant_person
🤱|0|breast_feeding
👩‍🍼|0|woman_feeding_baby
👨‍🍼|0|man_feeding_baby
🧑‍🍼|0|person_feeding_baby
👼|0|baby_angel
🎅|0|santa_claus
🤶|0|mrs_claus
🧑‍🎄|0|mx_claus
🦸|0|superhero
🦸‍♂️|0|man_superhero
🦸‍♀️|0|woman_superhero
🦹|0|supervillain
🦹‍♂️|0|man_supervillain
🦹‍♀️|0|woman_supervillain
🧙|0|mage
🧙‍♂️|0|man_mage
🧙‍♀️|0|woman_mage
🧚|0|fairy
🧚‍♂️|0|man_fairy
🧚‍♀️|0|woman_fairy
🧛|0|vampire
🧛‍♂️|0|man_vampire
🧛‍♀️|0|woman_vampire
🧜|0|merperson
🧜‍♂️|0|merman
🧜‍♀️|0|mermaid
🧝|0|elf
🧝‍♂️|0|man_elf
🧝‍♀️|0|woman_elf
🧞||genie
🧞‍♂️||man_genie
🧞‍♀️||woman_genie
🧟||zombie
🧟‍♂️||man_zombie
🧟‍♀️||woman_zombie
🧌||troll
💆|0|person_getting_massage
💆‍♂️|0|man_getting_massage
💆‍♀️|0|woman_getting_massage
💇|0|person_getting_haircut
💇‍♂️|0|man_getting_haircut
💇‍♀️|0|woman_getting_haircut
🚶|0|person_walking
🚶‍♂️|0|man_walking
🚶‍♀️|0|woman_walking
🚶‍➡️|0|person_walking_facing_right
🚶‍♀️‍➡️|0|woman_walking_facing_right
🚶‍♂️‍➡️|0|man_walking_facing_right
🧍|0|person_standing
🧍‍♂️|0|man_standing
🧍‍♀️|0|woman_standing
🧎|0|person_kneeling
🧎‍♂️|0|man_kneeling
🧎‍♀️|0|woman_kneeling
🧎‍➡️|0|person_kneeling_facing_right
🧎‍♀️‍➡️|0|woman_kneeling_facing_right
🧎‍♂️‍➡️|0|man_kneeling_facing_right
🧑‍🦯|0|person_with_white_cane
🧑‍🦯‍➡️|0|person_with_white_cane_facing_right
👨‍🦯|0|man_with_white_cane
👨‍🦯‍➡️|0|man_with_white_cane_facing_right
👩‍🦯|0|woman_with_white_cane
👩‍🦯‍➡️|0|woman_with_white_cane_facing_right
🧑‍🦼|0|person_in_motorized_wheelchair
🧑‍🦼‍➡️|0|person_in_motorized_wheelchair_facing_right
👨‍🦼|0|man_in_motorized_wheelchair
👨‍🦼‍➡️|0|man_in_motorized_wheelchair_facing_right
👩‍🦼|0|woman_in_motorized_wheelchair
👩‍🦼‍➡️|0|woman_in_motorized_wheelchair_facing_right
🧑‍🦽|0|person_in_manual_wheelchair
🧑‍🦽‍➡️|0|person_in_manual_wheelchair_facing_right
👨‍🦽|0|man_in_manual_wheelchair
👨‍🦽‍➡️|0|man_in_manual_wheelchair_facing_right
👩‍🦽|0|woman_in_manual_wheelchair
👩‍🦽‍➡️|0|woman_in_manual_wheelchair_facing_right
🏃|0|person_running
🏃‍♂️|0|man_running
🏃‍♀️|0|woman_running
🏃‍➡️|0|person_running_facing_right
🏃‍♀️‍➡️|0|woman_running_facing_right
🏃‍♂️‍➡️|0|man_running_facing_right
💃|0|woman_dancing
🕺|0|man_dancing
🕴️|0|person_in_suit_levitating
👯||people_with_bunny_ears
👯‍♂️||men_with_bunny_ears
👯‍♀️||women_with_bunny_ears
🧖|0|person_in_steamy_room
🧖‍♂️|0|man_in_steamy_room
🧖‍♀️|0|woman_in_steamy_room
🧗|0|person_climbing
🧗‍♂️|0|man_climbing
🧗‍♀️|0|woman_climbing
🤺||person_fencing
🏇|0|horse_racing
⛷️||skier
🏂|0|snowboarder
🏌️|0|person_golfing
🏌️‍♂️|0|man_golfing
🏌️‍♀️|0|woman_golfing
🏄|0|person_surfing
🏄‍♂️|0|man_surfing
🏄‍♀️|0|woman_surfing
🚣|0|person_rowing_boat
🚣‍♂️|0|man_rowing_boat
🚣‍♀️|0|woman_rowing_boat
🏊|0|person_swimming
🏊‍♂️|0|man_swimming
🏊‍♀️|0|woman_swimming
⛹️|0|person_bouncing_ball
⛹️‍♂️|0|man_bouncing_ball
⛹️‍♀️|0|woman_bouncing_ball
🏋️|0|person_lifting_weights
🏋️‍♂️|0|man_lifting_weights
🏋️‍♀️|0|woman_lifting_weights
🚴|0|person_biking
🚴‍♂️|0|man_biking
🚴‍♀️|0|woman_biking
🚵|0|person_mountain_biking
🚵‍♂️|0|man_mountain_biking
🚵‍♀️|0|woman_mountain_biking
🤸|0|person_cartwheeling
🤸‍♂️|0|man_cartwheeling
🤸‍♀️|0|woman_cartwheeling
🤼||people_wrestling
🤼‍♂️||men_wrestling
🤼‍♀️||women_wrestling
🤽|0|person_playing_water_polo
🤽‍♂️|0|man_playing_water_polo
🤽‍♀️|0|woman_playing_water_polo
🤾|0|person_playing_handball
🤾‍♂️|0|man_playing_handball
🤾‍♀️|0|woman_playing_handball
🤹|0|person_juggling
🤹‍♂️|0|man_juggling
🤹‍♀️|0|woman_juggling
🧘|0|person_in_lotus_position
🧘‍♂️|0|man_in_lotus_position
🧘‍♀️|0|woman_in_lotus_position
🛀|0|person_taking_bath
🛌|0|person_in_bed
🧑‍🤝‍🧑|02|people_holding_hands
👭|0|women_holding_hands
👫|0|woman_and_man_holding_hands
👬|0|men_holding_hands
💏|0|kiss
👩‍❤️‍💋‍👨|03|kiss_woman_man
👨‍❤️‍💋‍👨|03|kiss_man_man
👩‍❤️‍💋‍👩|03|kiss_woman_woman
💑|0|couple_with_heart
👩‍❤️‍👨|02|couple_with_heart_woman_man
👨‍❤️‍👨|02|couple_with_heart_man_man
👩‍❤️‍👩|02|couple_with_heart_woman_woman
👨‍👩‍👦||family_man_woman_boy
👨‍👩‍👧||family_man_woman_girl
👨‍👩‍👧‍👦||family_man_woman_girl_boy
👨‍👩‍👦‍👦||family_man_woman_boy_boy
👨‍👩‍👧‍👧||family_man_woman_girl_girl
👨‍👨‍👦||family_man_man_boy
👨‍👨‍👧||family_man_man_girl
👨‍👨‍👧‍👦||family_man_man_girl_boy
👨‍👨‍👦‍👦||family_man_man_boy_boy
👨‍👨‍👧‍👧||family_man_man_girl_girl
👩‍👩‍👦||family_woman_woman_boy
👩‍👩‍👧||family_woman_woman_girl
👩‍👩‍👧‍👦||family_woman_woman_girl_boy
👩‍👩‍👦‍👦||family_woman_woman_boy_boy
👩‍👩‍👧‍👧||family_woman_woman_girl_girl
👨‍👦||family_man_boy
👨‍👦‍👦||family_man_boy_boy
👨‍👧||family_man_girl
👨‍👧‍👦||family_man_girl_boy
👨‍👧‍👧||family_man_girl_girl
👩‍👦||family_woman_boy
👩‍👦‍👦||family_woman_boy_boy
👩‍👧||family_woman_girl
👩‍👧‍👦||family_woman_girl_boy
👩‍👧‍👧||family_woman_girl_girl
🗣️||speaking_head
👤||bust_in_silhouette
👥||busts_in_silhouette
🫂||people_hugging
👪||family
🧑‍🧑‍🧒||family_adult_adult_child
🧑‍🧑‍🧒‍🧒||family_adult_adult_child_child
🧑‍🧒||family_adult_child
🧑‍🧒‍🧒||family_adult_child_child
👣||footprints`,
  ],
  [
    "nature",
    `🐵||monkey face monkey_face
🐒||monkey
🦍||gorilla
🦧||orangutan
🐶||dog puppy pet dog_face
🐕||dog
🦮||guide_dog
🐕‍🦺||service_dog
🐩||poodle
🐺||wolf
🦊||fox
🦝||raccoon
🐱||cat kitten pet cat_face
🐈||cat
🐈‍⬛||black_cat
🦁||lion king
🐯||tiger tiger_face
🐅||tiger
🐆||leopard
🐴||horse_face
🫎||moose
🫏||donkey
🐎||horse
🦄||unicorn magic
🦓||zebra
🦌||deer
🦬||bison
🐮||cow moo cow_face
🐂||ox
🐃||water_buffalo
🐄||cow
🐷||pig oink pig_face
🐖||pig
🐗||boar
🐽||pig_nose
🐏||ram
🐑||ewe
🐐||goat
🐪||camel
🐫||two_hump_camel
🦙||llama
🦒||giraffe
🐘||elephant
🦣||mammoth
🦏||rhinoceros
🦛||hippopotamus
🐭||mouse rat mouse_face
🐁||mouse
🐀||rat
🐹||hamster
🐰||rabbit bunny rabbit_face
🐇||rabbit
🐿️||chipmunk
🦫||beaver
🦔||hedgehog
🦇||bat
🐻||bear
🐻‍❄️||polar_bear
🐨||koala
🐼||panda bear
🦥||sloth
🦦||otter
🦨||skunk
🦘||kangaroo
🦡||badger
🐾||paw_prints
🦃||turkey
🐔||chicken hen
🐓||rooster
🐣||hatching_chick
🐤||chick baby bird baby_chick
🐥||front_facing_baby_chick
🐦||bird
🐧||penguin
🕊️||dove
🦅||eagle
🦆||duck
🦢||swan
🦉||owl
🦤||dodo
🪶||feather
🦩||flamingo
🦚||peacock
🦜||parrot
🪽||wing
🐦‍⬛||black_bird
🪿||goose
🐦‍🔥||phoenix
🐸||frog toad
🐊||crocodile
🐢||turtle
🦎||lizard
🐍||snake
🐲||dragon_face
🐉||dragon
🦕||sauropod
🦖||t_rex
🐳||spouting_whale
🐋||whale
🐬||dolphin
🦭||seal
🐟||fish
🐠||tropical_fish
🐡||blowfish
🦈||shark
🐙||octopus
🐚||spiral_shell
🪸||coral
🪼||jellyfish
🐌||snail
🦋||butterfly
🐛||bug
🐜||ant
🐝||honeybee
🪲||beetle
🐞||lady_beetle
🦗||cricket
🪳||cockroach
🕷️||spider
🕸️||spider_web
🦂||scorpion
🦟||mosquito
🪰||fly
🪱||worm
🦠||microbe
💐||bouquet
🌸||cherry blossom flower pink cherry_blossom
💮||white flower white_flower
🪷||lotus
🏵️||rosette
🌹||rose flower red
🥀||wilted_flower
🌺||hibiscus flower
🌻||sunflower
🌼||blossom flower
🌷||tulip flower
🪻||hyacinth
🌱||seedling sprout plant
🪴||potted_plant
🌲||evergreen tree pine evergreen_tree
🌳||tree deciduous deciduous_tree
🌴||palm_tree
🌵||cactus
🌾||sheaf_of_rice
🌿||herb
☘️||shamrock
🍀||four leaf clover luck four_leaf_clover
🍁||maple_leaf
🍂||fallen_leaf
🍃||leaf_fluttering_in_wind
🪹||empty_nest
🪺||nest_with_eggs
🍄||mushroom`,
  ],
  [
    "food",
    `🍇||grapes fruit
🍈||melon
🍉||watermelon fruit
🍊||orange tangerine fruit
🍋||lemon fruit
🍋‍🟩||lime
🍌||banana fruit
🍍||pineapple fruit
🥭||mango
🍎||red apple fruit red_apple
🍏||green_apple
🍐||pear
🍑||peach fruit butt
🍒||cherries fruit
🍓||strawberry fruit
🫐||blueberries
🥝||kiwi fruit kiwi_fruit
🍅||tomato
🫒||olive
🥥||coconut
🥑||avocado
🍆||eggplant
🥔||potato
🥕||carrot
🌽||ear_of_corn
🌶️||hot_pepper
🫑||bell_pepper
🥒||cucumber
🥬||leafy_green
🥦||broccoli
🧄||garlic
🧅||onion
🥜||peanuts
🫘||beans
🌰||chestnut
🫚||ginger_root
🫛||pea_pod
🍄‍🟫||brown_mushroom
🍞||bread
🥐||croissant
🥖||baguette_bread
🫓||flatbread
🥨||pretzel
🥯||bagel
🥞||pancakes
🧇||waffle
🧀||cheese wedge cheese_wedge
🍖||meat_on_bone
🍗||poultry_leg
🥩||cut_of_meat
🥓||bacon
🍔||hamburger burger food
🍟||fries french food french_fries
🍕||pizza food slice
🌭||hot dog food hot_dog
🥪||sandwich
🌮||taco
🌯||burrito
🫔||tamale
🥙||stuffed_flatbread
🧆||falafel
🥚||egg
🍳||cooking fried egg
🥘||shallow_pan_of_food
🍲||pot_of_food
🫕||fondue
🥣||bowl_with_spoon
🥗||green_salad
🍿||popcorn snack movie
🧈||butter
🧂||salt
🥫||canned_food
🍱||bento_box
🍘||rice_cracker
🍙||rice_ball
🍚||cooked_rice
🍛||curry_rice
🍜||steaming_bowl
🍝||spaghetti
🍠||roasted_sweet_potato
🍢||oden
🍣||sushi
🍤||fried_shrimp
🍥||fish_cake_with_swirl
🥮||moon_cake
🍡||dango
🥟||dumpling
🥠||fortune_cookie
🥡||takeout_box
🦀||crab
🦞||lobster
🦐||shrimp
🦑||squid
🦪||oyster
🍦||soft_ice_cream
🍧||shaved_ice
🍨||ice_cream
🍩||doughnut
🍪||cookie
🎂||birthday_cake
🍰||shortcake
🧁||cupcake dessert sweet
🥧||pie
🍫||chocolate_bar
🍬||candy
🍭||lollipop
🍮||custard
🍯||honey_pot
🍼||baby_bottle
🥛||glass_of_milk
☕||coffee hot drink hot_beverage
🫖||teapot
🍵||tea hot drink teacup_without_handle
🍶||sake
🍾||bottle popping champagne celebrate bottle_with_popping_cork
🍷||wine glass drink red wine_glass
🍸||cocktail martini drink cocktail_glass
🍹||tropical drink tropical_drink
🍺||beer mug drink beer_mug
🍻||clinking beers cheers drink clinking_beer_mugs
🥂||champagne toast celebrate drink clinking_glasses
🥃||tumbler_glass
🫗||pouring_liquid
🥤||cup_with_straw
🧋||bubble_tea
🧃||beverage_box
🧉||mate
🧊||ice
🥢||chopsticks
🍽️||fork_and_knife_with_plate
🍴||fork_and_knife
🥄||spoon
🔪||kitchen_knife
🫙||jar
🏺||amphora`,
  ],
  [
    "travel",
    `🌍||globe_showing_europe_africa
🌎||globe_showing_americas
🌏||globe_showing_asia_australia
🌐||globe_with_meridians
🗺️||world_map
🗾||map_of_japan
🧭||compass
🏔️||snow_capped_mountain
⛰️||mountain
🌋||volcano
🗻||mount_fuji
🏕️||camping
🏖️||beach_with_umbrella
🏜️||desert
🏝️||desert_island
🏞️||national_park
🏟️||stadium
🏛️||classical_building
🏗️||building_construction
🧱||brick
🪨||rock
🪵||wood
🛖||hut
🏘️||houses
🏚️||derelict_house
🏠||house
🏡||house_with_garden
🏢||office_building
🏣||japanese_post_office
🏤||post_office
🏥||hospital
🏦||bank
🏨||hotel
🏩||love_hotel
🏪||convenience_store
🏫||school
🏬||department_store
🏭||factory
🏯||japanese_castle
🏰||castle
💒||wedding
🗼||tokyo_tower
🗽||statue_of_liberty
⛪||church
🕌||mosque
🛕||hindu_temple
🕍||synagogue
⛩️||shinto_shrine
🕋||kaaba
⛲||fountain
⛺||tent
🌁||foggy
🌃||night_with_stars
🏙️||cityscape
🌄||sunrise_over_mountains
🌅||sunrise
🌆||cityscape_at_dusk
🌇||sunset
🌉||bridge_at_night
♨️||hot_springs
🎠||carousel_horse
🛝||playground_slide
🎡||ferris_wheel
🎢||roller_coaster
💈||barber_pole
🎪||circus_tent
🚂||locomotive
🚃||railway_car
🚄||high_speed_train
🚅||bullet_train
🚆||train
🚇||metro
🚈||light_rail
🚉||station
🚊||tram
🚝||monorail
🚞||mountain_railway
🚋||tram_car
🚌||bus
🚍||oncoming_bus
🚎||trolleybus
🚐||minibus
🚑||ambulance
🚒||fire_engine
🚓||police_car
🚔||oncoming_police_car
🚕||taxi
🚖||oncoming_taxi
🚗||automobile
🚘||oncoming_automobile
🚙||sport_utility_vehicle
🛻||pickup_truck
🚚||delivery_truck
🚛||articulated_lorry
🚜||tractor
🏎️||racing_car
🏍️||motorcycle
🛵||motor_scooter
🦽||manual_wheelchair
🦼||motorized_wheelchair
🛺||auto_rickshaw
🚲||bicycle
🛴||kick_scooter
🛹||skateboard
🛼||roller_skate
🚏||bus_stop
🛣️||motorway
🛤️||railway_track
🛢️||oil_drum
⛽||fuel_pump
🛞||wheel
🚨||police_car_light
🚥||horizontal_traffic_light
🚦||vertical_traffic_light
🛑||stop_sign
🚧||construction
⚓||anchor
🛟||ring_buoy
⛵||sailboat
🛶||canoe
🚤||speedboat
🛳️||passenger_ship
⛴️||ferry
🛥️||motor_boat
🚢||ship
✈️||airplane
🛩️||small_airplane
🛫||airplane_departure
🛬||airplane_arrival
🪂||parachute
💺||seat
🚁||helicopter
🚟||suspension_railway
🚠||mountain_cableway
🚡||aerial_tramway
🛰️||satellite
🚀||rocket
🛸||flying_saucer
🛎️||bellhop_bell
🧳||luggage
⌛||hourglass_done
⏳||hourglass_not_done
⌚||watch
⏰||alarm_clock
⏱️||stopwatch
⏲️||timer_clock
🕰️||mantelpiece_clock
🕛||twelve_o_clock
🕧||twelve_thirty
🕐||one_o_clock
🕜||one_thirty
🕑||two_o_clock
🕝||two_thirty
🕒||three_o_clock
🕞||three_thirty
🕓||four_o_clock
🕟||four_thirty
🕔||five_o_clock
🕠||five_thirty
🕕||six_o_clock
🕡||six_thirty
🕖||seven_o_clock
🕢||seven_thirty
🕗||eight_o_clock
🕣||eight_thirty
🕘||nine_o_clock
🕤||nine_thirty
🕙||ten_o_clock
🕥||ten_thirty
🕚||eleven_o_clock
🕦||eleven_thirty
🌑||new_moon
🌒||waxing_crescent_moon
🌓||first_quarter_moon
🌔||waxing_gibbous_moon
🌕||full_moon
🌖||waning_gibbous_moon
🌗||last_quarter_moon
🌘||waning_crescent_moon
🌙||crescent_moon
🌚||new_moon_face
🌛||first_quarter_moon_face
🌜||last_quarter_moon_face
🌡️||thermometer
☀️||sun
🌝||full_moon_face
🌞||sun_with_face
🪐||ringed_planet
⭐||star yellow
🌟||glowing star sparkle glowing_star
🌠||shooting_star
🌌||milky_way
☁️||cloud
⛅||sun_behind_cloud
⛈️||cloud_with_lightning_and_rain
🌤️||sun_behind_small_cloud
🌥️||sun_behind_large_cloud
🌦️||sun_behind_rain_cloud
🌧️||cloud_with_rain
🌨️||cloud_with_snow
🌩️||cloud_with_lightning
🌪️||tornado
🌫️||fog
🌬️||wind_face
🌀||cyclone
🌈||rainbow
🌂||closed_umbrella
☂️||umbrella
☔||umbrella_with_rain_drops
⛱️||umbrella_on_ground
⚡||high_voltage
❄️||snowflake
☃️||snowman
⛄||snowman_without_snow
☄️||comet
🔥||fire hot flame lit
💧||droplet
🌊||water_wave`,
  ],
  [
    "activities",
    `🎃||jack_o_lantern
🎄||christmas_tree
🎆||fireworks
🎇||sparkler
🧨||firecracker
✨||sparkles magic shine
🎈||balloon
🎉||party_popper
🎊||confetti_ball
🎋||tanabata_tree
🎍||pine_decoration
🎎||japanese_dolls
🎏||carp_streamer
🎐||wind_chime
🎑||moon_viewing_ceremony
🧧||red_envelope
🎀||ribbon
🎁||wrapped_gift
🎗️||reminder_ribbon
🎟️||admission_tickets
🎫||ticket
🎖️||military_medal
🏆||trophy
🏅||sports_medal
🥇||1st_place_medal
🥈||2nd_place_medal
🥉||3rd_place_medal
⚽||soccer football ball sport soccer_ball
⚾||baseball ball sport
🥎||softball
🏀||basketball ball sport
🏐||volleyball
🏈||football american sport american_football
🏉||rugby_football
🎾||tennis ball sport
🥏||flying_disc
🎳||bowling
🏏||cricket_game
🏑||field_hockey
🏒||ice_hockey
🥍||lacrosse
🏓||ping_pong
🏸||badminton
🥊||boxing_glove
🥋||martial_arts_uniform
🥅||goal_net
⛳||flag_in_hole
⛸️||ice_skate
🎣||fishing_pole
🤿||diving_mask
🎽||running_shirt
🎿||skis
🛷||sled
🥌||curling_stone
🎯||bullseye target dart
🪀||yo_yo
🪁||kite
🔫||water_pistol
🎱||pool_8_ball
🔮||crystal_ball
🪄||magic_wand
🎮||video game controller gaming video_game
🕹️||joystick
🎰||slot_machine
🎲||dice game random game_die
🧩||puzzle_piece
🧸||teddy_bear
🪅||pinata
🪩||mirror_ball
🪆||nesting_dolls
♠️||spade_suit
♥️||heart_suit
♦️||diamond_suit
♣️||club_suit
♟️||chess_pawn
🃏||joker
🀄||mahjong_red_dragon
🎴||flower_playing_cards
🎭||performing_arts
🖼️||framed_picture
🎨||artist_palette
🧵||thread
🪡||sewing_needle
🧶||yarn
🪢||knot`,
  ],
  [
    "objects",
    `👓||glasses
🕶️||sunglasses
🥽||goggles
🥼||lab_coat
🦺||safety_vest
👔||necktie
👕||t_shirt
👖||jeans
🧣||scarf
🧤||gloves
🧥||coat
🧦||socks
👗||dress
👘||kimono
🥻||sari
🩱||one_piece_swimsuit
🩲||briefs
🩳||shorts
👙||bikini
👚||woman_s_clothes
🪭||folding_hand_fan
👛||purse
👜||handbag
👝||clutch_bag
🛍️||shopping_bags
🎒||backpack
🩴||thong_sandal
👞||man_s_shoe
👟||running_shoe
🥾||hiking_boot
🥿||flat_shoe
👠||high_heeled_shoe
👡||woman_s_sandal
🩰||ballet_shoes
👢||woman_s_boot
🪮||hair_pick
👑||crown
👒||woman_s_hat
🎩||top_hat
🎓||graduation_cap
🧢||billed_cap
🪖||military_helmet
⛑️||rescue_worker_s_helmet
📿||prayer_beads
💄||lipstick
💍||ring
💎||gem_stone
🔇||muted_speaker
🔈||speaker_low_volume
🔉||speaker_medium_volume
🔊||speaker_high_volume
📢||loudspeaker
📣||megaphone
📯||postal_horn
🔔||bell
🔕||bell_with_slash
🎼||musical_score
🎵||music note musical_note
🎶||music notes musical_notes
🎙️||studio_microphone
🎚️||level_slider
🎛️||control_knobs
🎤||microphone
🎧||headphone
📻||radio
🎷||saxophone
🪗||accordion
🎸||guitar
🎹||musical_keyboard
🎺||trumpet
🎻||violin
🪕||banjo
🥁||drum
🪘||long_drum
🪇||maracas
🪈||flute
📱||mobile_phone
📲||mobile_phone_with_arrow
☎️||telephone
📞||telephone_receiver
📟||pager
📠||fax_machine
🔋||battery
🪫||low_battery
🔌||electric_plug
💻||laptop
🖥️||desktop_computer
🖨️||printer
⌨️||keyboard
🖱️||computer_mouse
🖲️||trackball
💽||computer_disk
💾||floppy_disk
💿||optical_disk
📀||dvd
🧮||abacus
🎥||movie_camera
🎞️||film_frames
📽️||film_projector
🎬||clapper_board
📺||television
📷||camera
📸||camera_with_flash
📹||video_camera
📼||videocassette
🔍||magnifying_glass_tilted_left
🔎||magnifying_glass_tilted_right
🕯️||candle
💡||light bulb idea light_bulb
🔦||flashlight
🏮||red_paper_lantern
🪔||diya_lamp
📔||notebook_with_decorative_cover
📕||closed_book
📖||open_book
📗||green_book
📘||blue_book
📙||orange_book
📚||books
📓||notebook
📒||ledger
📃||page_with_curl
📜||scroll
📄||page_facing_up
📰||newspaper
🗞️||rolled_up_newspaper
📑||bookmark_tabs
🔖||bookmark
🏷️||label
💰||money_bag
🪙||coin
💴||yen_banknote
💵||dollar_banknote
💶||euro_banknote
💷||pound_banknote
💸||money_with_wings
💳||credit_card
🧾||receipt
💹||chart_increasing_with_yen
✉️||envelope
📧||e_mail
📨||incoming_envelope
📩||envelope_with_arrow
📤||outbox_tray
📥||inbox_tray
📦||package
📫||closed_mailbox_with_raised_flag
📪||closed_mailbox_with_lowered_flag
📬||open_mailbox_with_raised_flag
📭||open_mailbox_with_lowered_flag
📮||postbox
🗳️||ballot_box_with_ballot
✏️||pencil
✒️||black_nib
🖋️||fountain_pen
🖊️||pen
🖌️||paintbrush
🖍️||crayon
📝||memo
💼||briefcase
📁||file_folder
📂||open_file_folder
🗂️||card_index_dividers
📅||calendar
📆||tear_off_calendar
🗒️||spiral_notepad
🗓️||spiral_calendar
📇||card_index
📈||chart_increasing
📉||chart_decreasing
📊||bar_chart
📋||clipboard
📌||pushpin
📍||round_pushpin
📎||paperclip
🖇️||linked_paperclips
📏||straight_ruler
📐||triangular_ruler
✂️||scissors
🗃️||card_file_box
🗄️||file_cabinet
🗑️||wastebasket
🔒||locked
🔓||unlocked
🔏||locked_with_pen
🔐||locked_with_key
🔑||key
🗝️||old_key
🔨||hammer
🪓||axe
⛏️||pick
⚒️||hammer_and_pick
🛠️||hammer_and_wrench
🗡️||dagger
⚔️||crossed_swords
💣||bomb
🪃||boomerang
🏹||bow_and_arrow
🛡️||shield
🪚||carpentry_saw
🔧||wrench
🪛||screwdriver
🔩||nut_and_bolt
⚙️||gear
🗜️||clamp
⚖️||balance_scale
🦯||white_cane
🔗||link
⛓️‍💥||broken_chain
⛓️||chains
🪝||hook
🧰||toolbox
🧲||magnet
🪜||ladder
⚗️||alembic
🧪||test_tube
🧫||petri_dish
🧬||dna
🔬||microscope
🔭||telescope
📡||satellite_antenna
💉||syringe
🩸||drop_of_blood
💊||pill
🩹||adhesive_bandage
🩼||crutch
🩺||stethoscope
🩻||x_ray
🚪||door
🛗||elevator
🪞||mirror
🪟||window
🛏️||bed
🛋️||couch_and_lamp
🪑||chair
🚽||toilet
🪠||plunger
🚿||shower
🛁||bathtub
🪤||mouse_trap
🪒||razor
🧴||lotion_bottle
🧷||safety_pin
🧹||broom
🧺||basket
🧻||roll_of_paper
🪣||bucket
🧼||soap
🫧||bubbles
🪥||toothbrush
🧽||sponge
🧯||fire_extinguisher
🛒||shopping_cart
🚬||cigarette
⚰️||coffin
🪦||headstone
⚱️||funeral_urn
🧿||nazar_amulet
🪬||hamsa
🗿||moai
🪧||placard
🪪||identification_card`,
  ],
  [
    "symbols",
    `🏧||atm_sign
🚮||litter_in_bin_sign
🚰||potable_water
♿||wheelchair_symbol
🚹||men_s_room
🚺||women_s_room
🚻||restroom
🚼||baby_symbol
🚾||water_closet
🛂||passport_control
🛃||customs
🛄||baggage_claim
🛅||left_luggage
⚠️||warning caution alert
🚸||children_crossing
⛔||no_entry
🚫||prohibited forbidden no
🚳||no_bicycles
🚭||no_smoking
🚯||no_littering
🚱||non_potable_water
🚷||no_pedestrians
📵||no_mobile_phones
🔞||no_one_under_eighteen
☢️||radioactive
☣️||biohazard
⬆️||up_arrow
↗️||up_right_arrow
➡️||right_arrow
↘️||down_right_arrow
⬇️||down_arrow
↙️||down_left_arrow
⬅️||left_arrow
↖️||up_left_arrow
↕️||up_down_arrow
↔️||left_right_arrow
↩️||right_arrow_curving_left
↪️||left_arrow_curving_right
⤴️||right_arrow_curving_up
⤵️||right_arrow_curving_down
🔃||clockwise_vertical_arrows
🔄||counterclockwise_arrows_button
🔙||back_arrow
🔚||end_arrow
🔛||on_arrow
🔜||soon_arrow
🔝||top_arrow
🛐||place_of_worship
⚛️||atom_symbol
🕉️||om
✡️||star_of_david
☸️||wheel_of_dharma
☯️||yin_yang
✝️||latin_cross
☦️||orthodox_cross
☪️||star_and_crescent
☮️||peace_symbol
🕎||menorah
🔯||dotted_six_pointed_star
🪯||khanda
♈||aries
♉||taurus
♊||gemini
♋||cancer
♌||leo
♍||virgo
♎||libra
♏||scorpio
♐||sagittarius
♑||capricorn
♒||aquarius
♓||pisces
⛎||ophiuchus
🔀||shuffle_tracks_button
🔁||repeat_button
🔂||repeat_single_button
▶️||play_button
⏩||fast_forward_button
⏭️||next_track_button
⏯️||play_or_pause_button
◀️||reverse_button
⏪||fast_reverse_button
⏮️||last_track_button
🔼||upwards_button
⏫||fast_up_button
🔽||downwards_button
⏬||fast_down_button
⏸️||pause_button
⏹️||stop_button
⏺️||record_button
⏏️||eject_button
🎦||cinema
🔅||dim_button
🔆||bright_button
📶||antenna_bars
🛜||wireless
📳||vibration_mode
📴||mobile_phone_off
♀️||female_sign
♂️||male_sign
⚧️||transgender_symbol
✖️||multiply
➕||plus
➖||minus
➗||divide
🟰||heavy_equals_sign
♾️||infinity
‼️||double exclamation double_exclamation_mark
⁉️||exclamation question exclamation_question_mark
❓||question mark red red_question_mark
❔||white_question_mark
❕||white_exclamation_mark
❗||exclamation mark red alert red_exclamation_mark
〰️||wavy_dash
💱||currency_exchange
💲||heavy_dollar_sign
⚕️||medical_symbol
♻️||recycle green environment recycling_symbol
⚜️||fleur_de_lis
🔱||trident_emblem
📛||name_badge
🔰||beginner new japanese japanese_symbol_for_beginner
⭕||hollow_red_circle
✅||check mark yes done complete check_mark_button
☑️||check_box_with_check
✔️||check_mark
❌||cross mark no wrong cancel cross_mark
❎||cross_mark_button
➰||curly_loop
➿||double_curly_loop
〽️||part_alternation_mark
✳️||eight_spoked_asterisk
✴️||eight_pointed_star
❇️||sparkle
©️||copyright
®️||registered
™️||trade_mark
#️⃣||keycap_number_sign
*️⃣||keycap_asterisk
0️⃣||keycap_0
1️⃣||keycap_1
2️⃣||keycap_2
3️⃣||keycap_3
4️⃣||keycap_4
5️⃣||keycap_5
6️⃣||keycap_6
7️⃣||keycap_7
8️⃣||keycap_8
9️⃣||keycap_9
🔟||keycap_10
🔠||input_latin_uppercase
🔡||input_latin_lowercase
🔢||input_numbers
🔣||input_symbols
🔤||input_latin_letters
🅰️||a_button_blood_type
🆎||ab_button_blood_type
🅱️||b_button_blood_type
🆑||cl_button
🆒||cool_button
🆓||free_button
ℹ️||information
🆔||id_button
Ⓜ️||circled_m
🆕||new_button
🆖||ng_button
🅾️||o_button_blood_type
🆗||ok_button
🅿️||p_button
🆘||sos_button
🆙||up_button
🆚||vs_button
🈁||japanese_here_button
🈂️||japanese_service_charge_button
🈷️||japanese_monthly_amount_button
🈶||japanese_not_free_of_charge_button
🈯||japanese_reserved_button
🉐||japanese_bargain_button
🈹||japanese_discount_button
🈚||japanese_free_of_charge_button
🈲||japanese_prohibited_button
🉑||japanese_acceptable_button
🈸||japanese_application_button
🈴||japanese_passing_grade_button
🈳||japanese_vacancy_button
㊗️||japanese_congratulations_button
㊙️||japanese_secret_button
🈺||japanese_open_for_business_button
🈵||japanese_no_vacancy_button
🔴||red circle red_circle
🟠||orange circle orange_circle
🟡||yellow circle yellow_circle
🟢||green circle green_circle
🔵||blue circle blue_circle
🟣||purple circle purple_circle
🟤||brown_circle
⚫||black circle black_circle
⚪||white circle white_circle
🟥||red_square
🟧||orange_square
🟨||yellow_square
🟩||green_square
🟦||blue_square
🟪||purple_square
🟫||brown_square
⬛||black_large_square
⬜||white_large_square
◼️||black_medium_square
◻️||white_medium_square
◾||black_medium_small_square
◽||white_medium_small_square
▪️||black_small_square
▫️||white_small_square
🔶||large_orange_diamond
🔷||large_blue_diamond
🔸||small_orange_diamond
🔹||small_blue_diamond
🔺||red_triangle_pointed_up
🔻||red_triangle_pointed_down
💠||diamond_with_a_dot
🔘||radio_button
🔳||white_square_button
🔲||black_square_button`,
  ],
  [
    "flags",
    `🏁||chequered_flag
🚩||triangular_flag
🎌||crossed_flags
🏴||black_flag
🏳️||white_flag
🏳️‍🌈||rainbow_flag
🏳️‍⚧️||transgender_flag
🏴‍☠️||pirate_flag
🇦🇨||flag_ascension_island
🇦🇩||flag_andorra
🇦🇪||flag_united_arab_emirates
🇦🇫||flag_afghanistan
🇦🇬||flag_antigua_barbuda
🇦🇮||flag_anguilla
🇦🇱||flag_albania
🇦🇲||flag_armenia
🇦🇴||flag_angola
🇦🇶||flag_antarctica
🇦🇷||flag_argentina
🇦🇸||flag_american_samoa
🇦🇹||flag_austria
🇦🇺||flag_australia
🇦🇼||flag_aruba
🇦🇽||flag_aland_islands
🇦🇿||flag_azerbaijan
🇧🇦||flag_bosnia_herzegovina
🇧🇧||flag_barbados
🇧🇩||flag_bangladesh
🇧🇪||flag_belgium
🇧🇫||flag_burkina_faso
🇧🇬||flag_bulgaria
🇧🇭||flag_bahrain
🇧🇮||flag_burundi
🇧🇯||flag_benin
🇧🇱||flag_st_barthelemy
🇧🇲||flag_bermuda
🇧🇳||flag_brunei
🇧🇴||flag_bolivia
🇧🇶||flag_caribbean_netherlands
🇧🇷||flag_brazil
🇧🇸||flag_bahamas
🇧🇹||flag_bhutan
🇧🇻||flag_bouvet_island
🇧🇼||flag_botswana
🇧🇾||flag_belarus
🇧🇿||flag_belize
🇨🇦||flag_canada
🇨🇨||flag_cocos_keeling_islands
🇨🇩||flag_congo_kinshasa
🇨🇫||flag_central_african_republic
🇨🇬||flag_congo_brazzaville
🇨🇭||flag_switzerland
🇨🇮||flag_cote_d_ivoire
🇨🇰||flag_cook_islands
🇨🇱||flag_chile
🇨🇲||flag_cameroon
🇨🇳||flag_china
🇨🇴||flag_colombia
🇨🇵||flag_clipperton_island
🇨🇷||flag_costa_rica
🇨🇺||flag_cuba
🇨🇻||flag_cape_verde
🇨🇼||flag_curacao
🇨🇽||flag_christmas_island
🇨🇾||flag_cyprus
🇨🇿||flag_czechia
🇩🇪||flag_germany
🇩🇬||flag_diego_garcia
🇩🇯||flag_djibouti
🇩🇰||flag_denmark
🇩🇲||flag_dominica
🇩🇴||flag_dominican_republic
🇩🇿||flag_algeria
🇪🇦||flag_ceuta_melilla
🇪🇨||flag_ecuador
🇪🇪||flag_estonia
🇪🇬||flag_egypt
🇪🇭||flag_western_sahara
🇪🇷||flag_eritrea
🇪🇸||flag_spain
🇪🇹||flag_ethiopia
🇪🇺||flag_european_union
🇫🇮||flag_finland
🇫🇯||flag_fiji
🇫🇰||flag_falkland_islands
🇫🇲||flag_micronesia
🇫🇴||flag_faroe_islands
🇫🇷||flag_france
🇬🇦||flag_gabon
🇬🇧||flag_united_kingdom
🇬🇩||flag_grenada
🇬🇪||flag_georgia
🇬🇫||flag_french_guiana
🇬🇬||flag_guernsey
🇬🇭||flag_ghana
🇬🇮||flag_gibraltar
🇬🇱||flag_greenland
🇬🇲||flag_gambia
🇬🇳||flag_guinea
🇬🇵||flag_guadeloupe
🇬🇶||flag_equatorial_guinea
🇬🇷||flag_greece
🇬🇸||flag_south_georgia_south_sandwich_islands
🇬🇹||flag_guatemala
🇬🇺||flag_guam
🇬🇼||flag_guinea_bissau
🇬🇾||flag_guyana
🇭🇰||flag_hong_kong_sar_china
🇭🇲||flag_heard_mcdonald_islands
🇭🇳||flag_honduras
🇭🇷||flag_croatia
🇭🇹||flag_haiti
🇭🇺||flag_hungary
🇮🇨||flag_canary_islands
🇮🇩||flag_indonesia
🇮🇪||flag_ireland
🇮🇱||flag_israel
🇮🇲||flag_isle_of_man
🇮🇳||flag_india
🇮🇴||flag_british_indian_ocean_territory
🇮🇶||flag_iraq
🇮🇷||flag_iran
🇮🇸||flag_iceland
🇮🇹||flag_italy
🇯🇪||flag_jersey
🇯🇲||flag_jamaica
🇯🇴||flag_jordan
🇯🇵||flag_japan
🇰🇪||flag_kenya
🇰🇬||flag_kyrgyzstan
🇰🇭||flag_cambodia
🇰🇮||flag_kiribati
🇰🇲||flag_comoros
🇰🇳||flag_st_kitts_nevis
🇰🇵||flag_north_korea
🇰🇷||flag_south_korea
🇰🇼||flag_kuwait
🇰🇾||flag_cayman_islands
🇰🇿||flag_kazakhstan
🇱🇦||flag_laos
🇱🇧||flag_lebanon
🇱🇨||flag_st_lucia
🇱🇮||flag_liechtenstein
🇱🇰||flag_sri_lanka
🇱🇷||flag_liberia
🇱🇸||flag_lesotho
🇱🇹||flag_lithuania
🇱🇺||flag_luxembourg
🇱🇻||flag_latvia
🇱🇾||flag_libya
🇲🇦||flag_morocco
🇲🇨||flag_monaco
🇲🇩||flag_moldova
🇲🇪||flag_montenegro
🇲🇫||flag_st_martin
🇲🇬||flag_madagascar
🇲🇭||flag_marshall_islands
🇲🇰||flag_north_macedonia
🇲🇱||flag_mali
🇲🇲||flag_myanmar_burma
🇲🇳||flag_mongolia
🇲🇴||flag_macao_sar_china
🇲🇵||flag_northern_mariana_islands
🇲🇶||flag_martinique
🇲🇷||flag_mauritania
🇲🇸||flag_montserrat
🇲🇹||flag_malta
🇲🇺||flag_mauritius
🇲🇻||flag_maldives
🇲🇼||flag_malawi
🇲🇽||flag_mexico
🇲🇾||flag_malaysia
🇲🇿||flag_mozambique
🇳🇦||flag_namibia
🇳🇨||flag_new_caledonia
🇳🇪||flag_niger
🇳🇫||flag_norfolk_island
🇳🇬||flag_nigeria
🇳🇮||flag_nicaragua
🇳🇱||flag_netherlands
🇳🇴||flag_norway
🇳🇵||flag_nepal
🇳🇷||flag_nauru
🇳🇺||flag_niue
🇳🇿||flag_new_zealand
🇴🇲||flag_oman
🇵🇦||flag_panama
🇵🇪||flag_peru
🇵🇫||flag_french_polynesia
🇵🇬||flag_papua_new_guinea
🇵🇭||flag_philippines
🇵🇰||flag_pakistan
🇵🇱||flag_poland
🇵🇲||flag_st_pierre_miquelon
🇵🇳||flag_pitcairn_islands
🇵🇷||flag_puerto_rico
🇵🇸||flag_palestinian_territories
🇵🇹||flag_portugal
🇵🇼||flag_palau
🇵🇾||flag_paraguay
🇶🇦||flag_qatar
🇷🇪||flag_reunion
🇷🇴||flag_romania
🇷🇸||flag_serbia
🇷🇺||flag_russia
🇷🇼||flag_rwanda
🇸🇦||flag_saudi_arabia
🇸🇧||flag_solomon_islands
🇸🇨||flag_seychelles
🇸🇩||flag_sudan
🇸🇪||flag_sweden
🇸🇬||flag_singapore
🇸🇭||flag_st_helena
🇸🇮||flag_slovenia
🇸🇯||flag_svalbard_jan_mayen
🇸🇰||flag_slovakia
🇸🇱||flag_sierra_leone
🇸🇲||flag_san_marino
🇸🇳||flag_senegal
🇸🇴||flag_somalia
🇸🇷||flag_suriname
🇸🇸||flag_south_sudan
🇸🇹||flag_sao_tome_principe
🇸🇻||flag_el_salvador
🇸🇽||flag_sint_maarten
🇸🇾||flag_syria
🇸🇿||flag_eswatini
🇹🇦||flag_tristan_da_cunha
🇹🇨||flag_turks_caicos_islands
🇹🇩||flag_chad
🇹🇫||flag_french_southern_territories
🇹🇬||flag_togo
🇹🇭||flag_thailand
🇹🇯||flag_tajikistan
🇹🇰||flag_tokelau
🇹🇱||flag_timor_leste
🇹🇲||flag_turkmenistan
🇹🇳||flag_tunisia
🇹🇴||flag_tonga
🇹🇷||flag_turkiye
🇹🇹||flag_trinidad_tobago
🇹🇻||flag_tuvalu
🇹🇼||flag_taiwan
🇹🇿||flag_tanzania
🇺🇦||flag_ukraine
🇺🇬||flag_uganda
🇺🇲||flag_u_s_outlying_islands
🇺🇳||flag_united_nations
🇺🇸||flag_united_states
🇺🇾||flag_uruguay
🇺🇿||flag_uzbekistan
🇻🇦||flag_vatican_city
🇻🇨||flag_st_vincent_grenadines
🇻🇪||flag_venezuela
🇻🇬||flag_british_virgin_islands
🇻🇮||flag_u_s_virgin_islands
🇻🇳||flag_vietnam
🇻🇺||flag_vanuatu
🇼🇫||flag_wallis_futuna
🇼🇸||flag_samoa
🇽🇰||flag_kosovo
🇾🇪||flag_yemen
🇾🇹||flag_mayotte
🇿🇦||flag_south_africa
🇿🇲||flag_zambia
🇿🇼||flag_zimbabwe
🏴󠁧󠁢󠁥󠁮󠁧󠁿||flag_england
🏴󠁧󠁢󠁳󠁣󠁴󠁿||flag_scotland
🏴󠁧󠁢󠁷󠁬󠁳󠁿||flag_wales`,
  ],
];
