// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appeals.sql

package dbgen

import (
	"context"
)

const appealObservedRowExists = `-- name: AppealObservedRowExists :one
SELECT EXISTS (
  SELECT 1 FROM appeals
   WHERE id = ?1 AND state IN ('open', 'assigned')
     AND state = ?2 AND assignee_id = ?3
)
`

type AppealObservedRowExistsParams struct {
	ID                 int64  `json:"id"`
	ObservedState      string `json:"observedState"`
	ObservedAssigneeID int64  `json:"observedAssigneeId"`
}

// P3 review: reject a stale/terminal appeal BEFORE running the (possibly
// expensive) self-review eligibility test below -- the exact row+state+
// assignee the caller observed, mirroring DecideAppeal's own guard so a
// decide that is going to fail its guarded UPDATE anyway never pays for the
// eligibility check first.
func (q *Queries) AppealObservedRowExists(ctx context.Context, arg AppealObservedRowExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, appealObservedRowExists, arg.ID, arg.ObservedState, arg.ObservedAssigneeID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const assignAppeal = `-- name: AssignAppeal :execrows
UPDATE appeals
   SET assignee_id = ?1, state = 'assigned'
 WHERE appeals.id = ?2
   AND appeals.state IN ('open', 'assigned')
   AND appeals.assignee_id = ?3
   AND EXISTS (SELECT 1 FROM users u WHERE u.id = ?1)
`

type AssignAppealParams struct {
	AssigneeID         int64 `json:"assigneeId"`
	ID                 int64 `json:"id"`
	ObservedAssigneeID int64 `json:"observedAssigneeId"`
}

// Guarded three ways, the same shape as reports' AssignReport: state (only
// 'open' may be assigned -- nothing leaves a decided or withdrawn state),
// the OBSERVED assignee (optimistic concurrency), and EXISTS(users) (a
// moderator erased between requirePerm and this write cannot land as the
// new assignee).
func (q *Queries) AssignAppeal(ctx context.Context, arg AssignAppealParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, assignAppeal, arg.AssigneeID, arg.ID, arg.ObservedAssigneeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countUsersWithPermission = `-- name: CountUsersWithPermission :one
SELECT COUNT(*) FROM users u
  JOIN roles r ON r.id = u.role_id
 WHERE u.id != 0
   AND u.id != ?1
   AND u.id != ?2
   AND (u.banned = 0 OR (u.ban_expires IS NOT NULL AND replace(u.ban_expires, ' ', 'T') <= strftime('%Y-%m-%dT%H:%M:%SZ', 'now')))
   AND ((r.permissions & ?3) != 0 OR (r.permissions & ?4) != 0)
`

type CountUsersWithPermissionParams struct {
	ExcludeActorID     int64 `json:"excludeActorId"`
	ExcludeAppellantID int64 `json:"excludeAppellantId"`
	PermBit            int64 `json:"permBit"`
	AdminBit           int64 `json:"adminBit"`
}

// The eligible-moderator COUNT for decision 8's self-review escape (the
// exported db.CountEligibleModerators contract -- Assign's non-transactional
// checkSelfReview and its own direct tests want the actual count, not just
// ">0"): every OTHER user, excluding the acting moderator, the appellant
// (F2/F3 review: an appellant who happens to also hold the bit must never
// count as their own alternative reviewer), id 0 (the system actor is never
// a reviewer), and anyone effectively banned, who holds perm_bit or the
// Administrator bit. The ban comparison is normalised the same way
// mention_queries.go's notBannedClause is (P2 review, uniformity): BanUser
// writes ISO-8601 'Z' ("2006-01-02T15:04:05Z"), and a raw lexical
// "ban_expires <= datetime('now')" compares that against SQLite's space-form
// "2006-01-02 15:04:05" -- a bare ' ' sorts BELOW 'T', so a same-day expiry
// would compare as still-active until midnight and wrongly exclude an
// eligible moderator (the exact bug notBannedClause's own comment
// documents). replace() normalises the separator before comparing.
func (q *Queries) CountUsersWithPermission(ctx context.Context, arg CountUsersWithPermissionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersWithPermission,
		arg.ExcludeActorID,
		arg.ExcludeAppellantID,
		arg.PermBit,
		arg.AdminBit,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const decideAppeal = `-- name: DecideAppeal :execrows
UPDATE appeals
   SET state = ?1, decided_by = ?2,
       decision_note = ?3, decided_at = datetime('now')
 WHERE appeals.id = ?4
   AND appeals.state IN ('open', 'assigned')
   AND appeals.state = ?5
   AND appeals.assignee_id = ?6
   AND EXISTS (SELECT 1 FROM users u WHERE u.id = ?2)
`

type DecideAppealParams struct {
	NewState           string `json:"newState"`
	DecidedBy          int64  `json:"decidedBy"`
	DecisionNote       string `json:"decisionNote"`
	ID                 int64  `json:"id"`
	ObservedState      string `json:"observedState"`
	ObservedAssigneeID int64  `json:"observedAssigneeId"`
}

// new_state is 'upheld' or 'overturned', validated in Go. Guarded on the
// OBSERVED state and assignee (optimistic concurrency, Claim 5 review: a
// bare "state IN ('open','assigned')" let an Assign and a Decide the caller
// read as sequential actually land out of order -- Assign after the caller
// read 'open' but before this write, or vice versa, both invisible to a
// guard that does not pin the exact row the caller observed), and
// EXISTS(users) for the deciding moderator (erased mid-flight cannot land).
func (q *Queries) DecideAppeal(ctx context.Context, arg DecideAppealParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, decideAppeal,
		arg.NewState,
		arg.DecidedBy,
		arg.DecisionNote,
		arg.ID,
		arg.ObservedState,
		arg.ObservedAssigneeID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const eligibleModeratorExists = `-- name: EligibleModeratorExists :one
SELECT EXISTS (
  SELECT 1 FROM users u
    JOIN roles r ON r.id = u.role_id
   WHERE u.id != 0
     AND u.id != ?1
     AND u.id != ?2
     AND (u.banned = 0 OR (u.ban_expires IS NOT NULL AND replace(u.ban_expires, ' ', 'T') <= strftime('%Y-%m-%dT%H:%M:%SZ', 'now')))
     AND ((r.permissions & ?3) != 0 OR (r.permissions & ?4) != 0)
)
`

type EligibleModeratorExistsParams struct {
	ExcludeActorID     int64 `json:"excludeActorId"`
	ExcludeAppellantID int64 `json:"excludeAppellantId"`
	PermBit            int64 `json:"permBit"`
	AdminBit           int64 `json:"adminBit"`
}

// DecideAppealTx's own self-review escape test (P3 review): the identical
// WHERE clause as CountUsersWithPermission above, but SELECT EXISTS rather
// than SELECT COUNT(*) -- DecideAppealTx only ever tests ">0", so scanning
// until the first match is strictly less work than counting every match,
// and it now runs only after AppealObservedRowExists has already confirmed
// the appeal is not stale/terminal, inside the same transaction.
func (q *Queries) EligibleModeratorExists(ctx context.Context, arg EligibleModeratorExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, eligibleModeratorExists,
		arg.ExcludeActorID,
		arg.ExcludeAppellantID,
		arg.PermBit,
		arg.AdminBit,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const findAppealForAction = `-- name: FindAppealForAction :one

SELECT id FROM appeals WHERE action_id = ? LIMIT 1
`

// appeals is the B5-10 rate-limited appeal against a moderation action
// (migration 050). Keep this file ASCII-only: sqlc v1.30 truncates the next
// query by the byte/rune difference of any multi-byte character.
// The dedupe FAST PATH (mirrors reports' FindOpenOrAssignedReport): decision
// 8 forbids re-appealing a decided appeal, and this table's UNIQUE(action_id)
// forbids ANY second appeal against the same action, ever. This query alone
// is a pre-check only and is not race-proof; the UNIQUE constraint on
// InsertAppeal is what actually enforces it under concurrency.
func (q *Queries) FindAppealForAction(ctx context.Context, actionID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, findAppealForAction, actionID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAppealByID = `-- name: GetAppealByID :one
SELECT id, public_id, action_id, appellant_id, body, state, assignee_id,
       decided_by, decided_by_token, decision_note, created_at, decided_at
  FROM appeals WHERE id = ?
`

func (q *Queries) GetAppealByID(ctx context.Context, id int64) (Appeal, error) {
	row := q.db.QueryRowContext(ctx, getAppealByID, id)
	var i Appeal
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ActionID,
		&i.AppellantID,
		&i.Body,
		&i.State,
		&i.AssigneeID,
		&i.DecidedBy,
		&i.DecidedByToken,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getAppealByPublicID = `-- name: GetAppealByPublicID :one
SELECT id, public_id, action_id, appellant_id, body, state, assignee_id,
       decided_by, decided_by_token, decision_note, created_at, decided_at
  FROM appeals WHERE public_id = ?
`

// The only lookup a route parameter or a mod_queue frame's appeal_id ever
// drives: public_id is the sole externally-visible identifier.
func (q *Queries) GetAppealByPublicID(ctx context.Context, publicID string) (Appeal, error) {
	row := q.db.QueryRowContext(ctx, getAppealByPublicID, publicID)
	var i Appeal
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.ActionID,
		&i.AppellantID,
		&i.Body,
		&i.State,
		&i.AssigneeID,
		&i.DecidedBy,
		&i.DecidedByToken,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const insertAppeal = `-- name: InsertAppeal :one
INSERT INTO appeals (public_id, action_id, appellant_id, body)
SELECT ?1, ?2, ?3, ?4
 WHERE EXISTS (SELECT 1 FROM moderation_actions WHERE id = ?2)
RETURNING id
`

type InsertAppealParams struct {
	PublicID    string `json:"publicId"`
	ActionID    int64  `json:"actionId"`
	AppellantID int64  `json:"appellantId"`
	Body        string `json:"body"`
}

// public_id is generated in Go (crypto/rand) before this runs, the same
// shape reports.public_id uses. A violation of UNIQUE(action_id) here is the
// race-proof half of decision 8: two simultaneous appeals against the same
// action both reach this INSERT, and the loser's violates the constraint.
// N4 review: INSERT ... SELECT ... WHERE EXISTS, the same shape reports'
// InsertReport uses, so an action erased between Submit's ownership lookup
// and this write (the target's account erasure cascades and removes the
// action row) surfaces as zero rows (mapped to db.ErrNotFound) rather than
// a raw foreign-key constraint error reaching the caller as a 500.
func (q *Queries) InsertAppeal(ctx context.Context, arg InsertAppealParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertAppeal,
		arg.PublicID,
		arg.ActionID,
		arg.AppellantID,
		arg.Body,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const liftTimeoutByActionID = `-- name: LiftTimeoutByActionID :execrows
UPDATE moderation_actions
   SET lifted_at = datetime('now'), lifted_by = 0
 WHERE id = ?1 AND kind = 'timeout' AND lifted_at IS NULL AND expires_at > datetime('now')
`

// F1/N1 review: overturning an appeal reverses the SPECIFIC appealed action,
// never "whatever timeout is active for this target now" -- two timeouts,
// appeal the older, overturn must not touch a newer one. Guarded on id AND
// still-active (lifted_at IS NULL AND expires_at > now): if this row was
// already lifted (expired naturally, lifted directly, or superseded by a
// later TimeoutUser call, N1) overturning it is a record only, zero rows
// affected, not an error. Runs under the system actor (0, no EXISTS(users)
// guard): the reversal is a mechanical consequence of the appeal DECISION,
// audited on the appeal row with the human decider's id -- it is not a
// second moderation action by that human, so 0 is a blessed sentinel here
// rather than a live user id needing re-validation.
func (q *Queries) LiftTimeoutByActionID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, liftTimeoutByActionID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAppealsByState = `-- name: ListAppealsByState :many
SELECT id, public_id, action_id, appellant_id, body, state, assignee_id,
       decided_by, decision_note, created_at, decided_at
  FROM appeals
 WHERE state = ?
 ORDER BY created_at DESC, id DESC
`

type ListAppealsByStateRow struct {
	ID           int64   `json:"id"`
	PublicID     string  `json:"publicId"`
	ActionID     int64   `json:"actionId"`
	AppellantID  int64   `json:"appellantId"`
	Body         string  `json:"body"`
	State        string  `json:"state"`
	AssigneeID   int64   `json:"assigneeId"`
	DecidedBy    int64   `json:"decidedBy"`
	DecisionNote string  `json:"decisionNote"`
	CreatedAt    string  `json:"createdAt"`
	DecidedAt    *string `json:"decidedAt"`
}

// The moderation queue view for one state ("open", "assigned", "decided" --
// decided groups both terminal decision states together, mirroring reports'
// "closed" grouping resolved/dismissed).
func (q *Queries) ListAppealsByState(ctx context.Context, state string) ([]ListAppealsByStateRow, error) {
	rows, err := q.db.QueryContext(ctx, listAppealsByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppealsByStateRow{}
	for rows.Next() {
		var i ListAppealsByStateRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.ActionID,
			&i.AppellantID,
			&i.Body,
			&i.State,
			&i.AssigneeID,
			&i.DecidedBy,
			&i.DecisionNote,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppealsDecided = `-- name: ListAppealsDecided :many
SELECT id, public_id, action_id, appellant_id, body, state, assignee_id,
       decided_by, decision_note, created_at, decided_at
  FROM appeals
 WHERE state IN ('upheld', 'overturned')
 ORDER BY created_at DESC, id DESC
`

type ListAppealsDecidedRow struct {
	ID           int64   `json:"id"`
	PublicID     string  `json:"publicId"`
	ActionID     int64   `json:"actionId"`
	AppellantID  int64   `json:"appellantId"`
	Body         string  `json:"body"`
	State        string  `json:"state"`
	AssigneeID   int64   `json:"assigneeId"`
	DecidedBy    int64   `json:"decidedBy"`
	DecisionNote string  `json:"decisionNote"`
	CreatedAt    string  `json:"createdAt"`
	DecidedAt    *string `json:"decidedAt"`
}

func (q *Queries) ListAppealsDecided(ctx context.Context) ([]ListAppealsDecidedRow, error) {
	rows, err := q.db.QueryContext(ctx, listAppealsDecided)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppealsDecidedRow{}
	for rows.Next() {
		var i ListAppealsDecidedRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.ActionID,
			&i.AppellantID,
			&i.Body,
			&i.State,
			&i.AssigneeID,
			&i.DecidedBy,
			&i.DecisionNote,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppealsMine = `-- name: ListAppealsMine :many
SELECT id, public_id, action_id, body, state, decision_note, created_at, decided_at
  FROM appeals
 WHERE appellant_id = ?
 ORDER BY created_at DESC, id DESC
`

type ListAppealsMineRow struct {
	ID           int64   `json:"id"`
	PublicID     string  `json:"publicId"`
	ActionID     int64   `json:"actionId"`
	Body         string  `json:"body"`
	State        string  `json:"state"`
	DecisionNote string  `json:"decisionNote"`
	CreatedAt    string  `json:"createdAt"`
	DecidedAt    *string `json:"decidedAt"`
}

// The appellant's own view: their appeals, newest first.
func (q *Queries) ListAppealsMine(ctx context.Context, appellantID int64) ([]ListAppealsMineRow, error) {
	rows, err := q.db.QueryContext(ctx, listAppealsMine, appellantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppealsMineRow{}
	for rows.Next() {
		var i ListAppealsMineRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.ActionID,
			&i.Body,
			&i.State,
			&i.DecisionNote,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppealsOpenOrAssigned = `-- name: ListAppealsOpenOrAssigned :many
SELECT id, public_id, action_id, appellant_id, body, state, assignee_id,
       decided_by, decision_note, created_at, decided_at
  FROM appeals
 WHERE state IN ('open', 'assigned')
 ORDER BY created_at DESC, id DESC
`

type ListAppealsOpenOrAssignedRow struct {
	ID           int64   `json:"id"`
	PublicID     string  `json:"publicId"`
	ActionID     int64   `json:"actionId"`
	AppellantID  int64   `json:"appellantId"`
	Body         string  `json:"body"`
	State        string  `json:"state"`
	AssigneeID   int64   `json:"assigneeId"`
	DecidedBy    int64   `json:"decidedBy"`
	DecisionNote string  `json:"decisionNote"`
	CreatedAt    string  `json:"createdAt"`
	DecidedAt    *string `json:"decidedAt"`
}

// The default queue view (state omitted): open and assigned together,
// mirroring reports' ListReportsOpenOrAssigned.
func (q *Queries) ListAppealsOpenOrAssigned(ctx context.Context) ([]ListAppealsOpenOrAssignedRow, error) {
	rows, err := q.db.QueryContext(ctx, listAppealsOpenOrAssigned)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppealsOpenOrAssignedRow{}
	for rows.Next() {
		var i ListAppealsOpenOrAssignedRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.ActionID,
			&i.AppellantID,
			&i.Body,
			&i.State,
			&i.AssigneeID,
			&i.DecidedBy,
			&i.DecisionNote,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireRetiredCandidatesExcludingAppealed = `-- name: RetireRetiredCandidatesExcludingAppealed :execrows
DELETE FROM moderation_actions
 WHERE ((kind = 'warning' AND acknowledged_at IS NOT NULL AND acknowledged_at < ?1)
    OR (kind = 'timeout' AND COALESCE(lifted_at, expires_at) < ?1))
   AND id NOT IN (SELECT action_id FROM appeals)
`

// B5-10's completion of the // B5-10: comment RetireModerationActions left
// in Server/db/moderation_action_queries.go: the same warning/timeout
// retention sweep as RetireRetiredCandidates (moderation_actions.sql), but
// excluding any id an appeals row references -- decision 8's UNIQUE(action_id)
// memory must not be swept out from under a decided appeal, or a fresh
// appeal against the same action could slip past the "one appeal per action,
// ever" rule the row alone enforces.
func (q *Queries) RetireRetiredCandidatesExcludingAppealed(ctx context.Context, cutoff *string) (int64, error) {
	result, err := q.db.ExecContext(ctx, retireRetiredCandidatesExcludingAppealed, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const unlinkAppealsByAssignee = `-- name: UnlinkAppealsByAssignee :exec
UPDATE appeals SET assignee_id = 0 WHERE assignee_id = ?
`

// Same, for assignee_id: no token column of its own (mirrors reports'
// assignee_id and moderation_actions.lifted_by), so an erased assignee's id
// simply goes to 0.
func (q *Queries) UnlinkAppealsByAssignee(ctx context.Context, assigneeID int64) error {
	_, err := q.db.ExecContext(ctx, unlinkAppealsByAssignee, assigneeID)
	return err
}

const unlinkAppealsByDecider = `-- name: UnlinkAppealsByDecider :exec
UPDATE appeals SET decided_by = 0, decided_by_token = ? WHERE decided_by = ?
`

type UnlinkAppealsByDeciderParams struct {
	DecidedByToken *string `json:"decidedByToken"`
	DecidedBy      int64   `json:"decidedBy"`
}

// Erasure's actor-token unlink (mirrors UnlinkModerationActionsByActor): an
// erased moderator's decisions keep their row, decision and order, but the
// deciding id goes to 0 and the token takes its place.
func (q *Queries) UnlinkAppealsByDecider(ctx context.Context, arg UnlinkAppealsByDeciderParams) error {
	_, err := q.db.ExecContext(ctx, unlinkAppealsByDecider, arg.DecidedByToken, arg.DecidedBy)
	return err
}

const withdrawAppeal = `-- name: WithdrawAppeal :execrows
UPDATE appeals
   SET state = 'withdrawn'
 WHERE id = ? AND appellant_id = ? AND state IN ('open', 'assigned')
`

type WithdrawAppealParams struct {
	ID          int64 `json:"id"`
	AppellantID int64 `json:"appellantId"`
}

// The appellant only, guarded to open/assigned states.
func (q *Queries) WithdrawAppeal(ctx context.Context, arg WithdrawAppealParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, withdrawAppeal, arg.ID, arg.AppellantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
