// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: erasure.sql

package dbgen

import (
	"context"
)

const completeErasureJob = `-- name: CompleteErasureJob :exec
UPDATE erasure_jobs
SET state = 'done',
    files_removed = ?,
    last_error = NULL,
    attempts = attempts + 1,
    updated_at = datetime('now'),
    finished_at = datetime('now')
WHERE id = ?
`

type CompleteErasureJobParams struct {
	FilesRemoved int64 `json:"filesRemoved"`
	ID           int64 `json:"id"`
}

func (q *Queries) CompleteErasureJob(ctx context.Context, arg CompleteErasureJobParams) error {
	_, err := q.db.ExecContext(ctx, completeErasureJob, arg.FilesRemoved, arg.ID)
	return err
}

const countUnfinishedErasureJobs = `-- name: CountUnfinishedErasureJobs :one
SELECT COUNT(*) FROM erasure_jobs WHERE state <> 'done'
`

func (q *Queries) CountUnfinishedErasureJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnfinishedErasureJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getErasureJob = `-- name: GetErasureJob :one
SELECT id, user_id, state, files, files_removed, attempts, last_error, finished_at, replay_purged
FROM erasure_jobs
WHERE id = ?
`

type GetErasureJobRow struct {
	ID           int64   `json:"id"`
	UserID       int64   `json:"userId"`
	State        string  `json:"state"`
	Files        string  `json:"files"`
	FilesRemoved int64   `json:"filesRemoved"`
	Attempts     int64   `json:"attempts"`
	LastError    *string `json:"lastError"`
	FinishedAt   *string `json:"finishedAt"`
	ReplayPurged int64   `json:"replayPurged"`
}

func (q *Queries) GetErasureJob(ctx context.Context, id int64) (GetErasureJobRow, error) {
	row := q.db.QueryRowContext(ctx, getErasureJob, id)
	var i GetErasureJobRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.State,
		&i.Files,
		&i.FilesRemoved,
		&i.Attempts,
		&i.LastError,
		&i.FinishedAt,
		&i.ReplayPurged,
	)
	return i, err
}

const insertErasureJob = `-- name: InsertErasureJob :one

INSERT INTO erasure_jobs (user_id, state, files, replay_purged)
VALUES (?, 'db_done', ?, 0)
RETURNING id
`

type InsertErasureJobParams struct {
	UserID int64  `json:"userId"`
	Files  string `json:"files"`
}

// Erasure jobs (migration 037, B4-9): the durable file half of an account
// erasure. The row is written inside the erasure transaction with the
// stored_as names of every file the subject owned; the runner removes them
// after commit and marks the job done, retrying from startup and the
// maintenance tick until it is.
func (q *Queries) InsertErasureJob(ctx context.Context, arg InsertErasureJobParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertErasureJob, arg.UserID, arg.Files)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listUnfinishedErasureJobs = `-- name: ListUnfinishedErasureJobs :many
SELECT id, user_id, state, files, files_removed, attempts, last_error, replay_purged
FROM erasure_jobs
WHERE state <> 'done' OR replay_purged = 0
ORDER BY id ASC
`

type ListUnfinishedErasureJobsRow struct {
	ID           int64   `json:"id"`
	UserID       int64   `json:"userId"`
	State        string  `json:"state"`
	Files        string  `json:"files"`
	FilesRemoved int64   `json:"filesRemoved"`
	Attempts     int64   `json:"attempts"`
	LastError    *string `json:"lastError"`
	ReplayPurged int64   `json:"replayPurged"`
}

func (q *Queries) ListUnfinishedErasureJobs(ctx context.Context) ([]ListUnfinishedErasureJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnfinishedErasureJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnfinishedErasureJobsRow{}
	for rows.Next() {
		var i ListUnfinishedErasureJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.State,
			&i.Files,
			&i.FilesRemoved,
			&i.Attempts,
			&i.LastError,
			&i.ReplayPurged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markErasureJobReplayPurged = `-- name: MarkErasureJobReplayPurged :exec
UPDATE erasure_jobs
SET replay_purged = 1,
    updated_at = datetime('now')
WHERE id = ?
`

func (q *Queries) MarkErasureJobReplayPurged(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markErasureJobReplayPurged, id)
	return err
}

const recordErasureJobAttempt = `-- name: RecordErasureJobAttempt :exec
UPDATE erasure_jobs
SET attempts = attempts + 1,
    files_removed = ?,
    last_error = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type RecordErasureJobAttemptParams struct {
	FilesRemoved int64   `json:"filesRemoved"`
	LastError    *string `json:"lastError"`
	ID           int64   `json:"id"`
}

func (q *Queries) RecordErasureJobAttempt(ctx context.Context, arg RecordErasureJobAttemptParams) error {
	_, err := q.db.ExecContext(ctx, recordErasureJobAttempt, arg.FilesRemoved, arg.LastError, arg.ID)
	return err
}
