// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message_delivery.sql

package dbgen

import (
	"context"
)

const createMessageForDelivery = `-- name: CreateMessageForDelivery :one
INSERT INTO messages (channel_id, user_id, content, reply_to, mentions_everyone)
VALUES (?, ?, ?, ?, ?)
RETURNING id, channel_id, user_id, content, reply_to, edited_at, deleted, pinned, timestamp, mentions_everyone
`

type CreateMessageForDeliveryParams struct {
	ChannelID        int64  `json:"channelId"`
	UserID           int64  `json:"userId"`
	Content          string `json:"content"`
	ReplyTo          *int64 `json:"replyTo"`
	MentionsEveryone int64  `json:"mentionsEveryone"`
}

func (q *Queries) CreateMessageForDelivery(ctx context.Context, arg CreateMessageForDeliveryParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessageForDelivery,
		arg.ChannelID,
		arg.UserID,
		arg.Content,
		arg.ReplyTo,
		arg.MentionsEveryone,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.Content,
		&i.ReplyTo,
		&i.EditedAt,
		&i.Deleted,
		&i.Pinned,
		&i.Timestamp,
		&i.MentionsEveryone,
	)
	return i, err
}

const deleteExpiredMessageDeliveryReceipts = `-- name: DeleteExpiredMessageDeliveryReceipts :exec
DELETE FROM message_delivery_receipts WHERE expires_at_ms <= ?
`

func (q *Queries) DeleteExpiredMessageDeliveryReceipts(ctx context.Context, expiresAtMs int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredMessageDeliveryReceipts, expiresAtMs)
	return err
}

const getMessageDeliveryReceipt = `-- name: GetMessageDeliveryReceipt :one
SELECT r.user_id, r.client_message_id, r.channel_id, r.payload_hash,
       r.message_id, r.timestamp, r.expires_at_ms,
       EXISTS(SELECT 1 FROM messages m WHERE m.id = r.message_id
              AND m.user_id = r.user_id AND m.channel_id = r.channel_id AND m.deleted = 0) AS available
FROM message_delivery_receipts r WHERE r.user_id = ? AND r.client_message_id = ?
`

type GetMessageDeliveryReceiptParams struct {
	UserID          int64  `json:"userId"`
	ClientMessageID string `json:"clientMessageId"`
}

type GetMessageDeliveryReceiptRow struct {
	UserID          int64  `json:"userId"`
	ClientMessageID string `json:"clientMessageId"`
	ChannelID       int64  `json:"channelId"`
	PayloadHash     []byte `json:"payloadHash"`
	MessageID       int64  `json:"messageId"`
	Timestamp       string `json:"timestamp"`
	ExpiresAtMs     int64  `json:"expiresAtMs"`
	Available       int64  `json:"available"`
}

func (q *Queries) GetMessageDeliveryReceipt(ctx context.Context, arg GetMessageDeliveryReceiptParams) (GetMessageDeliveryReceiptRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageDeliveryReceipt, arg.UserID, arg.ClientMessageID)
	var i GetMessageDeliveryReceiptRow
	err := row.Scan(
		&i.UserID,
		&i.ClientMessageID,
		&i.ChannelID,
		&i.PayloadHash,
		&i.MessageID,
		&i.Timestamp,
		&i.ExpiresAtMs,
		&i.Available,
	)
	return i, err
}

const insertMessageDeliveryReceipt = `-- name: InsertMessageDeliveryReceipt :exec
INSERT INTO message_delivery_receipts
    (user_id, client_message_id, channel_id, payload_hash, message_id, timestamp, expires_at_ms)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertMessageDeliveryReceiptParams struct {
	UserID          int64  `json:"userId"`
	ClientMessageID string `json:"clientMessageId"`
	ChannelID       int64  `json:"channelId"`
	PayloadHash     []byte `json:"payloadHash"`
	MessageID       int64  `json:"messageId"`
	Timestamp       string `json:"timestamp"`
	ExpiresAtMs     int64  `json:"expiresAtMs"`
}

func (q *Queries) InsertMessageDeliveryReceipt(ctx context.Context, arg InsertMessageDeliveryReceiptParams) error {
	_, err := q.db.ExecContext(ctx, insertMessageDeliveryReceipt,
		arg.UserID,
		arg.ClientMessageID,
		arg.ChannelID,
		arg.PayloadHash,
		arg.MessageID,
		arg.Timestamp,
		arg.ExpiresAtMs,
	)
	return err
}
