// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AddReaction(ctx context.Context, arg AddReactionParams) error
	AdminUpdateChannel(ctx context.Context, arg AdminUpdateChannelParams) error
	ApplyVoiceServerDeafen(ctx context.Context, arg ApplyVoiceServerDeafenParams) (sql.Result, error)
	// Scoped to channel_id as well as user_id: the moderator's authorization is
	// checked against a channel snapshot several round trips before this write
	// lands, so an unscoped `WHERE user_id = ?` would follow the target onto
	// whatever channel their row points at by then -- including a DM call the
	// moderator was never authorized against (OC-0005). :execresult so the
	// caller can tell a real no-op (target moved) from a normal apply.
	ApplyVoiceServerMute(ctx context.Context, arg ApplyVoiceServerMuteParams) (sql.Result, error)
	ApprovePendingUser(ctx context.Context, id int64) (sql.Result, error)
	BanUser(ctx context.Context, arg BanUserParams) error
	BlockUser(ctx context.Context, arg BlockUserParams) error
	CleanupExpiredLockouts(ctx context.Context, expiresAt string) error
	CleanupExpiredPartialAuthChallenges(ctx context.Context, expiresAt string) error
	CleanupExpiredPendingTOTPEnrollments(ctx context.Context, expiresAt string) error
	CleanupExpiredUsedTOTPCodes(ctx context.Context, expiresAt string) error
	ClearAllVoiceStates(ctx context.Context) error
	ClearVoiceServerDeafen(ctx context.Context, arg ClearVoiceServerDeafenParams) (sql.Result, error)
	ClearVoiceServerMute(ctx context.Context, arg ClearVoiceServerMuteParams) (sql.Result, error)
	ClearVoiceState(ctx context.Context, userID int64) error
	CloseDM(ctx context.Context, arg CloseDMParams) error
	CompleteErasureJob(ctx context.Context, arg CompleteErasureJobParams) error
	// The consume deletes only the live credential whose verifier the caller
	// compared against, so the affected row count is what tells two concurrent
	// redemptions, an expired credential, and a credential replaced since the
	// compare apart.
	ConsumeRecoveryAssist(ctx context.Context, arg ConsumeRecoveryAssistParams) (sql.Result, error)
	// The consume is conditional: only an unspent kit is spent, and the affected
	// row count is what tells two concurrent redemptions apart.
	ConsumeRecoveryKit(ctx context.Context, arg ConsumeRecoveryKitParams) (sql.Result, error)
	CountActiveCameras(ctx context.Context, channelID int64) (int64, error)
	CountActiveInvites(ctx context.Context) (int64, error)
	CountActiveMessages(ctx context.Context) (int64, error)
	CountChannels(ctx context.Context) (int64, error)
	CountDMParticipants(ctx context.Context, channelID int64) (int64, error)
	CountPendingUsers(ctx context.Context) (int64, error)
	CountRoleMembers(ctx context.Context) ([]CountRoleMembersRow, error)
	CountUnfinishedErasureJobs(ctx context.Context) (int64, error)
	CountUnusedRecoveryCodes(ctx context.Context, userID int64) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// Authorization probe for the file route: an unlinked attachment is readable by
	// everyone exactly while some user's avatar points at it. Covered by the
	// partial index on users(avatar) added in migration 027.
	CountUsersWithAvatar(ctx context.Context, avatar *string) (int64, error)
	// A lapsed temporary ban must not hide a TOTP-less user from this count: the
	// ban_expires arm mirrors auth.IsEffectivelyBanned (and db.notBannedClause /
	// ListMembers above), which treats an elapsed ban as "not banned" and lets
	// the user log in. Without it, require_2fa can be enabled while such a user
	// still exists, and their next login is refused forever with no recovery
	// path. The replace() normalises the space-separator form of ban_expires to
	// 'T' before comparing, because ' ' sorts below 'T'.
	CountUsersWithoutTOTP(ctx context.Context) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (sql.Result, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error
	CreateChannel(ctx context.Context, arg CreateChannelParams) (sql.Result, error)
	CreateEmoji(ctx context.Context, arg CreateEmojiParams) (CreateEmojiRow, error)
	CreateInvite(ctx context.Context, arg CreateInviteParams) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	// Approval-mode registration (B4-1): the account exists from the application
	// on, as registration_status = 'pending', and cannot sign in until an admin
	// approves it. Denial anonymises the row and marks it 'denied' for good.
	// The cap is enforced in the same statement as the insert: SQLite runs the
	// writer serially, so two applications racing for the last slot cannot both
	// observe room. Zero rows affected means the queue is full.
	CreatePendingUser(ctx context.Context, arg CreatePendingUserParams) (sql.Result, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteChannel(ctx context.Context, id int64) error
	DeleteChannelPermission(ctx context.Context, arg DeleteChannelPermissionParams) error
	DeleteChannelUserPermission(ctx context.Context, arg DeleteChannelUserPermissionParams) error
	DeleteEmoji(ctx context.Context, id int64) (sql.Result, error)
	// Sargable text comparison against idx_sessions_expires_at (migration 031).
	// expires_at is stored as RFC3339 UTC ("2006-01-02T15:04:05Z") and the
	// migration normalized legacy rows, so the caller must pass the cutoff in
	// exactly that layout -- a space-separated cutoff would compare wrong.
	DeleteExpiredSessions(ctx context.Context, expiresAt string) error
	DeleteLockout(ctx context.Context, key string) error
	// Avatars are attachments that are never linked to a message on purpose: the
	// users.avatar URL is what keeps them alive and authorizes serving them
	// (migration 027). Excluding them here is what stops the sweep from destroying
	// every avatar in the instance. idx_users_avatar makes the lookup cheap.
	//
	// OC-0279: a message delete is a soft delete (messages.deleted=1, the row
	// survives), so an attachment linked to a deleted message keeps a non-NULL
	// message_id forever -- message_id IS NULL alone never matches it, so its
	// file was permanently unreclaimable even though serveFileResolve already
	// 404s it once the owning message is deleted. The second EXISTS below
	// catches that case by joining back to messages.deleted instead. Matching on
	// messages.deleted=1 here (rather than unlinking message_id in the delete
	// path) is deliberate: unlinking would move the row onto the "unlinked
	// attachment" access branch in serveFileAuthorize and make it downloadable
	// again by the uploader.
	DeleteOrphanedAttachments(ctx context.Context, uploadedAt string) ([]string, error)
	DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) (sql.Result, error)
	DeletePartialAuthChallenge(ctx context.Context, tokenHash string) (sql.Result, error)
	DeletePendingTOTPEnrollment(ctx context.Context, userID int64) error
	DeleteRecoveryAssist(ctx context.Context, userID int64) error
	DeleteRecoveryCodes(ctx context.Context, userID int64) error
	DeleteRecoveryKit(ctx context.Context, userID int64) error
	DeleteRole(ctx context.Context, id int64) error
	DeleteSessionByID(ctx context.Context, arg DeleteSessionByIDParams) (sql.Result, error)
	DeleteSessionByToken(ctx context.Context, token string) error
	DeleteUsedTOTPCode(ctx context.Context, arg DeleteUsedTOTPCodeParams) error
	DeleteUserSessions(ctx context.Context, userID int64) (sql.Result, error)
	DenyPendingUser(ctx context.Context, arg DenyPendingUserParams) (sql.Result, error)
	DisablePlugin(ctx context.Context, id int64) error
	// The deleted = 0 guard is the one SoftDeleteMessage and SetMessagePinned
	// already carry (OC-0284): an edit that races a delete must not rewrite a
	// tombstone. No row comes back when it loses, which the wrapper reports as
	// ErrNotFound rather than a silent success (OC-0358).
	EditMessageContent(ctx context.Context, arg EditMessageContentParams) (Message, error)
	// Camera and screenshare share one voice_max_video budget, counted in
	// STREAMS, not rows: a channel capped at N simultaneous video streams must
	// not let a camera publish ignore screenshare occupants (or vice versa,
	// OC-0023), and a single user with both flags set must consume two of the N
	// slots, not one (OC-0006) -- so both gates sum `vs2.camera + vs2.screenshare`
	// across the channel's rows rather than counting rows where either is set.
	// The enabling user's own bit for the flag being set CAN already be 1 at
	// gate time (a client that lost track of the server-side flag retries the
	// enable), so each gate excludes exactly that one bit from the count --
	// see the per-query comments below (OC-0081).
	// The channel-wide stream count excludes the requester's own camera flag
	// (subtracted via the correlated outer-row reference), so re-enabling an
	// already-set camera is idempotent at the cap instead of being refused
	// against the requester's own stream (OC-0081). Their screenshare, and
	// every other user's streams, still count.
	EnableCameraIfUnderLimit(ctx context.Context, arg EnableCameraIfUnderLimitParams) (sql.Result, error)
	EnablePlugin(ctx context.Context, id int64) error
	// Mirror of EnableCameraIfUnderLimit: the count excludes the requester's
	// own screenshare flag so re-enable is idempotent at the cap (OC-0081).
	EnableScreenshareIfUnderLimit(ctx context.Context, arg EnableScreenshareIfUnderLimitParams) (sql.Result, error)
	EvictOldestSessions(ctx context.Context, arg EvictOldestSessionsParams) error
	// The 1:1 DM channel between two users, if one exists. Mirrors the lookup
	// inside GetOrCreateDMChannel (raw, transactional) without creating anything:
	// the is_group clause keeps group DMs out, matching the block-enforcement
	// boundary (blocks never gate group DMs). ORDER BY makes the row choice
	// deterministic should duplicates ever exist.
	FindDMChannelIDBetween(ctx context.Context, arg FindDMChannelIDBetweenParams) (int64, error)
	ForceLogoutUser(ctx context.Context, userID int64) error
	// Auth-hot lookup: returns the token only if it is neither revoked nor expired,
	// so a resolved row is always usable. Matches the sessions never-expiring
	// convention (expires_at IS NULL).
	GetActiveAPIToken(ctx context.Context, tokenHash string) (ApiToken, error)
	GetAllSettings(ctx context.Context) ([]Setting, error)
	GetAllVoiceStates(ctx context.Context) ([]GetAllVoiceStatesRow, error)
	GetAttachmentByID(ctx context.Context, id string) (GetAttachmentByIDRow, error)
	GetAttachmentWithChannel(ctx context.Context, id string) (GetAttachmentWithChannelRow, error)
	GetAuditLog(ctx context.Context, arg GetAuditLogParams) ([]GetAuditLogRow, error)
	GetChannel(ctx context.Context, id int64) (GetChannelRow, error)
	GetChannelOverrides(ctx context.Context, channelID int64) ([]GetChannelOverridesRow, error)
	GetChannelPermission(ctx context.Context, arg GetChannelPermissionParams) (GetChannelPermissionRow, error)
	GetChannelUnreadCounts(ctx context.Context, arg GetChannelUnreadCountsParams) ([]GetChannelUnreadCountsRow, error)
	GetChannelUserOverrides(ctx context.Context, channelID int64) ([]GetChannelUserOverridesRow, error)
	GetChannelUserPermission(ctx context.Context, arg GetChannelUserPermissionParams) (GetChannelUserPermissionRow, error)
	GetChannelVoiceStates(ctx context.Context, channelID int64) ([]GetChannelVoiceStatesRow, error)
	GetDMParticipantIDs(ctx context.Context, channelID int64) ([]int64, error)
	GetDMParticipants(ctx context.Context, channelID int64) ([]GetDMParticipantsRow, error)
	// Every participant of every DM the user has open, in one pass. Includes the
	// user themselves so a caller can tell "group of three" from "group of three
	// others"; the Go layer filters when it needs the others.
	GetDMParticipantsForUser(ctx context.Context, userID int64) ([]GetDMParticipantsForUserRow, error)
	// The fallback role every member lands on when their role is deleted. Highest
	// position wins if a database somehow carries more than one default.
	GetDefaultRole(ctx context.Context) (Role, error)
	GetEmojiByID(ctx context.Context, id int64) (GetEmojiByIDRow, error)
	GetEmojiByShortcode(ctx context.Context, shortcode string) (GetEmojiByShortcodeRow, error)
	GetErasureJob(ctx context.Context, id int64) (GetErasureJobRow, error)
	GetEventsSince(ctx context.Context, arg GetEventsSinceParams) ([]GetEventsSinceRow, error)
	GetInvite(ctx context.Context, code string) (GetInviteRow, error)
	GetLatestMessageID(ctx context.Context, channelID int64) (interface{}, error)
	GetMaxEventSeq(ctx context.Context) (int64, error)
	GetMessage(ctx context.Context, id int64) (Message, error)
	GetMessagesForAPI(ctx context.Context, arg GetMessagesForAPIParams) ([]GetMessagesForAPIRow, error)
	// The highest-privilege account (role with the greatest position), used as the
	// default identity for `token create`. FROM is users-only (role position is a
	// correlated subquery, not a join) so the row maps through userFromGen exactly
	// like GetUserByID, so keep this SELECT list identical to GetUserByID's.
	// A :one query already reads a single row via QueryRow, so no LIMIT is needed
	// (and an explicit LIMIT 1 is mis-emitted by sqlc here). ORDER BY puts the
	// highest-position role first, so that first row is the owner.
	// Banned users are excluded: account deletion anonymises the row and sets
	// banned = 1 permanently, so without this filter a self-deleted Owner keeps
	// outranking every live admin and becomes the default identity for token
	// creation forever -- minting tokens the auth layer then 403s on every use.
	// The ban_expires arm mirrors auth.IsEffectivelyBanned (and db.notBannedClause)
	// so a lapsed temporary ban stays eligible; the replace() normalises the space
	// separator form of ban_expires to 'T' before comparing, because ' ' sorts
	// below 'T' and a same-day space-form expiry would otherwise read as lapsed.
	GetOwnerUser(ctx context.Context) (User, error)
	GetPartialAuthChallenge(ctx context.Context, tokenHash string) (GetPartialAuthChallengeRow, error)
	GetPendingTOTPEnrollment(ctx context.Context, userID int64) (GetPendingTOTPEnrollmentRow, error)
	GetReactionCounts(ctx context.Context, messageID int64) ([]GetReactionCountsRow, error)
	// Reactors for one (message, emoji) pair, oldest reaction first. The reactions
	// table has no timestamp column, so the autoincrement id carries the order.
	GetReactionUsers(ctx context.Context, arg GetReactionUsersParams) ([]GetReactionUsersRow, error)
	// Reader-pool lookup that lets the channel-focus path skip the UpdateReadState
	// UPSERT when the row is already correct, keeping no-op focus events off the
	// single writer connection.
	GetReadState(ctx context.Context, arg GetReadStateParams) (GetReadStateRow, error)
	GetRecoveryAssist(ctx context.Context, userID int64) (RecoveryAssist, error)
	GetRecoveryKit(ctx context.Context, userID int64) (RecoveryKit, error)
	GetRoleByID(ctx context.Context, id int64) (Role, error)
	// Case-insensitive by design: migration 023 enforces uniqueness under the same
	// collation, so this is the lookup that agrees with the constraint.
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetRoleChannelPermissions(ctx context.Context, roleID int64) ([]GetRoleChannelPermissionsRow, error)
	GetRoleForUser(ctx context.Context, id int64) (Role, error)
	GetSessionByTokenHash(ctx context.Context, token string) (Session, error)
	GetSessionWithBanStatus(ctx context.Context, token string) (GetSessionWithBanStatusRow, error)
	GetSetting(ctx context.Context, key string) (string, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserChannelPermissions(ctx context.Context, userID int64) ([]GetUserChannelPermissionsRow, error)
	GetUserDMChannelIDs(ctx context.Context, userID int64) ([]int64, error)
	// A DM row carries no recipient any more: dm_participants holds N users, so
	// "the other one" is only well defined for a two-person DM. The participant
	// set comes from GetDMParticipantsForUser below, one extra query for the whole
	// list rather than one per channel, and the Go layer stitches them together.
	GetUserDMChannels(ctx context.Context, userID int64) ([]GetUserDMChannelsRow, error)
	GetUserSessions(ctx context.Context, userID int64) ([]Session, error)
	GetUserVoiceState(ctx context.Context, userID int64) (GetUserVoiceStateRow, error)
	GetUserWithRole(ctx context.Context, id int64) (GetUserWithRoleRow, error)
	// Erasure jobs (migration 037, B4-9): the durable file half of an account
	// erasure. The row is written inside the erasure transaction with the
	// stored_as names of every file the subject owned; the runner removes them
	// after commit and marks the job done, retrying from startup and the
	// maintenance tick until it is.
	InsertErasureJob(ctx context.Context, arg InsertErasureJobParams) (int64, error)
	InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error
	InsertSession(ctx context.Context, arg InsertSessionParams) (sql.Result, error)
	InsertUsedTOTPCode(ctx context.Context, arg InsertUsedTOTPCodeParams) (sql.Result, error)
	InstallPlugin(ctx context.Context, arg InstallPluginParams) (sql.Result, error)
	IsBlocked(ctx context.Context, arg IsBlockedParams) (int64, error)
	IsDMParticipant(ctx context.Context, arg IsDMParticipantParams) (int64, error)
	IsEitherBlocked(ctx context.Context, arg IsEitherBlockedParams) (int64, error)
	IsGroupDM(ctx context.Context, id int64) (int64, error)
	// server_muted / server_deafened are deliberately absent from both upserts'
	// reset lists: a moderator-imposed mute must survive a channel switch, which
	// reaches the ON CONFLICT branch. It is scoped to the voice session:
	// leaving voice deletes the row, so a rejoin starts clean.
	JoinVoiceChannel(ctx context.Context, arg JoinVoiceChannelParams) error
	// The channel-wide row count excludes the joining user's own existing row
	// (if any), mirroring the OC-0081 fix on EnableCameraIfUnderLimit /
	// EnableScreenshareIfUnderLimit below. Without this, a user who already
	// holds a row on the target channel (e.g. retrying a join after a failed
	// channel-switch left their old row in place) gets counted against their
	// own capacity slot, so a full channel refuses an upsert that would only
	// replace the row already there (OC-0255).
	JoinVoiceChannelIfCapacity(ctx context.Context, arg JoinVoiceChannelIfCapacityParams) (sql.Result, error)
	LeaveVoiceChannel(ctx context.Context, userID int64) error
	LeaveVoiceChannelIfMatch(ctx context.Context, arg LeaveVoiceChannelIfMatchParams) (sql.Result, error)
	// Admin/CLI listing. Never selects token_hash (unrecoverable; only the raw
	// token shown at creation is usable).
	ListAPITokens(ctx context.Context) ([]ListAPITokensRow, error)
	ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]ListAllUsersRow, error)
	ListBlockedUsers(ctx context.Context, blockerID int64) ([]int64, error)
	ListBlockersOfUser(ctx context.Context, blockedID int64) ([]int64, error)
	ListChannels(ctx context.Context) ([]ListChannelsRow, error)
	ListEmoji(ctx context.Context) ([]ListEmojiRow, error)
	ListInvites(ctx context.Context) ([]ListInvitesRow, error)
	// The ready payload's member roster. docs/protocol.md documents members[] as
	// "All registered users", so this must not silently truncate: the previous
	// LIMIT 1000 dropped every member past the first thousand with no has_more
	// signal, leaving those users unrenderable and unmentionable on the client
	// with nothing to indicate the list was incomplete.
	ListMembers(ctx context.Context) ([]ListMembersRow, error)
	ListPendingUsers(ctx context.Context, arg ListPendingUsersParams) ([]ListPendingUsersRow, error)
	ListPlugins(ctx context.Context) ([]Plugin, error)
	// Highest rank first. Positions are only "unique enough": reorder normalizes
	// them, but creating a role inserts just below the actor and may tie with an
	// existing role, so id is a tiebreaker. Without it SQLite may return tied rows
	// in any order, and the admin panel derives its reorder payload from this
	// order, so a single move-up would silently shuffle the tied roles.
	// NOTE: keep comments in this file ASCII-only. sqlc mixes byte and rune
	// offsets when stripping them, so a non-ASCII character here truncates the
	// generated SQL of THIS and every following query by the byte/rune delta.
	ListRoles(ctx context.Context) ([]Role, error)
	ListUnfinishedErasureJobs(ctx context.Context) ([]ListUnfinishedErasureJobsRow, error)
	ListUnusedRecoveryCodes(ctx context.Context, userID int64) ([]ListUnusedRecoveryCodesRow, error)
	ListUserIDsByRole(ctx context.Context, roleID int64) ([]int64, error)
	ListUserSessions(ctx context.Context, userID int64) ([]Session, error)
	LoadActiveLockouts(ctx context.Context, expiresAt string) ([]RateLockout, error)
	LogAudit(ctx context.Context, arg LogAuditParams) error
	LogAuditEntry(ctx context.Context, arg LogAuditEntryParams) error
	// Mark-read that computes its own watermark inside the writer statement.
	// Passing a snapshot read moments earlier is what destroyed a mention raised
	// during the round trip (OC-0323): the clear zeroed mention_count while
	// last_message_id still pointed behind the mentioning message, so the badge was
	// gone and nothing ever recomputed it. Computing MAX(id) here means every
	// message committed before this statement is covered by last_message_id, and
	// every message committed after it finds IncrementMentionCounts' own
	// `last_message_id < msgID` guard true, so its mention survives.
	MarkChannelReadAtLatest(ctx context.Context, arg MarkChannelReadAtLatestParams) error
	MarkRecoveryCodeUsed(ctx context.Context, arg MarkRecoveryCodeUsedParams) (sql.Result, error)
	// The new-login signal (B4-7): listing the account's sessions from one
	// device acknowledges every other session's login. The caller's own row is
	// left alone so a device never acknowledges itself.
	MarkSessionsSeen(ctx context.Context, arg MarkSessionsSeenParams) (sql.Result, error)
	// Disconnect bookkeeping. It clears only 'online', which is the one status
	// that means "has a live session"; idle, dnd and invisible are choices the
	// user made and are what the next connect reads instead of stamping online
	// (db.ConnectStatus). A stale choice never renders as "present" because the
	// read path treats a member with no live connection as offline regardless.
	MarkUserDisconnected(ctx context.Context, id int64) error
	OpenDM(ctx context.Context, arg OpenDMParams) (int64, error)
	// seq is supplied by the hub so the row seq matches the wrapped-payload seq.
	PersistEvent(ctx context.Context, arg PersistEventParams) error
	PluginKVDelete(ctx context.Context, arg PluginKVDeleteParams) error
	PluginKVGet(ctx context.Context, arg PluginKVGetParams) ([]byte, error)
	PluginKVSet(ctx context.Context, arg PluginKVSetParams) error
	PruneEventsOlderThan(ctx context.Context, createdAt time.Time) (int64, error)
	RecordErasureJobAttempt(ctx context.Context, arg RecordErasureJobAttemptParams) error
	RemoveDMParticipant(ctx context.Context, arg RemoveDMParticipantParams) error
	RemoveReaction(ctx context.Context, arg RemoveReactionParams) (sql.Result, error)
	// Startup reset: nothing is connected yet, so every 'online' is a leftover
	// from the previous process. Chosen statuses survive for the same reason they
	// survive a disconnect.
	ResetAllUserStatuses(ctx context.Context) error
	RevokeAPIToken(ctx context.Context, id int64) (sql.Result, error)
	RevokeAPITokenByLabel(ctx context.Context, label string) (sql.Result, error)
	RevokeInvite(ctx context.Context, code string) error
	SetChannelSlowMode(ctx context.Context, arg SetChannelSlowModeParams) error
	SetChannelVoiceMaxUsers(ctx context.Context, arg SetChannelVoiceMaxUsersParams) error
	SetDMChannelName(ctx context.Context, arg SetDMChannelNameParams) error
	SetMessagePinned(ctx context.Context, arg SetMessagePinnedParams) (sql.Result, error)
	SetRolePosition(ctx context.Context, arg SetRolePositionParams) error
	SetSetting(ctx context.Context, arg SetSettingParams) error
	SoftDeleteMessage(ctx context.Context, id int64) (sql.Result, error)
	TouchAPIToken(ctx context.Context, tokenHash string) error
	TouchSession(ctx context.Context, token string) error
	UnbanUser(ctx context.Context, id int64) error
	UnblockUser(ctx context.Context, arg UnblockUserParams) error
	UninstallPlugin(ctx context.Context, id int64) error
	UpdateChannel(ctx context.Context, arg UpdateChannelParams) error
	// Marking a channel read also clears its mention badge: channel_focus is the
	// only caller, and a focused channel has no outstanding mentions by definition.
	UpdateReadState(ctx context.Context, arg UpdateReadStateParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	// Separate from UpdateUserProfile because a custom status arrives over the
	// WebSocket presence path, not the REST profile PATCH, and must not be able to
	// clobber the username/avatar of a profile edit racing it.
	UpdateUserCustomStatus(ctx context.Context, arg UpdateUserCustomStatusParams) error
	UpdateUserIdentityKey(ctx context.Context, arg UpdateUserIdentityKeyParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (sql.Result, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpdateUserTOTPSecret(ctx context.Context, arg UpdateUserTOTPSecretParams) error
	UpdateVoiceCamera(ctx context.Context, arg UpdateVoiceCameraParams) error
	UpdateVoiceDeafen(ctx context.Context, arg UpdateVoiceDeafenParams) error
	UpdateVoiceMute(ctx context.Context, arg UpdateVoiceMuteParams) error
	UpdateVoiceScreenshare(ctx context.Context, arg UpdateVoiceScreenshareParams) error
	UpsertChannelPermission(ctx context.Context, arg UpsertChannelPermissionParams) error
	UpsertChannelUserPermission(ctx context.Context, arg UpsertChannelUserPermissionParams) error
	UpsertLockout(ctx context.Context, arg UpsertLockoutParams) error
	// Second-factor state (migration 032, B4-3). ASCII only in this file: sqlc
	// v1.30.0 miscounts multi-byte characters and truncates the next query.
	UpsertPartialAuthChallenge(ctx context.Context, arg UpsertPartialAuthChallengeParams) error
	UpsertPendingTOTPEnrollment(ctx context.Context, arg UpsertPendingTOTPEnrollmentParams) error
	// Owner-issued recovery credentials (B4-6): one per account, replaced on
	// issuance, deleted by the redemption that consumes it. The verifier is an
	// argon2id PHC string and no query returns anything else about the secret.
	UpsertRecoveryAssist(ctx context.Context, arg UpsertRecoveryAssistParams) error
	// Recovery kits (B4-5): one verifier per account, replaced on enrolment,
	// spent by a successful recovery. The verifier is an argon2id PHC string;
	// no query ever returns anything else about the kit.
	UpsertRecoveryKit(ctx context.Context, arg UpsertRecoveryKitParams) error
	UseInviteAtomic(ctx context.Context, code string) (sql.Result, error)
	UserCount(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
