// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	// Own rows only: userID must be the target. Zero rows affected means the
	// id does not exist, belongs to someone else, or is already acknowledged --
	// the caller answers the same NOT_FOUND either way, so this can never be
	// used to probe another user's warning ids.
	AcknowledgeWarning(ctx context.Context, arg AcknowledgeWarningParams) (int64, error)
	AddReaction(ctx context.Context, arg AddReactionParams) error
	AdminUpdateChannel(ctx context.Context, arg AdminUpdateChannelParams) error
	ApplyVoiceServerDeafen(ctx context.Context, arg ApplyVoiceServerDeafenParams) (sql.Result, error)
	// Scoped to channel_id as well as user_id: the moderator's authorization is
	// checked against a channel snapshot several round trips before this write
	// lands, so an unscoped `WHERE user_id = ?` would follow the target onto
	// whatever channel their row points at by then -- including a DM call the
	// moderator was never authorized against (OC-0005). :execresult so the
	// caller can tell a real no-op (target moved) from a normal apply.
	ApplyVoiceServerMute(ctx context.Context, arg ApplyVoiceServerMuteParams) (sql.Result, error)
	ApprovePendingUser(ctx context.Context, id int64) (sql.Result, error)
	// Guarded three ways, the same shape as reports' AssignReport: state (only
	// 'open' may be assigned -- nothing leaves a decided or withdrawn state),
	// the OBSERVED assignee (optimistic concurrency), and EXISTS(users) (a
	// moderator erased between requirePerm and this write cannot land as the
	// new assignee).
	AssignAppeal(ctx context.Context, arg AssignAppealParams) (int64, error)
	// Guarded three ways: state (nothing leaves a closed state), the OBSERVED
	// assignee (optimistic concurrency -- a concurrent reassignment moves this
	// out from under a racing caller, so its stale outrank verdict can never be
	// applied), and EXISTS(users) (a moderator erased between requirePerm and
	// this write cannot land as the new assignee). Zero rows affected covers
	// all three causes; the caller answers 409 for each.
	AssignReport(ctx context.Context, arg AssignReportParams) (int64, error)
	BanUser(ctx context.Context, arg BanUserParams) error
	BlockUser(ctx context.Context, arg BlockUserParams) error
	// The quota guard and the increment are one statement, so exactly one of
	// N concurrent uploads racing the last byte is admitted: SQLite serialises
	// writers and the WHERE is evaluated against the row the UPDATE sees.
	// Rows affected = admitted.
	ChargeUserStorage(ctx context.Context, arg ChargeUserStorageParams) (int64, error)
	// The unlimited-quota form: the counter is maintained whether or not a
	// quota is set, so turning one on later starts from a live number.
	ChargeUserStorageUnbounded(ctx context.Context, arg ChargeUserStorageUnboundedParams) error
	CleanupExpiredLockouts(ctx context.Context, expiresAt string) error
	CleanupExpiredPartialAuthChallenges(ctx context.Context, expiresAt string) error
	CleanupExpiredPendingTOTPEnrollments(ctx context.Context, expiresAt string) error
	CleanupExpiredUsedTOTPCodes(ctx context.Context, expiresAt string) error
	ClearAllVoiceStates(ctx context.Context) error
	ClearVoiceServerDeafen(ctx context.Context, arg ClearVoiceServerDeafenParams) (sql.Result, error)
	ClearVoiceServerMute(ctx context.Context, arg ClearVoiceServerMuteParams) (sql.Result, error)
	ClearVoiceState(ctx context.Context, userID int64) error
	CloseDM(ctx context.Context, arg CloseDMParams) error
	// open -> resolved|dismissed is close-without-assigning; assigned ->
	// resolved|dismissed is the ordinary path. Nothing leaves a closed state.
	CloseReport(ctx context.Context, arg CloseReportParams) (int64, error)
	CompleteErasureJob(ctx context.Context, arg CompleteErasureJobParams) error
	// The consume deletes only the live credential whose verifier the caller
	// compared against, so the affected row count is what tells two concurrent
	// redemptions, an expired credential, and a credential replaced since the
	// compare apart.
	ConsumeRecoveryAssist(ctx context.Context, arg ConsumeRecoveryAssistParams) (sql.Result, error)
	// The consume is conditional: only an unspent kit is spent, and the affected
	// row count is what tells two concurrent redemptions apart.
	ConsumeRecoveryKit(ctx context.Context, arg ConsumeRecoveryKitParams) (sql.Result, error)
	CountActiveCameras(ctx context.Context, channelID int64) (int64, error)
	CountActiveInvites(ctx context.Context) (int64, error)
	CountActiveMessages(ctx context.Context) (int64, error)
	CountChannels(ctx context.Context) (int64, error)
	CountDMParticipants(ctx context.Context, channelID int64) (int64, error)
	CountPendingUsers(ctx context.Context) (int64, error)
	CountRoleMembers(ctx context.Context) ([]CountRoleMembersRow, error)
	CountUnfinishedErasureJobs(ctx context.Context) (int64, error)
	CountUnusedRecoveryCodes(ctx context.Context, userID int64) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// Authorization probe for the file route: an unlinked attachment is readable by
	// everyone exactly while some user's avatar points at it. Covered by the
	// partial index on users(avatar) added in migration 027.
	CountUsersWithAvatar(ctx context.Context, avatar *string) (int64, error)
	// The eligible-moderator count for decision 8's self-review escape: every
	// user (other than exclude_id, the acting moderator) whose role holds
	// perm_bit or the Administrator bit. The bit test is done in SQL rather
	// than fetched row-by-row and checked in Go, since the count alone is all
	// the caller needs.
	CountUsersWithPermission(ctx context.Context, arg CountUsersWithPermissionParams) (int64, error)
	// A lapsed temporary ban must not hide a TOTP-less user from this count: the
	// ban_expires arm mirrors auth.IsEffectivelyBanned (and db.notBannedClause /
	// ListMembers above), which treats an elapsed ban as "not banned" and lets
	// the user log in. Without it, require_2fa can be enabled while such a user
	// still exists, and their next login is refused forever with no recovery
	// path. The replace() normalises the space-separator form of ban_expires to
	// 'T' before comparing, because ' ' sorts below 'T'.
	CountUsersWithoutTOTP(ctx context.Context) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (sql.Result, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error
	CreateChannel(ctx context.Context, arg CreateChannelParams) (sql.Result, error)
	CreateEmoji(ctx context.Context, arg CreateEmojiParams) (CreateEmojiRow, error)
	CreateInvite(ctx context.Context, arg CreateInviteParams) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	// Approval-mode registration (B4-1): the account exists from the application
	// on, as registration_status = 'pending', and cannot sign in until an admin
	// approves it. Denial anonymises the row and marks it 'denied' for good.
	// The cap is enforced in the same statement as the insert: SQLite runs the
	// writer serially, so two applications racing for the last slot cannot both
	// observe room. Zero rows affected means the queue is full.
	CreatePendingUser(ctx context.Context, arg CreatePendingUserParams) (sql.Result, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	// new_state is 'upheld' or 'overturned', validated in Go. Guarded to
	// open/assigned states -- nothing leaves a decided or withdrawn state -- and
	// EXISTS(users) for the deciding moderator (erased mid-flight cannot land).
	DecideAppeal(ctx context.Context, arg DecideAppealParams) (int64, error)
	DeleteChannel(ctx context.Context, id int64) error
	DeleteChannelPermission(ctx context.Context, arg DeleteChannelPermissionParams) error
	DeleteChannelUserPermission(ctx context.Context, arg DeleteChannelUserPermissionParams) error
	DeleteEmoji(ctx context.Context, id int64) (sql.Result, error)
	// Sargable text comparison against idx_sessions_expires_at (migration 031).
	// expires_at is stored as RFC3339 UTC ("2006-01-02T15:04:05Z") and the
	// migration normalized legacy rows, so the caller must pass the cutoff in
	// exactly that layout -- a space-separated cutoff would compare wrong.
	DeleteExpiredSessions(ctx context.Context, expiresAt string) error
	DeleteLockout(ctx context.Context, key string) error
	// Avatars are attachments that are never linked to a message on purpose: the
	// users.avatar URL is what keeps them alive and authorizes serving them
	// (migration 027). Excluding them here is what stops the sweep from destroying
	// every avatar in the instance. idx_users_avatar makes the lookup cheap.
	//
	// OC-0279: a message delete is a soft delete (messages.deleted=1, the row
	// survives), so an attachment linked to a deleted message keeps a non-NULL
	// message_id forever -- message_id IS NULL alone never matches it, so its
	// file was permanently unreclaimable even though serveFileResolve already
	// 404s it once the owning message is deleted. The second EXISTS below
	// catches that case by joining back to messages.deleted instead. Matching on
	// messages.deleted=1 here (rather than unlinking message_id in the delete
	// path) is deliberate: unlinking would move the row onto the "unlinked
	// attachment" access branch in serveFileAuthorize and make it downloadable
	// again by the uploader.
	DeleteOrphanedAttachments(ctx context.Context, uploadedAt string) ([]string, error)
	DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) (sql.Result, error)
	DeletePartialAuthChallenge(ctx context.Context, tokenHash string) (sql.Result, error)
	DeletePendingTOTPEnrollment(ctx context.Context, userID int64) error
	DeleteRecoveryAssist(ctx context.Context, userID int64) error
	DeleteRecoveryCodes(ctx context.Context, userID int64) error
	DeleteRecoveryKit(ctx context.Context, userID int64) error
	DeleteRole(ctx context.Context, id int64) error
	DeleteSessionByID(ctx context.Context, arg DeleteSessionByIDParams) (sql.Result, error)
	DeleteSessionByToken(ctx context.Context, token string) error
	DeleteUsedTOTPCode(ctx context.Context, arg DeleteUsedTOTPCodeParams) error
	DeleteUserSessions(ctx context.Context, userID int64) (sql.Result, error)
	DenyPendingUser(ctx context.Context, arg DenyPendingUserParams) (sql.Result, error)
	DisablePlugin(ctx context.Context, id int64) error
	// The deleted = 0 guard is the one SoftDeleteMessage and SetMessagePinned
	// already carry (OC-0284): an edit that races a delete must not rewrite a
	// tombstone. No row comes back when it loses, which the wrapper reports as
	// ErrNotFound rather than a silent success (OC-0358).
	EditMessageContent(ctx context.Context, arg EditMessageContentParams) (Message, error)
	// Camera and screenshare share one voice_max_video budget, counted in
	// STREAMS, not rows: a channel capped at N simultaneous video streams must
	// not let a camera publish ignore screenshare occupants (or vice versa,
	// OC-0023), and a single user with both flags set must consume two of the N
	// slots, not one (OC-0006) -- so both gates sum `vs2.camera + vs2.screenshare`
	// across the channel's rows rather than counting rows where either is set.
	// The enabling user's own bit for the flag being set CAN already be 1 at
	// gate time (a client that lost track of the server-side flag retries the
	// enable), so each gate excludes exactly that one bit from the count --
	// see the per-query comments below (OC-0081).
	// The channel-wide stream count excludes the requester's own camera flag
	// (subtracted via the correlated outer-row reference), so re-enabling an
	// already-set camera is idempotent at the cap instead of being refused
	// against the requester's own stream (OC-0081). Their screenshare, and
	// every other user's streams, still count.
	EnableCameraIfUnderLimit(ctx context.Context, arg EnableCameraIfUnderLimitParams) (sql.Result, error)
	EnablePlugin(ctx context.Context, id int64) error
	// Mirror of EnableCameraIfUnderLimit: the count excludes the requester's
	// own screenshare flag so re-enable is idempotent at the cap (OC-0081).
	EnableScreenshareIfUnderLimit(ctx context.Context, arg EnableScreenshareIfUnderLimitParams) (sql.Result, error)
	// user_storage is the per-user upload byte counter (migration 044, B5-2).
	// Keep this file ASCII-only: sqlc v1.30 truncates the next query by the
	// byte/rune difference of any multi-byte character.
	EnsureUserStorage(ctx context.Context, userID int64) error
	EvictOldestSessions(ctx context.Context, arg EvictOldestSessionsParams) error
	// appeals is the B5-10 rate-limited appeal against a moderation action
	// (migration 050). Keep this file ASCII-only: sqlc v1.30 truncates the next
	// query by the byte/rune difference of any multi-byte character.
	// The dedupe FAST PATH (mirrors reports' FindOpenOrAssignedReport): decision
	// 8 forbids re-appealing a decided appeal, and this table's UNIQUE(action_id)
	// forbids ANY second appeal against the same action, ever. This query alone
	// is a pre-check only and is not race-proof; the UNIQUE constraint on
	// InsertAppeal is what actually enforces it under concurrency.
	FindAppealForAction(ctx context.Context, actionID int64) (int64, error)
	// The 1:1 DM channel between two users, if one exists. Mirrors the lookup
	// inside GetOrCreateDMChannel (raw, transactional) without creating anything:
	// the is_group clause keeps group DMs out, matching the block-enforcement
	// boundary (blocks never gate group DMs). ORDER BY makes the row choice
	// deterministic should duplicates ever exist.
	FindDMChannelIDBetween(ctx context.Context, arg FindDMChannelIDBetweenParams) (int64, error)
	// The dedupe FAST PATH: the same reporter, the same target, an open or
	// assigned report already exists. This is a pre-check only -- it saves the
	// caller building an evidence snapshot for a report that will be refused --
	// idx_reports_active_unique (migration 048) is what actually enforces the
	// rule under concurrency; this query has no such guarantee alone.
	FindOpenOrAssignedReport(ctx context.Context, arg FindOpenOrAssignedReportParams) (int64, error)
	ForceLogoutUser(ctx context.Context, userID int64) error
	// Auth-hot lookup: returns the token only if it is neither revoked nor expired,
	// so a resolved row is always usable. Matches the sessions never-expiring
	// convention (expires_at IS NULL).
	GetActiveAPIToken(ctx context.Context, tokenHash string) (ApiToken, error)
	GetAllSettings(ctx context.Context) ([]Setting, error)
	GetAllVoiceStates(ctx context.Context) ([]GetAllVoiceStatesRow, error)
	GetAppealByID(ctx context.Context, id int64) (Appeal, error)
	// The only lookup a route parameter or a mod_queue frame's appeal_id ever
	// drives: public_id is the sole externally-visible identifier.
	GetAppealByPublicID(ctx context.Context, publicID string) (Appeal, error)
	GetAttachmentByID(ctx context.Context, id string) (GetAttachmentByIDRow, error)
	GetAttachmentWithChannel(ctx context.Context, id string) (GetAttachmentWithChannelRow, error)
	GetAuditLog(ctx context.Context, arg GetAuditLogParams) ([]GetAuditLogRow, error)
	GetChannel(ctx context.Context, id int64) (GetChannelRow, error)
	GetChannelOverrides(ctx context.Context, channelID int64) ([]GetChannelOverridesRow, error)
	GetChannelPermission(ctx context.Context, arg GetChannelPermissionParams) (GetChannelPermissionRow, error)
	GetChannelUnreadCounts(ctx context.Context, arg GetChannelUnreadCountsParams) ([]GetChannelUnreadCountsRow, error)
	GetChannelUserOverrides(ctx context.Context, channelID int64) ([]GetChannelUserOverridesRow, error)
	GetChannelUserPermission(ctx context.Context, arg GetChannelUserPermissionParams) (GetChannelUserPermissionRow, error)
	GetChannelVoiceStates(ctx context.Context, channelID int64) ([]GetChannelVoiceStatesRow, error)
	GetDMParticipantIDs(ctx context.Context, channelID int64) ([]int64, error)
	GetDMParticipants(ctx context.Context, channelID int64) ([]GetDMParticipantsRow, error)
	// Every participant of every DM the user has open, in one pass. Includes the
	// user themselves so a caller can tell "group of three" from "group of three
	// others"; the Go layer filters when it needs the others.
	GetDMParticipantsForUser(ctx context.Context, userID int64) ([]GetDMParticipantsForUserRow, error)
	// The fallback role every member lands on when their role is deleted. Highest
	// position wins if a database somehow carries more than one default.
	GetDefaultRole(ctx context.Context) (Role, error)
	GetEmojiByID(ctx context.Context, id int64) (GetEmojiByIDRow, error)
	GetEmojiByShortcode(ctx context.Context, shortcode string) (GetEmojiByShortcodeRow, error)
	GetErasureJob(ctx context.Context, id int64) (GetErasureJobRow, error)
	GetEventsSince(ctx context.Context, arg GetEventsSinceParams) ([]GetEventsSinceRow, error)
	GetInvite(ctx context.Context, code string) (GetInviteRow, error)
	GetLatestMessageID(ctx context.Context, channelID int64) (interface{}, error)
	GetMaxEventSeq(ctx context.Context) (int64, error)
	GetMessage(ctx context.Context, id int64) (Message, error)
	GetMessagesForAPI(ctx context.Context, arg GetMessagesForAPIParams) ([]GetMessagesForAPIRow, error)
	// B5-10's appeal submission and decision both need the appealed action's
	// own row: its kind (appealable or not), its target (must be the appellant),
	// and its actor (the deciding-moderator self-review check).
	GetModerationActionByID(ctx context.Context, id int64) (GetModerationActionByIDRow, error)
	// The highest-privilege account (role with the greatest position), used as the
	// default identity for `token create`. FROM is users-only (role position is a
	// correlated subquery, not a join) so the row maps through userFromGen exactly
	// like GetUserByID, so keep this SELECT list identical to GetUserByID's.
	// A :one query already reads a single row via QueryRow, so no LIMIT is needed
	// (and an explicit LIMIT 1 is mis-emitted by sqlc here). ORDER BY puts the
	// highest-position role first, so that first row is the owner.
	// Banned users are excluded: account deletion anonymises the row and sets
	// banned = 1 permanently, so without this filter a self-deleted Owner keeps
	// outranking every live admin and becomes the default identity for token
	// creation forever -- minting tokens the auth layer then 403s on every use.
	// The ban_expires arm mirrors auth.IsEffectivelyBanned (and db.notBannedClause)
	// so a lapsed temporary ban stays eligible; the replace() normalises the space
	// separator form of ban_expires to 'T' before comparing, because ' ' sorts
	// below 'T' and a same-day space-form expiry would otherwise read as lapsed.
	GetOwnerUser(ctx context.Context) (User, error)
	GetPartialAuthChallenge(ctx context.Context, tokenHash string) (GetPartialAuthChallengeRow, error)
	GetPendingTOTPEnrollment(ctx context.Context, userID int64) (GetPendingTOTPEnrollmentRow, error)
	GetReactionCounts(ctx context.Context, messageID int64) ([]GetReactionCountsRow, error)
	// Reactors for one (message, emoji) pair, oldest reaction first. The reactions
	// table has no timestamp column, so the autoincrement id carries the order.
	GetReactionUsers(ctx context.Context, arg GetReactionUsersParams) ([]GetReactionUsersRow, error)
	// Reader-pool lookup that lets the channel-focus path skip the UpdateReadState
	// UPSERT when the row is already correct, keeping no-op focus events off the
	// single writer connection.
	GetReadState(ctx context.Context, arg GetReadStateParams) (GetReadStateRow, error)
	GetRecoveryAssist(ctx context.Context, userID int64) (RecoveryAssist, error)
	GetRecoveryKit(ctx context.Context, userID int64) (RecoveryKit, error)
	GetReportByID(ctx context.Context, id int64) (Report, error)
	// The only lookup a route parameter or a mod_queue frame's id ever drives:
	// public_id is the sole externally-visible identifier (Codex review).
	GetReportByPublicID(ctx context.Context, publicID string) (Report, error)
	GetRoleByID(ctx context.Context, id int64) (Role, error)
	// Case-insensitive by design: migration 023 enforces uniqueness under the same
	// collation, so this is the lookup that agrees with the constraint.
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetRoleChannelPermissions(ctx context.Context, roleID int64) ([]GetRoleChannelPermissionsRow, error)
	GetRoleForUser(ctx context.Context, id int64) (Role, error)
	GetSessionByTokenHash(ctx context.Context, token string) (Session, error)
	GetSessionWithBanStatus(ctx context.Context, token string) (GetSessionWithBanStatusRow, error)
	GetSetting(ctx context.Context, key string) (string, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserChannelPermissions(ctx context.Context, userID int64) ([]GetUserChannelPermissionsRow, error)
	GetUserDMChannelIDs(ctx context.Context, userID int64) ([]int64, error)
	// A DM row carries no recipient any more: dm_participants holds N users, so
	// "the other one" is only well defined for a two-person DM. The participant
	// set comes from GetDMParticipantsForUser below, one extra query for the whole
	// list rather than one per channel, and the Go layer stitches them together.
	GetUserDMChannels(ctx context.Context, userID int64) ([]GetUserDMChannelsRow, error)
	GetUserSessions(ctx context.Context, userID int64) ([]Session, error)
	GetUserStorage(ctx context.Context, userID int64) (int64, error)
	GetUserVoiceState(ctx context.Context, userID int64) (GetUserVoiceStateRow, error)
	GetUserWithRole(ctx context.Context, id int64) (GetUserWithRoleRow, error)
	// The one indexed lookup permissions.Checker / service.PermissionService.Subject
	// run, uncached, to fill Subject.TimedOut.
	HasActiveTimeout(ctx context.Context, targetID int64) (int64, error)
	// public_id is generated in Go (crypto/rand) before this runs, the same
	// shape reports.public_id uses. A violation of UNIQUE(action_id) here is the
	// race-proof half of decision 8: two simultaneous appeals against the same
	// action both reach this INSERT, and the loser's violates the constraint.
	InsertAppeal(ctx context.Context, arg InsertAppealParams) (int64, error)
	// Erasure jobs (migration 037, B4-9): the durable file half of an account
	// erasure. The row is written inside the erasure transaction with the
	// stored_as names of every file the subject owned; the runner removes them
	// after commit and marks the job done, retrying from startup and the
	// maintenance tick until it is.
	InsertErasureJob(ctx context.Context, arg InsertErasureJobParams) (int64, error)
	// moderation_actions is the B5-9 moderator-action ledger (migration 049):
	// every warning, timeout, kick, ban and removal writes a row here. Keep
	// this file ASCII-only: sqlc v1.30 truncates the next query by the
	// byte/rune difference of any multi-byte character.
	// The rank guard (actor strictly outranks target, re-read live) runs in Go
	// immediately before this insert, inside the same transaction as the
	// caller's effect (Server/db/moderation_action_queries.go,
	// recordModerationAction) -- not here, so this statement is a plain insert.
	InsertModerationAction(ctx context.Context, arg InsertModerationActionParams) (int64, error)
	InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error
	// reports is the B5-8 report intake, queue and evidence snapshot (migration
	// 048). Keep this file ASCII-only: sqlc v1.30 truncates the next query by
	// the byte/rune difference of any multi-byte character.
	// public_id is generated in Go (crypto/rand) before this runs; the UNIQUE
	// constraint on it is not expected to ever fire. idx_reports_active_unique
	// (migration 048) is the constraint expected to fire here on a race: two
	// simultaneous filings of the same (reporter, target) both reach this
	// INSERT, and the loser's violates that partial unique index.
	// Re-validated inside the transaction (Codex review, P1-4 widened): the
	// evidence snapshot is built and the reporter/subject resolved before the
	// transaction opens, so an erasure landing between that resolution and this
	// INSERT must not restore a since-erased reporter or subject id -- the
	// INSERT ... SELECT ... WHERE EXISTS guard turns that race into zero rows
	// (mapped to db.ErrNotFound) rather than a row naming an erased account.
	// subject_id = 0 is a valid, principal-less target (an attachment with no
	// resolvable uploader) and skips the EXISTS check for it.
	InsertReport(ctx context.Context, arg InsertReportParams) (int64, error)
	// report_events is this feature's own immutable history, never the shared
	// audit_log (second Codex review): detail is the state or outcome word
	// only, never free text.
	InsertReportEvent(ctx context.Context, arg InsertReportEventParams) error
	// Guarded (Codex review, P1-4 widened): an evidence row's author erased
	// between the snapshot's capture and this transaction's commit must not
	// land -- the row is silently dropped (0 = a valid author-less context row,
	// e.g. a system message, and skips the check).
	InsertReportEvidence(ctx context.Context, arg InsertReportEvidenceParams) error
	// INSERT ... SELECT ... WHERE EXISTS, not a bare INSERT: a moderator erased
	// between requirePerm and this write must not land as a note's author, and
	// (Codex review) the report must still be open/assigned -- a note added
	// between GetReport's read and this write, on a report a concurrent Close
	// just closed, must not land either. Both guards are in the one INSERT's
	// WHERE clause, so there is no read-then-write gap between them. Zero rows
	// affected means the caller answers 409, for either cause.
	InsertReportNote(ctx context.Context, arg InsertReportNoteParams) (int64, error)
	InsertSession(ctx context.Context, arg InsertSessionParams) (sql.Result, error)
	InsertUsedTOTPCode(ctx context.Context, arg InsertUsedTOTPCodeParams) (sql.Result, error)
	InstallPlugin(ctx context.Context, arg InstallPluginParams) (sql.Result, error)
	IsBlocked(ctx context.Context, arg IsBlockedParams) (int64, error)
	IsDMParticipant(ctx context.Context, arg IsDMParticipantParams) (int64, error)
	IsEitherBlocked(ctx context.Context, arg IsEitherBlockedParams) (int64, error)
	IsGroupDM(ctx context.Context, id int64) (int64, error)
	// server_muted / server_deafened are deliberately absent from both upserts'
	// reset lists: a moderator-imposed mute must survive a channel switch, which
	// reaches the ON CONFLICT branch. It is scoped to the voice session:
	// leaving voice deletes the row, so a rejoin starts clean.
	JoinVoiceChannel(ctx context.Context, arg JoinVoiceChannelParams) error
	// The channel-wide row count excludes the joining user's own existing row
	// (if any), mirroring the OC-0081 fix on EnableCameraIfUnderLimit /
	// EnableScreenshareIfUnderLimit below. Without this, a user who already
	// holds a row on the target channel (e.g. retrying a join after a failed
	// channel-switch left their old row in place) gets counted against their
	// own capacity slot, so a full channel refuses an upsert that would only
	// replace the row already there (OC-0255).
	JoinVoiceChannelIfCapacity(ctx context.Context, arg JoinVoiceChannelIfCapacityParams) (sql.Result, error)
	LeaveVoiceChannel(ctx context.Context, userID int64) error
	LeaveVoiceChannelIfMatch(ctx context.Context, arg LeaveVoiceChannelIfMatchParams) (sql.Result, error)
	// Lifts EVERY currently-active timeout row for target_id in one statement
	// (P2-9), guarded on EXISTS(users) for the lifting actor same as before --
	// rather than the single newest row LiftTimeout used to touch.
	LiftAllActiveTimeouts(ctx context.Context, arg LiftAllActiveTimeoutsParams) (int64, error)
	// Admin/CLI listing. Never selects token_hash (unrecoverable; only the raw
	// token shown at creation is usable).
	ListAPITokens(ctx context.Context) ([]ListAPITokensRow, error)
	// Every currently-active timeout row for target_id -- normally at most one
	// after SupersedeActiveTimeouts (see its comment), but LiftTimeout acts on
	// all of them defensively (P2-9). voice_muted tells LiftTimeout whether any
	// of them actually applied the voice half (P1-4).
	ListActiveTimeouts(ctx context.Context, targetID int64) ([]ListActiveTimeoutsRow, error)
	ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]ListAllUsersRow, error)
	// The moderation queue view for one state ("open", "assigned", "decided" --
	// decided groups both terminal decision states together, mirroring reports'
	// "closed" grouping resolved/dismissed).
	ListAppealsByState(ctx context.Context, state string) ([]ListAppealsByStateRow, error)
	ListAppealsDecided(ctx context.Context) ([]ListAppealsDecidedRow, error)
	// The appellant's own view: their appeals, newest first.
	ListAppealsMine(ctx context.Context, appellantID int64) ([]ListAppealsMineRow, error)
	// The default queue view (state omitted): open and assigned together,
	// mirroring reports' ListReportsOpenOrAssigned.
	ListAppealsOpenOrAssigned(ctx context.Context) ([]ListAppealsOpenOrAssignedRow, error)
	ListBlockedUsers(ctx context.Context, blockerID int64) ([]int64, error)
	ListBlockersOfUser(ctx context.Context, blockedID int64) ([]int64, error)
	ListChannels(ctx context.Context) ([]ListChannelsRow, error)
	ListEmoji(ctx context.Context) ([]ListEmojiRow, error)
	ListInvites(ctx context.Context) ([]ListInvitesRow, error)
	// The ready payload's member roster. docs/protocol.md documents members[] as
	// "All registered users", so this must not silently truncate: the previous
	// LIMIT 1000 dropped every member past the first thousand with no has_more
	// signal, leaving those users unrenderable and unmentionable on the client
	// with nothing to indicate the list was incomplete.
	ListMembers(ctx context.Context) ([]ListMembersRow, error)
	// The queue detail's "actions taken" list.
	ListModerationActionsForReport(ctx context.Context, reportID *int64) ([]ListModerationActionsForReportRow, error)
	// GET /api/v1/moderation/users/{id}/actions: the full ledger for one user,
	// newest first.
	ListModerationActionsForTarget(ctx context.Context, targetID int64) ([]ListModerationActionsForTargetRow, error)
	ListPendingUsers(ctx context.Context, arg ListPendingUsersParams) ([]ListPendingUsersRow, error)
	ListPlugins(ctx context.Context) ([]Plugin, error)
	ListReportEvents(ctx context.Context, reportID int64) ([]ReportEvent, error)
	ListReportEvidence(ctx context.Context, reportID int64) ([]ReportEvidence, error)
	ListReportNotes(ctx context.Context, reportID int64) ([]ReportNote, error)
	// Either concrete queue state, taken alone ("open" or "assigned").
	ListReportsByState(ctx context.Context, state string) ([]ListReportsByStateRow, error)
	// state=closed groups every terminal state, including the erasure-forced one.
	ListReportsClosed(ctx context.Context) ([]ListReportsClosedRow, error)
	// The reporter's own view: never the assignee, never the notes.
	ListReportsMine(ctx context.Context, reporterID int64) ([]ListReportsMineRow, error)
	// The default queue view: open and assigned together.
	ListReportsOpenOrAssigned(ctx context.Context) ([]ListReportsOpenOrAssignedRow, error)
	// Highest rank first. Positions are only "unique enough": reorder normalizes
	// them, but creating a role inserts just below the actor and may tie with an
	// existing role, so id is a tiebreaker. Without it SQLite may return tied rows
	// in any order, and the admin panel derives its reorder payload from this
	// order, so a single move-up would silently shuffle the tied roles.
	// NOTE: keep comments in this file ASCII-only. sqlc mixes byte and rune
	// offsets when stripping them, so a non-ASCII character here truncates the
	// generated SQL of THIS and every following query by the byte/rune delta.
	ListRoles(ctx context.Context) ([]Role, error)
	// ready's notices slot: every warning issued to userID that has not yet
	// been acknowledged.
	ListUnacknowledgedWarnings(ctx context.Context, targetID int64) ([]ListUnacknowledgedWarningsRow, error)
	ListUnfinishedErasureJobs(ctx context.Context) ([]ListUnfinishedErasureJobsRow, error)
	ListUnusedRecoveryCodes(ctx context.Context, userID int64) ([]ListUnusedRecoveryCodesRow, error)
	ListUserIDsByRole(ctx context.Context, roleID int64) ([]int64, error)
	ListUserSessions(ctx context.Context, userID int64) ([]Session, error)
	ListUserStorageIDs(ctx context.Context) ([]int64, error)
	LoadActiveLockouts(ctx context.Context, expiresAt string) ([]RateLockout, error)
	LogAudit(ctx context.Context, arg LogAuditParams) error
	LogAuditEntry(ctx context.Context, arg LogAuditEntryParams) error
	// Mark-read that computes its own watermark inside the writer statement.
	// Passing a snapshot read moments earlier is what destroyed a mention raised
	// during the round trip (OC-0323): the clear zeroed mention_count while
	// last_message_id still pointed behind the mentioning message, so the badge was
	// gone and nothing ever recomputed it. Computing MAX(id) here means every
	// message committed before this statement is covered by last_message_id, and
	// every message committed after it finds IncrementMentionCounts' own
	// `last_message_id < msgID` guard true, so its mention survives.
	MarkChannelReadAtLatest(ctx context.Context, arg MarkChannelReadAtLatestParams) error
	MarkErasureJobReplayPurged(ctx context.Context, id int64) error
	MarkRecoveryCodeUsed(ctx context.Context, arg MarkRecoveryCodeUsedParams) (sql.Result, error)
	// The new-login signal (B4-7): listing the account's sessions from one
	// device acknowledges every other session's login. The caller's own row is
	// left alone so a device never acknowledges itself.
	MarkSessionsSeen(ctx context.Context, arg MarkSessionsSeenParams) (sql.Result, error)
	// Disconnect bookkeeping. It clears only 'online', which is the one status
	// that means "has a live session"; idle, dnd and invisible are choices the
	// user made and are what the next connect reads instead of stamping online
	// (db.ConnectStatus). A stale choice never renders as "present" because the
	// read path treats a member with no live connection as offline regardless.
	MarkUserDisconnected(ctx context.Context, id int64) error
	OpenDM(ctx context.Context, arg OpenDMParams) (int64, error)
	// seq is supplied by the hub so the row seq matches the wrapped-payload seq.
	PersistEvent(ctx context.Context, arg PersistEventParams) error
	PluginKVDelete(ctx context.Context, arg PluginKVDeleteParams) error
	PluginKVGet(ctx context.Context, arg PluginKVGetParams) ([]byte, error)
	PluginKVSet(ctx context.Context, arg PluginKVSetParams) error
	PruneEventsOlderThan(ctx context.Context, createdAt time.Time) (int64, error)
	PruneReportDetailOlderThan(ctx context.Context, closedAt *string) (int64, error)
	PruneReportEvidenceOlderThan(ctx context.Context, closedAt *string) (int64, error)
	PruneReportNotesOlderThan(ctx context.Context, closedAt *string) (int64, error)
	RecordErasureJobAttempt(ctx context.Context, arg RecordErasureJobAttemptParams) error
	// The truth: every counted byte this user holds in the store has an
	// attachments row that names it (avatars are attachments). Emoji are a
	// bounded exclusion, see migration 044.
	RecountUserStorage(ctx context.Context, userID int64) error
	// MAX(0, ...) rather than a bare subtraction: a recount may already have
	// lowered the row below the charge being released, and the CHECK
	// constraint would otherwise turn the release into an error.
	ReleaseUserStorage(ctx context.Context, arg ReleaseUserStorageParams) error
	RemoveDMParticipant(ctx context.Context, arg RemoveDMParticipantParams) error
	RemoveReaction(ctx context.Context, arg RemoveReactionParams) (sql.Result, error)
	// Startup reset: nothing is connected yet, so every 'online' is a leftover
	// from the previous process. Chosen statuses survive for the same reason they
	// survive a disconnect.
	ResetAllUserStatuses(ctx context.Context) error
	// The maintenance-tick retention sweep, kept only as the pre-appeals
	// fallback RetireModerationActions falls back to if the appeals table is
	// somehow absent (Server/db/moderation_action_queries.go) -- in ordinary
	// operation migration 050 has always run by the time this executes, so
	// RetireRetiredCandidatesExcludingAppealed (appeals.sql) is the query that
	// actually runs. Warnings retire moderation.action_retention_days after
	// acknowledged_at; timeouts the same number of days after expires_at, or
	// after lifted_at when lifted early. Ban, kick and removal rows are never
	// touched here.
	RetireRetiredCandidates(ctx context.Context, cutoff *string) (int64, error)
	// B5-10's completion of the // B5-10: comment RetireModerationActions left
	// in Server/db/moderation_action_queries.go: the same warning/timeout
	// retention sweep as RetireRetiredCandidates (moderation_actions.sql), but
	// excluding any id an appeals row references -- decision 8's UNIQUE(action_id)
	// memory must not be swept out from under a decided appeal, or a fresh
	// appeal against the same action could slip past the "one appeal per action,
	// ever" rule the row alone enforces.
	RetireRetiredCandidatesExcludingAppealed(ctx context.Context, cutoff *string) (int64, error)
	RevokeAPIToken(ctx context.Context, id int64) (sql.Result, error)
	RevokeAPITokenByLabel(ctx context.Context, label string) (sql.Result, error)
	RevokeInvite(ctx context.Context, code string) error
	SetChannelSlowMode(ctx context.Context, arg SetChannelSlowModeParams) error
	SetChannelVoiceMaxUsers(ctx context.Context, arg SetChannelVoiceMaxUsersParams) error
	SetDMChannelName(ctx context.Context, arg SetDMChannelNameParams) error
	SetMessagePinned(ctx context.Context, arg SetMessagePinnedParams) (sql.Result, error)
	SetRolePosition(ctx context.Context, arg SetRolePositionParams) error
	SetSetting(ctx context.Context, arg SetSettingParams) error
	// Records that this timeout row's voice half actually landed a mute
	// (P1-4/P3-14): called once, right after ApplyTimeoutMute reports success,
	// never reconsidered afterward.
	SetTimeoutVoiceMuted(ctx context.Context, id int64) error
	SoftDeleteMessage(ctx context.Context, id int64) (sql.Result, error)
	// On issuing a NEW timeout (P2-9, Codex review): lift every OTHER
	// still-active timeout row for the same target, in the same transaction as
	// the new row's insert, so a repeated timeout never leaves two overlapping
	// active rows for LiftTimeout to pick between -- the single-row
	// GetActiveTimeout this replaced used to silently orphan every row but the
	// newest. id excludes the row this same transaction just inserted, which
	// must stay active.
	SupersedeActiveTimeouts(ctx context.Context, arg SupersedeActiveTimeoutsParams) (int64, error)
	// The operator's storage figure on the metrics surface: every attachments
	// row, legacy rows with a NULL uploader_id included, so it is a total and
	// not a sum of counters.
	TotalAttachmentBytes(ctx context.Context) (int64, error)
	TouchAPIToken(ctx context.Context, tokenHash string) error
	TouchSession(ctx context.Context, token string) error
	UnbanUser(ctx context.Context, id int64) error
	UnblockUser(ctx context.Context, arg UnblockUserParams) error
	UninstallPlugin(ctx context.Context, id int64) error
	// Same, for assignee_id: no token column of its own (mirrors reports'
	// assignee_id and moderation_actions.lifted_by), so an erased assignee's id
	// simply goes to 0.
	UnlinkAppealsByAssignee(ctx context.Context, assigneeID int64) error
	// Erasure's actor-token unlink (mirrors UnlinkModerationActionsByActor): an
	// erased moderator's decisions keep their row, decision and order, but the
	// deciding id goes to 0 and the token takes its place.
	UnlinkAppealsByDecider(ctx context.Context, arg UnlinkAppealsByDeciderParams) error
	// Erasure's actor-token unlink (mirrors erasureUnlinkReports): an erased
	// moderator's actions keep their row, action, time and order, but the
	// actor id goes to 0 and the token takes its place.
	UnlinkModerationActionsByActor(ctx context.Context, arg UnlinkModerationActionsByActorParams) error
	// Same, for the lifted_by column: no token column of its own (mirrors the
	// reports assignee_id and audit_log's other bare actor columns), so an
	// erased lifter's id simply goes to 0.
	UnlinkModerationActionsByLifter(ctx context.Context, liftedBy int64) error
	UpdateChannel(ctx context.Context, arg UpdateChannelParams) error
	// Marking a channel read also clears its mention badge: channel_focus is the
	// only caller, and a focused channel has no outstanding mentions by definition.
	UpdateReadState(ctx context.Context, arg UpdateReadStateParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	// Separate from UpdateUserProfile because a custom status arrives over the
	// WebSocket presence path, not the REST profile PATCH, and must not be able to
	// clobber the username/avatar of a profile edit racing it.
	UpdateUserCustomStatus(ctx context.Context, arg UpdateUserCustomStatusParams) error
	UpdateUserIdentityKey(ctx context.Context, arg UpdateUserIdentityKeyParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (sql.Result, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpdateUserTOTPSecret(ctx context.Context, arg UpdateUserTOTPSecretParams) error
	UpdateVoiceCamera(ctx context.Context, arg UpdateVoiceCameraParams) error
	UpdateVoiceDeafen(ctx context.Context, arg UpdateVoiceDeafenParams) error
	UpdateVoiceMute(ctx context.Context, arg UpdateVoiceMuteParams) error
	UpdateVoiceScreenshare(ctx context.Context, arg UpdateVoiceScreenshareParams) error
	UpsertChannelPermission(ctx context.Context, arg UpsertChannelPermissionParams) error
	UpsertChannelUserPermission(ctx context.Context, arg UpsertChannelUserPermissionParams) error
	UpsertLockout(ctx context.Context, arg UpsertLockoutParams) error
	// Second-factor state (migration 032, B4-3). ASCII only in this file: sqlc
	// v1.30.0 miscounts multi-byte characters and truncates the next query.
	UpsertPartialAuthChallenge(ctx context.Context, arg UpsertPartialAuthChallengeParams) error
	UpsertPendingTOTPEnrollment(ctx context.Context, arg UpsertPendingTOTPEnrollmentParams) error
	// Owner-issued recovery credentials (B4-6): one per account, replaced on
	// issuance, deleted by the redemption that consumes it. The verifier is an
	// argon2id PHC string and no query returns anything else about the secret.
	UpsertRecoveryAssist(ctx context.Context, arg UpsertRecoveryAssistParams) error
	// Recovery kits (B4-5): one verifier per account, replaced on enrolment,
	// spent by a successful recovery. The verifier is an argon2id PHC string;
	// no query ever returns anything else about the kit.
	UpsertRecoveryKit(ctx context.Context, arg UpsertRecoveryKitParams) error
	UseInviteAtomic(ctx context.Context, code string) (sql.Result, error)
	UserCount(ctx context.Context) (int64, error)
	// The appellant only, guarded to open/assigned states.
	WithdrawAppeal(ctx context.Context, arg WithdrawAppealParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
