// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recoveryassist.sql

package dbgen

import (
	"context"
	"database/sql"
)

const consumeRecoveryAssist = `-- name: ConsumeRecoveryAssist :execresult
DELETE FROM recovery_assists WHERE user_id = ? AND expires_at > ?
`

type ConsumeRecoveryAssistParams struct {
	UserID    int64  `json:"userId"`
	ExpiresAt string `json:"expiresAt"`
}

// The consume deletes only a live credential, so the affected row count is
// what tells two concurrent redemptions, and an expired credential, apart.
func (q *Queries) ConsumeRecoveryAssist(ctx context.Context, arg ConsumeRecoveryAssistParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, consumeRecoveryAssist, arg.UserID, arg.ExpiresAt)
}

const deleteRecoveryAssist = `-- name: DeleteRecoveryAssist :exec
DELETE FROM recovery_assists WHERE user_id = ?
`

func (q *Queries) DeleteRecoveryAssist(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecoveryAssist, userID)
	return err
}

const getRecoveryAssist = `-- name: GetRecoveryAssist :one
SELECT user_id, verifier, issued_by, verification, created_at, expires_at
FROM recovery_assists WHERE user_id = ?
`

func (q *Queries) GetRecoveryAssist(ctx context.Context, userID int64) (RecoveryAssist, error) {
	row := q.db.QueryRowContext(ctx, getRecoveryAssist, userID)
	var i RecoveryAssist
	err := row.Scan(
		&i.UserID,
		&i.Verifier,
		&i.IssuedBy,
		&i.Verification,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const upsertRecoveryAssist = `-- name: UpsertRecoveryAssist :exec

INSERT INTO recovery_assists (user_id, verifier, issued_by, verification, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET verifier = excluded.verifier,
                                   issued_by = excluded.issued_by,
                                   verification = excluded.verification,
                                   created_at = excluded.created_at,
                                   expires_at = excluded.expires_at
`

type UpsertRecoveryAssistParams struct {
	UserID       int64  `json:"userId"`
	Verifier     string `json:"verifier"`
	IssuedBy     int64  `json:"issuedBy"`
	Verification string `json:"verification"`
	CreatedAt    string `json:"createdAt"`
	ExpiresAt    string `json:"expiresAt"`
}

// Owner-issued recovery credentials (B4-6): one per account, replaced on
// issuance, deleted by the redemption that consumes it. The verifier is an
// argon2id PHC string and no query returns anything else about the secret.
func (q *Queries) UpsertRecoveryAssist(ctx context.Context, arg UpsertRecoveryAssistParams) error {
	_, err := q.db.ExecContext(ctx, upsertRecoveryAssist,
		arg.UserID,
		arg.Verifier,
		arg.IssuedBy,
		arg.Verification,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}
