// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_storage.sql

package dbgen

import (
	"context"
)

const chargeUserStorage = `-- name: ChargeUserStorage :execrows
UPDATE user_storage
   SET bytes_used = bytes_used + ?1
 WHERE user_id = ?2
   AND bytes_used + ?1 <= ?3
`

type ChargeUserStorageParams struct {
	Bytes  int64 `json:"bytes"`
	UserID int64 `json:"userId"`
	Quota  int64 `json:"quota"`
}

// The quota guard and the increment are one statement, so exactly one of
// N concurrent uploads racing the last byte is admitted: SQLite serialises
// writers and the WHERE is evaluated against the row the UPDATE sees.
// Rows affected = admitted.
func (q *Queries) ChargeUserStorage(ctx context.Context, arg ChargeUserStorageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, chargeUserStorage, arg.Bytes, arg.UserID, arg.Quota)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const chargeUserStorageUnbounded = `-- name: ChargeUserStorageUnbounded :exec
UPDATE user_storage SET bytes_used = bytes_used + ? WHERE user_id = ?
`

type ChargeUserStorageUnboundedParams struct {
	BytesUsed int64 `json:"bytesUsed"`
	UserID    int64 `json:"userId"`
}

// The unlimited-quota form: the counter is maintained whether or not a
// quota is set, so turning one on later starts from a live number.
func (q *Queries) ChargeUserStorageUnbounded(ctx context.Context, arg ChargeUserStorageUnboundedParams) error {
	_, err := q.db.ExecContext(ctx, chargeUserStorageUnbounded, arg.BytesUsed, arg.UserID)
	return err
}

const ensureUserStorage = `-- name: EnsureUserStorage :exec

INSERT OR IGNORE INTO user_storage (user_id, bytes_used) VALUES (?, 0)
`

// user_storage is the per-user upload byte counter (migration 044, B5-2).
// Keep this file ASCII-only: sqlc v1.30 truncates the next query by the
// byte/rune difference of any multi-byte character.
func (q *Queries) EnsureUserStorage(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, ensureUserStorage, userID)
	return err
}

const getUserStorage = `-- name: GetUserStorage :one
SELECT bytes_used FROM user_storage WHERE user_id = ?
`

func (q *Queries) GetUserStorage(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserStorage, userID)
	var bytes_used int64
	err := row.Scan(&bytes_used)
	return bytes_used, err
}

const listUserStorageIDs = `-- name: ListUserStorageIDs :many
SELECT user_id FROM user_storage ORDER BY user_id
`

func (q *Queries) ListUserStorageIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listUserStorageIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recountUserStorage = `-- name: RecountUserStorage :exec
UPDATE user_storage
   SET bytes_used = (SELECT COALESCE(SUM(size), 0) FROM attachments WHERE uploader_id = user_storage.user_id)
 WHERE user_id = ?
`

// The truth: every counted byte this user holds in the store has an
// attachments row that names it (avatars are attachments). Emoji are a
// bounded exclusion, see migration 044.
func (q *Queries) RecountUserStorage(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, recountUserStorage, userID)
	return err
}

const releaseUserStorage = `-- name: ReleaseUserStorage :exec
UPDATE user_storage SET bytes_used = MAX(0, bytes_used - ?1) WHERE user_id = ?2
`

type ReleaseUserStorageParams struct {
	Bytes  int64 `json:"bytes"`
	UserID int64 `json:"userId"`
}

// MAX(0, ...) rather than a bare subtraction: a recount may already have
// lowered the row below the charge being released, and the CHECK
// constraint would otherwise turn the release into an error.
func (q *Queries) ReleaseUserStorage(ctx context.Context, arg ReleaseUserStorageParams) error {
	_, err := q.db.ExecContext(ctx, releaseUserStorage, arg.Bytes, arg.UserID)
	return err
}

const totalAttachmentBytes = `-- name: TotalAttachmentBytes :one
SELECT CAST(COALESCE(SUM(size), 0) AS INTEGER) AS total FROM attachments
`

// The operator's storage figure on the metrics surface: every attachments
// row, legacy rows with a NULL uploader_id included, so it is a total and
// not a sum of counters.
func (q *Queries) TotalAttachmentBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalAttachmentBytes)
	var total int64
	err := row.Scan(&total)
	return total, err
}
