/**
 * Emoji keyword index for search (B9-19). Maps emoji character → searchable
 * keywords. This is search-index data, not UI copy: the same table is why
 * `message-list/syntax-highlight.ts` is excluded from the UI-string scan.
 *
 * Shared because the composer's `:` autocomplete searches the same list the
 * picker does — two independently-maintained name tables would mean typing
 * `:fire` and searching "fire" disagreeing about what exists.
 */
export const EMOJI_NAMES: Readonly<Record<string, string>> = {
  "😀": "grinning face happy smile",
  "😃": "smiley face happy smile",
  "😄": "smile happy grin",
  "😁": "beaming grin teeth smile",
  "😆": "laughing happy squint smile",
  "😅": "sweat smile nervous",
  "🤣": "rofl laughing rolling floor",
  "😂": "joy tears laughing cry happy",
  "🙂": "slightly smiling",
  "😊": "blush happy smile shy",
  "😇": "innocent angel halo",
  "🥰": "love hearts face smiling",
  "😍": "heart eyes love",
  "🤩": "star struck excited",
  "😘": "kiss blowing wink",
  "😗": "kissing face",
  "😋": "yummy delicious tongue food",
  "😛": "tongue out",
  "😜": "wink tongue playful",
  "🤪": "zany crazy wild",
  "😝": "squinting tongue",
  "🤑": "money face rich dollar",
  "🤗": "hugging hug hands",
  "🤭": "hand over mouth oops giggle",
  "🤫": "shushing quiet secret shh",
  "🤔": "thinking hmm wonder",
  "🤐": "zipper mouth shut secret",
  "🤨": "raised eyebrow skeptical",
  "😐": "neutral face blank",
  "😑": "expressionless blank",
  "😶": "no mouth silent mute",
  "😏": "smirk smug",
  "😒": "unamused bored annoyed",
  "🙄": "eye roll whatever",
  "😬": "grimace awkward teeth",
  "🤥": "lying pinocchio nose",
  "😌": "relieved calm peaceful",
  "😔": "pensive sad thoughtful",
  "😪": "sleepy tired",
  "🤤": "drooling hungry",
  "😴": "sleeping zzz tired",
  "😷": "mask sick medical face",
  "🤒": "thermometer sick fever",
  "🤕": "bandage hurt injured",
  "🤢": "nauseous sick green",
  "🤮": "vomiting throw up sick",
  "🥵": "hot face overheated",
  "🥶": "cold face freezing",
  "🥴": "woozy drunk dizzy",
  "😵": "dizzy spiral knocked out",
  "🤯": "mind blown exploding head",
  "🤠": "cowboy hat yeehaw",
  "🥳": "party celebration birthday",
  "😎": "sunglasses cool",
  "🤓": "nerd glasses geek",
  "🧐": "monocle detective inspect",
  "😕": "confused puzzled",
  "😟": "worried concerned",
  "🙁": "frowning sad",
  "😮": "open mouth surprised",
  "😲": "astonished shocked wow",
  "😳": "flushed embarrassed",
  "🥺": "pleading puppy eyes please",
  "😢": "crying sad tear",
  "😭": "sobbing crying loud",
  "😤": "steam nose angry huffing",
  "😠": "angry mad",
  "😡": "rage furious red",
  "🤬": "cursing swearing symbols angry",
  "💀": "skull dead death skeleton",
  "👋": "wave hello hi bye hand",
  "🤚": "raised back hand",
  "🖐": "hand fingers splayed five",
  "✋": "raised hand stop high five",
  "🖖": "vulcan spock",
  "👌": "ok okay perfect",
  "🤌": "pinched fingers italian",
  "🤏": "pinching small little",
  "✌️": "peace victory two",
  "🤞": "crossed fingers luck hope",
  "🤟": "love you gesture rock",
  "🤘": "rock on horns metal",
  "🤙": "call me hang loose shaka",
  "👈": "pointing left",
  "👉": "pointing right",
  "👆": "pointing up",
  "👇": "pointing down",
  "☝️": "index pointing up",
  "👍": "thumbs up like good yes",
  "👎": "thumbs down dislike bad no",
  "✊": "raised fist power",
  "👊": "fist bump punch",
  "🤛": "left fist bump",
  "🤜": "right fist bump",
  "👏": "clap applause bravo",
  "🙌": "raising hands hooray celebrate",
  "👐": "open hands jazz",
  "🤲": "palms up together prayer",
  "🤝": "handshake deal agreement",
  "🙏": "pray thanks please folded hands",
  "🐶": "dog puppy pet",
  "🐱": "cat kitten pet",
  "🐭": "mouse rat",
  "🐹": "hamster",
  "🐰": "rabbit bunny",
  "🦊": "fox",
  "🐻": "bear",
  "🐼": "panda bear",
  "🐨": "koala",
  "🐯": "tiger",
  "🦁": "lion king",
  "🐮": "cow moo",
  "🐷": "pig oink",
  "🐸": "frog toad",
  "🐵": "monkey face",
  "🐔": "chicken hen",
  "🐧": "penguin",
  "🐦": "bird",
  "🐤": "chick baby bird",
  "🦄": "unicorn magic",
  "🌸": "cherry blossom flower pink",
  "🌹": "rose flower red",
  "🌺": "hibiscus flower",
  "🌻": "sunflower",
  "🌼": "blossom flower",
  "🌷": "tulip flower",
  "🌱": "seedling sprout plant",
  "🌲": "evergreen tree pine",
  "🌳": "tree deciduous",
  "🍀": "four leaf clover luck",
  "🍎": "red apple fruit",
  "🍊": "orange tangerine fruit",
  "🍋": "lemon fruit",
  "🍌": "banana fruit",
  "🍉": "watermelon fruit",
  "🍇": "grapes fruit",
  "🍓": "strawberry fruit",
  "🍒": "cherries fruit",
  "🍑": "peach fruit butt",
  "🍍": "pineapple fruit",
  "🥝": "kiwi fruit",
  "🍔": "hamburger burger food",
  "🍟": "fries french food",
  "🍕": "pizza food slice",
  "🌭": "hot dog food",
  "🍿": "popcorn snack movie",
  "🧀": "cheese wedge",
  "🥚": "egg",
  "🍳": "cooking fried egg",
  "🥓": "bacon",
  "☕": "coffee hot drink",
  "🍵": "tea hot drink",
  "🍺": "beer mug drink",
  "🍻": "clinking beers cheers drink",
  "🥂": "champagne toast celebrate drink",
  "🍷": "wine glass drink red",
  "🍸": "cocktail martini drink",
  "🍹": "tropical drink",
  "🍾": "bottle popping champagne celebrate",
  "🧁": "cupcake dessert sweet",
  "⚽": "soccer football ball sport",
  "🏀": "basketball ball sport",
  "🏈": "football american sport",
  "⚾": "baseball ball sport",
  "🎾": "tennis ball sport",
  "🎮": "video game controller gaming",
  "🎲": "dice game random",
  "🎯": "bullseye target dart",
  "🎵": "music note",
  "🎶": "music notes",
  "💡": "light bulb idea",
  "🔥": "fire hot flame lit",
  "⭐": "star yellow",
  "🌟": "glowing star sparkle",
  "💫": "dizzy star shooting",
  "✨": "sparkles magic shine",
  "💥": "boom collision crash",
  "❤️": "red heart love",
  "🧡": "orange heart love",
  "💛": "yellow heart love",
  "💚": "green heart love",
  "💙": "blue heart love",
  "💜": "purple heart love",
  "🖤": "black heart dark love",
  "🤍": "white heart love",
  "💯": "hundred percent perfect score",
  "💢": "anger symbol mad",
  "💬": "speech bubble chat talk",
  "👁‍🗨": "eye speech bubble witness",
  "🗨": "speech balloon left",
  "✅": "check mark yes done complete",
  "❌": "cross mark no wrong cancel",
  "❓": "question mark red",
  "❗": "exclamation mark red alert",
  "‼️": "double exclamation",
  "⁉️": "exclamation question",
  "💤": "sleeping zzz tired",
  "💮": "white flower",
  "♻️": "recycle green environment",
  "🔰": "beginner new japanese",
  "⚠️": "warning caution alert",
  "🚫": "prohibited forbidden no",
  "🔴": "red circle",
  "🟠": "orange circle",
  "🟡": "yellow circle",
  "🟢": "green circle",
  "🔵": "blue circle",
  "🟣": "purple circle",
  "⚫": "black circle",
  "⚪": "white circle",
};
