package db

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/J3vb/OwnCord/Server/db/dbgen"
)

// Appeal is a row of the appeals table (migration 050, B5-10). DecidedByToken
// is filled by erasure (the bare-id-plus-token pattern, migrations 038/041/
// 048/049): a zero id plus a non-empty token means the deciding moderator
// erased their account. PublicID is the only identifier ever exposed outside
// the server, the same shape reports.PublicID uses (Codex review deviation
// from the HP-5 draft) — appeals are filed in sequence server-side, so a
// moderator who can see appeals 1 and 3 but never 2 could otherwise infer
// appeal 2 concerns someone specific.
type Appeal struct {
	ID             int64
	PublicID       string
	ActionID       int64
	AppellantID    int64
	Body           string
	State          string
	AssigneeID     int64
	DecidedBy      int64
	DecidedByToken string
	DecisionNote   string
	CreatedAt      string
	DecidedAt      *string
}

// AppealSummary is one row of the appellant's own view (GET
// /api/v1/appeals/mine): id, action id, body, state, decision_note,
// created_at, decided_at — never the assignee, never who decided it.
type AppealSummary struct {
	ID           int64
	PublicID     string
	ActionID     int64
	Body         string
	State        string
	DecisionNote string
	CreatedAt    string
	DecidedAt    *string
}

// AppealQueueRow is one row of the moderation appeal queue.
type AppealQueueRow struct {
	ID           int64
	PublicID     string
	ActionID     int64
	AppellantID  int64
	Body         string
	State        string
	AssigneeID   int64
	DecidedBy    int64
	DecisionNote string
	CreatedAt    string
	DecidedAt    *string
}

func appealFromRow(r dbgen.Appeal) Appeal {
	return Appeal{
		ID: r.ID, PublicID: r.PublicID, ActionID: r.ActionID, AppellantID: r.AppellantID,
		Body: r.Body, State: r.State, AssigneeID: r.AssigneeID, DecidedBy: r.DecidedBy,
		DecidedByToken: strOrEmpty(r.DecidedByToken), DecisionNote: r.DecisionNote,
		CreatedAt: r.CreatedAt, DecidedAt: r.DecidedAt,
	}
}

// FindAppealForAction is the dedupe FAST-PATH check for decision 8's "one
// appeal per action, ever": returns 0, nil when no appeal exists yet. This
// alone is not race-proof — see the UNIQUE(action_id) constraint, which
// InsertAppeal's error mapping actually enforces.
func (d *DB) FindAppealForAction(ctx context.Context, actionID int64) (int64, error) {
	id, err := d.q.FindAppealForAction(ctx, actionID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return 0, nil
		}
		return 0, fmt.Errorf("FindAppealForAction: %w", err)
	}
	return id, nil
}

// InsertAppeal files a new appeal. publicID is generated by the caller
// (crypto/rand) before this runs. A violation of UNIQUE(action_id) surfaces
// as db.ErrConflict — the race-proof half of decision 8's "one appeal per
// action, ever".
func (d *DB) InsertAppeal(ctx context.Context, publicID string, actionID, appellantID int64, body string) (int64, error) {
	id, err := d.q.InsertAppeal(ctx, dbgen.InsertAppealParams{
		PublicID: publicID, ActionID: actionID, AppellantID: appellantID, Body: body,
	})
	if err != nil {
		if IsUniqueConstraintError(err) {
			return 0, fmt.Errorf("InsertAppeal: %w", ErrConflict)
		}
		return 0, fmt.Errorf("InsertAppeal: %w", err)
	}
	return id, nil
}

// GetAppeal returns one appeal by its internal id, or ErrNotFound.
func (d *DB) GetAppeal(ctx context.Context, id int64) (*Appeal, error) {
	r, err := d.q.GetAppealByID(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("GetAppeal: %w", err)
	}
	a := appealFromRow(r)
	return &a, nil
}

// GetAppealByPublicID resolves the opaque public id every route parameter
// and API response carries to the appeal row, or ErrNotFound.
func (d *DB) GetAppealByPublicID(ctx context.Context, publicID string) (*Appeal, error) {
	r, err := d.q.GetAppealByPublicID(ctx, publicID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("GetAppealByPublicID: %w", err)
	}
	a := appealFromRow(r)
	return &a, nil
}

// ListAppealsMine is the appellant's own view.
func (d *DB) ListAppealsMine(ctx context.Context, appellantID int64) ([]AppealSummary, error) {
	rows, err := d.q.ListAppealsMine(ctx, appellantID)
	if err != nil {
		return nil, fmt.Errorf("ListAppealsMine: %w", err)
	}
	out := make([]AppealSummary, 0, len(rows))
	for _, r := range rows {
		out = append(out, AppealSummary{
			ID: r.ID, PublicID: r.PublicID, ActionID: r.ActionID, Body: r.Body,
			State: r.State, DecisionNote: r.DecisionNote, CreatedAt: r.CreatedAt, DecidedAt: r.DecidedAt,
		})
	}
	return out, nil
}

// ListAppealsQueue returns the moderation queue view for one state filter:
// "open", "assigned", "decided" (both terminal decision states together,
// mirroring reports' "closed" grouping of resolved/dismissed), or "" for
// the default open+assigned view.
func (d *DB) ListAppealsQueue(ctx context.Context, state string) ([]AppealQueueRow, error) {
	build := func(rows []AppealQueueRow, err error) ([]AppealQueueRow, error) {
		if err != nil {
			return nil, fmt.Errorf("ListAppealsQueue: %w", err)
		}
		return rows, nil
	}
	switch state {
	case "decided":
		rows, err := d.q.ListAppealsDecided(ctx)
		out := make([]AppealQueueRow, 0, len(rows))
		for i := range rows {
			r := &rows[i]
			out = append(out, AppealQueueRow{
				ID: r.ID, PublicID: r.PublicID, ActionID: r.ActionID, AppellantID: r.AppellantID,
				Body: r.Body, State: r.State, AssigneeID: r.AssigneeID, DecidedBy: r.DecidedBy,
				DecisionNote: r.DecisionNote, CreatedAt: r.CreatedAt, DecidedAt: r.DecidedAt,
			})
		}
		return build(out, err)
	case "open", "assigned":
		rows, err := d.q.ListAppealsByState(ctx, state)
		out := make([]AppealQueueRow, 0, len(rows))
		for i := range rows {
			r := &rows[i]
			out = append(out, AppealQueueRow{
				ID: r.ID, PublicID: r.PublicID, ActionID: r.ActionID, AppellantID: r.AppellantID,
				Body: r.Body, State: r.State, AssigneeID: r.AssigneeID, DecidedBy: r.DecidedBy,
				DecisionNote: r.DecisionNote, CreatedAt: r.CreatedAt, DecidedAt: r.DecidedAt,
			})
		}
		return build(out, err)
	default:
		rows, err := d.q.ListAppealsOpenOrAssigned(ctx)
		out := make([]AppealQueueRow, 0, len(rows))
		for i := range rows {
			r := &rows[i]
			out = append(out, AppealQueueRow{
				ID: r.ID, PublicID: r.PublicID, ActionID: r.ActionID, AppellantID: r.AppellantID,
				Body: r.Body, State: r.State, AssigneeID: r.AssigneeID, DecidedBy: r.DecidedBy,
				DecisionNote: r.DecisionNote, CreatedAt: r.CreatedAt, DecidedAt: r.DecidedAt,
			})
		}
		return build(out, err)
	}
}

// AssignAppeal assigns assigneeID to appeal id, guarded on state,
// observedAssigneeID (optimistic concurrency, mirrors AssignReport) and
// EXISTS(users). Returns whether a row was affected; zero means CONFLICT.
func (d *DB) AssignAppeal(ctx context.Context, id, assigneeID, observedAssigneeID int64) (bool, error) {
	n, err := d.q.AssignAppeal(ctx, dbgen.AssignAppealParams{AssigneeID: assigneeID, ID: id, ObservedAssigneeID: observedAssigneeID})
	if err != nil {
		return false, fmt.Errorf("AssignAppeal: %w", err)
	}
	return n == 1, nil
}

// AssignAppealForced is the appeal queue's force-reassign path. See
// forceReassignGuarded (report_queries.go) for the shared mechanics.
func (d *DB) AssignAppealForced(ctx context.Context, id, assigneeID, observedAssigneeID, actorRolePosition int64) (bool, error) {
	return forceReassignGuarded(ctx, d.writer, observedAssigneeID, actorRolePosition, func(q *dbgen.Queries) (int64, error) {
		return q.AssignAppeal(ctx, dbgen.AssignAppealParams{AssigneeID: assigneeID, ID: id, ObservedAssigneeID: observedAssigneeID})
	})
}

// DecideAppeal records outcome ("upheld" or "overturned") against appeal id,
// guarded to open/assigned states and EXISTS(users) for the deciding
// moderator. Returns whether a row was affected; zero means CONFLICT.
func (d *DB) DecideAppeal(ctx context.Context, id int64, outcome string, decidedBy int64, note string) (bool, error) {
	n, err := d.q.DecideAppeal(ctx, dbgen.DecideAppealParams{
		NewState: outcome, DecidedBy: decidedBy, DecisionNote: note, ID: id,
	})
	if err != nil {
		return false, fmt.Errorf("DecideAppeal: %w", err)
	}
	return n == 1, nil
}

// WithdrawAppeal withdraws appeal id — the appellant only, guarded to
// open/assigned states. Returns whether a row was affected; zero means
// CONFLICT.
func (d *DB) WithdrawAppeal(ctx context.Context, id, appellantID int64) (bool, error) {
	n, err := d.q.WithdrawAppeal(ctx, dbgen.WithdrawAppealParams{ID: id, AppellantID: appellantID})
	if err != nil {
		return false, fmt.Errorf("WithdrawAppeal: %w", err)
	}
	return n == 1, nil
}

// CountEligibleModerators counts every user (other than excludeID) whose
// role holds MODERATE_MEMBERS or Administrator — decision 8's self-review
// escape: the acting moderator may decide their own appeal only when this
// count is zero. permBit/adminBit are passed in from the permissions
// package (not imported here, to keep db free of a permissions dependency).
func (d *DB) CountEligibleModerators(ctx context.Context, excludeID, permBit, adminBit int64) (int64, error) {
	n, err := d.q.CountUsersWithPermission(ctx, dbgen.CountUsersWithPermissionParams{
		ExcludeID: excludeID, PermBit: permBit, AdminBit: adminBit,
	})
	if err != nil {
		return 0, fmt.Errorf("CountEligibleModerators: %w", err)
	}
	return n, nil
}

// GetModerationAction returns one moderation_actions row by id, or
// ErrNotFound — B5-10's appeal submission and decision both need the
// appealed action's own kind, target and actor.
func (d *DB) GetModerationAction(ctx context.Context, id int64) (*ModerationAction, error) {
	r, err := d.q.GetModerationActionByID(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("GetModerationAction: %w", err)
	}
	a := moderationActionFromRow(moderationActionRow(r))
	return &a, nil
}
