package db

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/J3vb/OwnCord/Server/db/dbgen"
)

// Appeal is a row of the appeals table (migration 050, B5-10). DecidedByToken
// is filled by erasure (the bare-id-plus-token pattern, migrations 038/041/
// 048/049): a zero id plus a non-empty token means the deciding moderator
// erased their account. PublicID is the only identifier ever exposed outside
// the server, the same shape reports.PublicID uses (Codex review deviation
// from the HP-5 draft) — appeals are filed in sequence server-side, so a
// moderator who can see appeals 1 and 3 but never 2 could otherwise infer
// appeal 2 concerns someone specific.
type Appeal struct {
	ID             int64
	PublicID       string
	ActionID       int64
	AppellantID    int64
	Body           string
	State          string
	AssigneeID     int64
	DecidedBy      int64
	DecidedByToken string
	DecisionNote   string
	CreatedAt      string
	DecidedAt      *string
}

// AppealSummary is one row of the appellant's own view (GET
// /api/v1/appeals/mine): id, action id, body, state, decision_note,
// created_at, decided_at — never the assignee, never who decided it.
type AppealSummary struct {
	ID           int64
	PublicID     string
	ActionID     int64
	Body         string
	State        string
	DecisionNote string
	CreatedAt    string
	DecidedAt    *string
}

// AppealQueueRow is one row of the moderation appeal queue.
type AppealQueueRow struct {
	ID           int64
	PublicID     string
	ActionID     int64
	AppellantID  int64
	Body         string
	State        string
	AssigneeID   int64
	DecidedBy    int64
	DecisionNote string
	CreatedAt    string
	DecidedAt    *string
}

func appealFromRow(r dbgen.Appeal) Appeal {
	return Appeal{
		ID: r.ID, PublicID: r.PublicID, ActionID: r.ActionID, AppellantID: r.AppellantID,
		Body: r.Body, State: r.State, AssigneeID: r.AssigneeID, DecidedBy: r.DecidedBy,
		DecidedByToken: strOrEmpty(r.DecidedByToken), DecisionNote: r.DecisionNote,
		CreatedAt: r.CreatedAt, DecidedAt: r.DecidedAt,
	}
}

// FindAppealForAction is the dedupe FAST-PATH check for decision 8's "one
// appeal per action, ever": returns 0, nil when no appeal exists yet. This
// alone is not race-proof — see the UNIQUE(action_id) constraint, which
// InsertAppeal's error mapping actually enforces.
func (d *DB) FindAppealForAction(ctx context.Context, actionID int64) (int64, error) {
	id, err := d.q.FindAppealForAction(ctx, actionID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return 0, nil
		}
		return 0, fmt.Errorf("FindAppealForAction: %w", err)
	}
	return id, nil
}

// InsertAppeal files a new appeal. publicID is generated by the caller
// (crypto/rand) before this runs. A violation of UNIQUE(action_id) surfaces
// as db.ErrConflict — the race-proof half of decision 8's "one appeal per
// action, ever". N4 review: the INSERT's own WHERE EXISTS guard (the action
// still exists) turns an action erased between the caller's ownership
// lookup and this write into zero rows (sql.ErrNoRows here), mapped to
// db.ErrNotFound — the same refusal an action that never existed gets.
func (d *DB) InsertAppeal(ctx context.Context, publicID string, actionID, appellantID int64, body string) (int64, error) {
	id, err := d.q.InsertAppeal(ctx, dbgen.InsertAppealParams{
		PublicID: publicID, ActionID: actionID, AppellantID: appellantID, Body: body,
	})
	if err != nil {
		if IsUniqueConstraintError(err) {
			return 0, fmt.Errorf("InsertAppeal: %w", ErrConflict)
		}
		if errors.Is(err, sql.ErrNoRows) {
			return 0, fmt.Errorf("InsertAppeal: action no longer exists: %w", ErrNotFound)
		}
		return 0, fmt.Errorf("InsertAppeal: %w", err)
	}
	return id, nil
}

// GetAppeal returns one appeal by its internal id, or ErrNotFound.
func (d *DB) GetAppeal(ctx context.Context, id int64) (*Appeal, error) {
	r, err := d.q.GetAppealByID(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("GetAppeal: %w", err)
	}
	a := appealFromRow(r)
	return &a, nil
}

// GetAppealByPublicID resolves the opaque public id every route parameter
// and API response carries to the appeal row, or ErrNotFound.
func (d *DB) GetAppealByPublicID(ctx context.Context, publicID string) (*Appeal, error) {
	r, err := d.q.GetAppealByPublicID(ctx, publicID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("GetAppealByPublicID: %w", err)
	}
	a := appealFromRow(r)
	return &a, nil
}

// ListAppealsMine is the appellant's own view.
func (d *DB) ListAppealsMine(ctx context.Context, appellantID int64) ([]AppealSummary, error) {
	rows, err := d.q.ListAppealsMine(ctx, appellantID)
	if err != nil {
		return nil, fmt.Errorf("ListAppealsMine: %w", err)
	}
	out := make([]AppealSummary, 0, len(rows))
	for _, r := range rows {
		out = append(out, AppealSummary{
			ID: r.ID, PublicID: r.PublicID, ActionID: r.ActionID, Body: r.Body,
			State: r.State, DecisionNote: r.DecisionNote, CreatedAt: r.CreatedAt, DecidedAt: r.DecidedAt,
		})
	}
	return out, nil
}

// ListAppealsQueue returns the moderation queue view for one state filter:
// "open", "assigned", "decided" (both terminal decision states together,
// mirroring reports' "closed" grouping of resolved/dismissed), or "" for
// the default open+assigned view.
func (d *DB) ListAppealsQueue(ctx context.Context, state string) ([]AppealQueueRow, error) {
	build := func(rows []AppealQueueRow, err error) ([]AppealQueueRow, error) {
		if err != nil {
			return nil, fmt.Errorf("ListAppealsQueue: %w", err)
		}
		return rows, nil
	}
	switch state {
	case "decided":
		rows, err := d.q.ListAppealsDecided(ctx)
		out := make([]AppealQueueRow, 0, len(rows))
		for i := range rows {
			r := &rows[i]
			out = append(out, AppealQueueRow{
				ID: r.ID, PublicID: r.PublicID, ActionID: r.ActionID, AppellantID: r.AppellantID,
				Body: r.Body, State: r.State, AssigneeID: r.AssigneeID, DecidedBy: r.DecidedBy,
				DecisionNote: r.DecisionNote, CreatedAt: r.CreatedAt, DecidedAt: r.DecidedAt,
			})
		}
		return build(out, err)
	case "open", "assigned":
		rows, err := d.q.ListAppealsByState(ctx, state)
		out := make([]AppealQueueRow, 0, len(rows))
		for i := range rows {
			r := &rows[i]
			out = append(out, AppealQueueRow{
				ID: r.ID, PublicID: r.PublicID, ActionID: r.ActionID, AppellantID: r.AppellantID,
				Body: r.Body, State: r.State, AssigneeID: r.AssigneeID, DecidedBy: r.DecidedBy,
				DecisionNote: r.DecisionNote, CreatedAt: r.CreatedAt, DecidedAt: r.DecidedAt,
			})
		}
		return build(out, err)
	default:
		rows, err := d.q.ListAppealsOpenOrAssigned(ctx)
		out := make([]AppealQueueRow, 0, len(rows))
		for i := range rows {
			r := &rows[i]
			out = append(out, AppealQueueRow{
				ID: r.ID, PublicID: r.PublicID, ActionID: r.ActionID, AppellantID: r.AppellantID,
				Body: r.Body, State: r.State, AssigneeID: r.AssigneeID, DecidedBy: r.DecidedBy,
				DecisionNote: r.DecisionNote, CreatedAt: r.CreatedAt, DecidedAt: r.DecidedAt,
			})
		}
		return build(out, err)
	}
}

// AssignAppeal assigns assigneeID to appeal id, guarded on state,
// observedAssigneeID (optimistic concurrency, mirrors AssignReport) and
// EXISTS(users). Returns whether a row was affected; zero means CONFLICT.
func (d *DB) AssignAppeal(ctx context.Context, id, assigneeID, observedAssigneeID int64) (bool, error) {
	n, err := d.q.AssignAppeal(ctx, dbgen.AssignAppealParams{AssigneeID: assigneeID, ID: id, ObservedAssigneeID: observedAssigneeID})
	if err != nil {
		return false, fmt.Errorf("AssignAppeal: %w", err)
	}
	return n == 1, nil
}

// AssignAppealForced is the appeal queue's force-reassign path. See
// forceReassignGuarded (report_queries.go) for the shared mechanics.
func (d *DB) AssignAppealForced(ctx context.Context, id, assigneeID, observedAssigneeID, actorID int64) (bool, error) {
	return forceReassignGuarded(ctx, d.writer, actorID, observedAssigneeID, func(q *dbgen.Queries) (int64, error) {
		return q.AssignAppeal(ctx, dbgen.AssignAppealParams{AssigneeID: assigneeID, ID: id, ObservedAssigneeID: observedAssigneeID})
	})
}

// WithdrawAppeal withdraws appeal id — the appellant only, guarded to
// open/assigned states. Returns whether a row was affected; zero means
// CONFLICT.
func (d *DB) WithdrawAppeal(ctx context.Context, id, appellantID int64) (bool, error) {
	n, err := d.q.WithdrawAppeal(ctx, dbgen.WithdrawAppealParams{ID: id, AppellantID: appellantID})
	if err != nil {
		return false, fmt.Errorf("WithdrawAppeal: %w", err)
	}
	return n == 1, nil
}

// CountEligibleModerators counts every OTHER user (excluding excludeActorID,
// excludeAppellantID, id 0, and anyone effectively banned) whose role holds
// MODERATE_MEMBERS or Administrator — decision 8's self-review escape: the
// acting moderator may decide (or assign to themselves) their own appeal
// only when this count is zero. permBit/adminBit are passed in from the
// permissions package (not imported here, to keep db free of a permissions
// dependency).
func (d *DB) CountEligibleModerators(ctx context.Context, excludeActorID, excludeAppellantID, permBit, adminBit int64) (int64, error) {
	n, err := d.q.CountUsersWithPermission(ctx, dbgen.CountUsersWithPermissionParams{
		ExcludeActorID: excludeActorID, ExcludeAppellantID: excludeAppellantID, PermBit: permBit, AdminBit: adminBit,
	})
	if err != nil {
		return 0, fmt.Errorf("CountEligibleModerators: %w", err)
	}
	return n, nil
}

// AppealWriteOutcome is the guarded-write result DecideAppealTx reports, so
// the service layer maps each reason to its own HTTP status without
// re-deriving it from a generic bool (F1/F2/F3/Claim 5 review).
type AppealWriteOutcome int

const (
	// AppealWriteOK: the write (and, for an overturn, its reversal) landed.
	AppealWriteOK AppealWriteOutcome = iota
	// AppealWriteConflict: the observed state/assignee was stale, or the
	// deciding/assigning moderator no longer resolves to a user at all.
	AppealWriteConflict
	// AppealWriteSelfReview: another eligible reviewer exists.
	AppealWriteSelfReview
	// AppealWriteReversalFailed: the decision's guarded UPDATE would have
	// succeeded, but overturning it hit a real reversal error (not "nothing
	// was active to reverse", which is not an error) — the whole
	// transaction rolled back, so the decision itself did not commit either
	// (F1: the appellant must never be told "overturned" while the
	// sanction it named is still, mechanically, in effect).
	AppealWriteReversalFailed
)

// appealReversalHookForTest, when non-nil, forces applyAppealReversalTx to
// fail regardless of kind — the revert-proof seam for F1's own test ("a
// forced failure inside the reversal → nothing committed"). Test-only (nil
// in production); set via SetAppealReversalHookForTest (export_test.go).
var appealReversalHookForTest func() error

// applyAppealReversalTx runs overturn's kind-specific reversal on the SAME
// transaction as the decision's own guarded UPDATE (F1 review: this used to
// run AFTER the decision committed, through outrank-gated service methods,
// so a decider lacking THOSE gates — or a crash between the two writes —
// could leave the appellant told "overturned" while still sanctioned; it is
// now a store-level consequence of the decision, not a second moderation
// action, so it never calls ModerationService and never re-checks outrank).
// Zero rows affected is NOT an error (N1: the appealed timeout may already
// be superseded/lifted, or the appealed ban may already be superseded by a
// later ban action — "nothing to reverse" is a valid outcome and the
// decision still commits); only a genuine execution error aborts.
func applyAppealReversalTx(ctx context.Context, tx *sql.Tx, q *dbgen.Queries, kind string, actionID, targetID int64) error {
	if appealReversalHookForTest != nil {
		if err := appealReversalHookForTest(); err != nil {
			return err
		}
	}
	switch kind {
	case "timeout":
		if _, err := q.LiftTimeoutByActionID(ctx, actionID); err != nil {
			return fmt.Errorf("lift timeout: %w", err)
		}
	case "ban":
		// Hand-rolled: sqlc's SQLite analyzer does not correctly bind a
		// second distinct parameter reused inside a NOT EXISTS subquery
		// here (confirmed against v1.30 — the generated Go function silently
		// dropped the second bind), so this one statement runs directly
		// rather than through dbgen. See LiftBanIfCurrent's history for
		// the shape decision 8/F1/N1 need: unban only when no STRICTLY
		// NEWER 'ban' action exists for the same target — ban, unban,
		// re-ban, overturn the first ban must leave the user banned. The
		// tie-break is the row's id, not created_at: created_at is
		// datetime('now')'s second resolution, and a ban/unban/re-ban
		// sequence in one test (or one busy moderator) can land two ban
		// rows in the same wall-clock second, making a created_at ">"
		// comparison silently always-false and wrongly unbanning (caught by
		// TestAppeal_OverturnFirstBanDoesNotUnbanAfterReban). moderation_actions.id
		// is an autoincrement primary key, so a strictly higher id always
		// means a strictly later insert, with no resolution floor.
		if _, err := tx.ExecContext(ctx, `
			UPDATE users
			   SET banned = 0, ban_reason = NULL, ban_expires = NULL
			 WHERE id = ?
			   AND banned = 1
			   AND NOT EXISTS (
			       SELECT 1 FROM moderation_actions
			        WHERE target_id = ? AND kind = 'ban' AND id > ?
			   )`, targetID, targetID, actionID); err != nil {
			return fmt.Errorf("lift ban: %w", err)
		}
	case "warning":
		if _, err := q.AcknowledgeWarning(ctx, dbgen.AcknowledgeWarningParams{ID: actionID, TargetID: targetID}); err != nil {
			return fmt.Errorf("acknowledge warning: %w", err)
		}
	case "removal":
		// Nothing to restore — the content is gone.
	}
	return nil
}

// AppealedAction is the sliver of the appealed moderation_actions row
// DecideAppealTx's reversal needs, resolved once by the caller (which
// already loaded the full row for its own checks) rather than re-read here.
type AppealedAction struct {
	ID       int64
	Kind     string
	TargetID int64
}

// DecideAppealTx decides appealID in ONE transaction: the self-review
// eligibility count (when checkSelfReview), the guarded UPDATE (Claim 5: on
// the OBSERVED state/assignee, not a bare "open or assigned"), and (for an
// overturn) the reversal all run on the same connection — a moderator
// banned or erased between the count and the write, or a reversal that
// genuinely fails, cannot land a decision the data no longer supports
// (F1/F2/F3). checkSelfReview is true when decidedBy took the appealed
// action; soleModerator reports whether the escape actually applied, for
// the caller's audit detail.
func (d *DB) DecideAppealTx(
	ctx context.Context,
	appealID int64,
	observedState string,
	observedAssigneeID int64,
	outcome string,
	decidedBy int64,
	note string,
	checkSelfReview bool,
	appellantID, permBit, adminBit int64,
	action AppealedAction,
) (result AppealWriteOutcome, soleModeratorUsed bool, err error) {
	tx, err := d.writer.BeginTx(ctx, nil)
	if err != nil {
		return AppealWriteConflict, false, fmt.Errorf("DecideAppealTx begin tx: %w", err)
	}
	defer tx.Rollback() //nolint:errcheck
	q := dbgen.New(tx)

	if checkSelfReview {
		eligible, err := q.CountUsersWithPermission(ctx, dbgen.CountUsersWithPermissionParams{
			ExcludeActorID: decidedBy, ExcludeAppellantID: appellantID, PermBit: permBit, AdminBit: adminBit,
		})
		if err != nil {
			return AppealWriteConflict, false, fmt.Errorf("DecideAppealTx eligibility: %w", err)
		}
		if eligible > 0 {
			return AppealWriteSelfReview, false, nil
		}
		soleModeratorUsed = true
	}

	n, err := q.DecideAppeal(ctx, dbgen.DecideAppealParams{
		NewState: outcome, DecidedBy: decidedBy, DecisionNote: note, ID: appealID,
		ObservedState: observedState, ObservedAssigneeID: observedAssigneeID,
	})
	if err != nil {
		return AppealWriteConflict, false, fmt.Errorf("DecideAppealTx: %w", err)
	}
	if n != 1 {
		return AppealWriteConflict, false, nil
	}

	// F1: the reversal runs and is checked INSIDE this transaction, before
	// the decision commits. A decider lacking the reversal's own gates (or a
	// crash between the two writes) must never leave the appellant told
	// "overturned" while still sanctioned — so if the reversal fails, the
	// decision UPDATE above is rolled back with it, not just left uncommitted
	// on its own.
	if outcome == "overturned" {
		if err := applyAppealReversalTx(ctx, tx, q, action.Kind, action.ID, action.TargetID); err != nil {
			return AppealWriteReversalFailed, false, fmt.Errorf("DecideAppealTx reversal: %w", err)
		}
	}

	if err := tx.Commit(); err != nil {
		return AppealWriteConflict, false, fmt.Errorf("DecideAppealTx commit: %w", err)
	}
	return AppealWriteOK, soleModeratorUsed, nil
}

// GetModerationAction returns one moderation_actions row by id, or
// ErrNotFound — B5-10's appeal submission and decision both need the
// appealed action's own kind, target and actor.
func (d *DB) GetModerationAction(ctx context.Context, id int64) (*ModerationAction, error) {
	r, err := d.q.GetModerationActionByID(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("GetModerationAction: %w", err)
	}
	a := moderationActionFromRow(moderationActionRow(r))
	return &a, nil
}
