package db

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/J3vb/OwnCord/Server/db/dbgen"
)

// Appeal is a row of the appeals table (migration 050, B5-10). DecidedByToken
// is filled by erasure (the bare-id-plus-token pattern, migrations 038/041/
// 048/049): a zero id plus a non-empty token means the deciding moderator
// erased their account. PublicID is the only identifier ever exposed outside
// the server, the same shape reports.PublicID uses (Codex review deviation
// from the HP-5 draft) — appeals are filed in sequence server-side, so a
// moderator who can see appeals 1 and 3 but never 2 could otherwise infer
// appeal 2 concerns someone specific.
type Appeal struct {
	ID             int64
	PublicID       string
	ActionID       int64
	AppellantID    int64
	Body           string
	State          string
	AssigneeID     int64
	DecidedBy      int64
	DecidedByToken string
	DecisionNote   string
	CreatedAt      string
	DecidedAt      *string
}

// AppealSummary is one row of the appellant's own view (GET
// /api/v1/appeals/mine): id, action id, body, state, decision_note,
// created_at, decided_at — never the assignee, never who decided it.
type AppealSummary struct {
	ID           int64
	PublicID     string
	ActionID     int64
	Body         string
	State        string
	DecisionNote string
	CreatedAt    string
	DecidedAt    *string
}

// AppealQueueRow is one row of the moderation appeal queue.
type AppealQueueRow struct {
	ID           int64
	PublicID     string
	ActionID     int64
	AppellantID  int64
	Body         string
	State        string
	AssigneeID   int64
	DecidedBy    int64
	DecisionNote string
	CreatedAt    string
	DecidedAt    *string
}

func appealFromRow(r dbgen.Appeal) Appeal {
	return Appeal{
		ID: r.ID, PublicID: r.PublicID, ActionID: r.ActionID, AppellantID: r.AppellantID,
		Body: r.Body, State: r.State, AssigneeID: r.AssigneeID, DecidedBy: r.DecidedBy,
		DecidedByToken: strOrEmpty(r.DecidedByToken), DecisionNote: r.DecisionNote,
		CreatedAt: r.CreatedAt, DecidedAt: r.DecidedAt,
	}
}

// FindAppealForAction is the dedupe FAST-PATH check for decision 8's "one
// appeal per action, ever": returns 0, nil when no appeal exists yet. This
// alone is not race-proof — see the UNIQUE(action_id) constraint, which
// InsertAppeal's error mapping actually enforces.
func (d *DB) FindAppealForAction(ctx context.Context, actionID int64) (int64, error) {
	id, err := d.q.FindAppealForAction(ctx, actionID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return 0, nil
		}
		return 0, fmt.Errorf("FindAppealForAction: %w", err)
	}
	return id, nil
}

// appealInsertPreHookForTest, when non-nil, runs immediately before
// InsertAppeal's own INSERT statement — the barrier a db-package test uses
// to force two goroutines to genuinely both be in flight at this exact
// point (mirroring moderationActionPreInsertHook's contention-test shape),
// rather than merely hoping the scheduler interleaves them. Test-only (nil
// in production).
var appealInsertPreHookForTest func()

// InsertAppeal files a new appeal. publicID is generated by the caller
// (crypto/rand) before this runs. A violation of UNIQUE(action_id) surfaces
// as db.ErrConflict — the race-proof half of decision 8's "one appeal per
// action, ever". N4 review: the INSERT's own WHERE EXISTS guard (the action
// still exists) turns an action erased between the caller's ownership
// lookup and this write into zero rows (sql.ErrNoRows here), mapped to
// db.ErrNotFound — the same refusal an action that never existed gets.
func (d *DB) InsertAppeal(ctx context.Context, publicID string, actionID, appellantID int64, body string) (int64, error) {
	if appealInsertPreHookForTest != nil {
		appealInsertPreHookForTest()
	}
	id, err := d.q.InsertAppeal(ctx, dbgen.InsertAppealParams{
		PublicID: publicID, ActionID: actionID, AppellantID: appellantID, Body: body,
	})
	if err != nil {
		if IsUniqueConstraintError(err) {
			return 0, fmt.Errorf("InsertAppeal: %w", ErrConflict)
		}
		if errors.Is(err, sql.ErrNoRows) {
			return 0, fmt.Errorf("InsertAppeal: action no longer exists: %w", ErrNotFound)
		}
		return 0, fmt.Errorf("InsertAppeal: %w", err)
	}
	return id, nil
}

// GetAppeal returns one appeal by its internal id, or ErrNotFound.
func (d *DB) GetAppeal(ctx context.Context, id int64) (*Appeal, error) {
	r, err := d.q.GetAppealByID(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("GetAppeal: %w", err)
	}
	a := appealFromRow(r)
	return &a, nil
}

// GetAppealByPublicID resolves the opaque public id every route parameter
// and API response carries to the appeal row, or ErrNotFound.
func (d *DB) GetAppealByPublicID(ctx context.Context, publicID string) (*Appeal, error) {
	r, err := d.q.GetAppealByPublicID(ctx, publicID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("GetAppealByPublicID: %w", err)
	}
	a := appealFromRow(r)
	return &a, nil
}

// ListAppealsMine is the appellant's own view.
func (d *DB) ListAppealsMine(ctx context.Context, appellantID int64) ([]AppealSummary, error) {
	rows, err := d.q.ListAppealsMine(ctx, appellantID)
	if err != nil {
		return nil, fmt.Errorf("ListAppealsMine: %w", err)
	}
	out := make([]AppealSummary, 0, len(rows))
	for _, r := range rows {
		out = append(out, AppealSummary{
			ID: r.ID, PublicID: r.PublicID, ActionID: r.ActionID, Body: r.Body,
			State: r.State, DecisionNote: r.DecisionNote, CreatedAt: r.CreatedAt, DecidedAt: r.DecidedAt,
		})
	}
	return out, nil
}

// ListAppealsQueue returns the moderation queue view for one state filter:
// "open", "assigned", "decided" (both terminal decision states together,
// mirroring reports' "closed" grouping of resolved/dismissed), or "" for
// the default open+assigned view.
func (d *DB) ListAppealsQueue(ctx context.Context, state string) ([]AppealQueueRow, error) {
	build := func(rows []AppealQueueRow, err error) ([]AppealQueueRow, error) {
		if err != nil {
			return nil, fmt.Errorf("ListAppealsQueue: %w", err)
		}
		return rows, nil
	}
	switch state {
	case "decided":
		rows, err := d.q.ListAppealsDecided(ctx)
		out := make([]AppealQueueRow, 0, len(rows))
		for i := range rows {
			r := &rows[i]
			out = append(out, AppealQueueRow{
				ID: r.ID, PublicID: r.PublicID, ActionID: r.ActionID, AppellantID: r.AppellantID,
				Body: r.Body, State: r.State, AssigneeID: r.AssigneeID, DecidedBy: r.DecidedBy,
				DecisionNote: r.DecisionNote, CreatedAt: r.CreatedAt, DecidedAt: r.DecidedAt,
			})
		}
		return build(out, err)
	case "open", "assigned":
		rows, err := d.q.ListAppealsByState(ctx, state)
		out := make([]AppealQueueRow, 0, len(rows))
		for i := range rows {
			r := &rows[i]
			out = append(out, AppealQueueRow{
				ID: r.ID, PublicID: r.PublicID, ActionID: r.ActionID, AppellantID: r.AppellantID,
				Body: r.Body, State: r.State, AssigneeID: r.AssigneeID, DecidedBy: r.DecidedBy,
				DecisionNote: r.DecisionNote, CreatedAt: r.CreatedAt, DecidedAt: r.DecidedAt,
			})
		}
		return build(out, err)
	default:
		rows, err := d.q.ListAppealsOpenOrAssigned(ctx)
		out := make([]AppealQueueRow, 0, len(rows))
		for i := range rows {
			r := &rows[i]
			out = append(out, AppealQueueRow{
				ID: r.ID, PublicID: r.PublicID, ActionID: r.ActionID, AppellantID: r.AppellantID,
				Body: r.Body, State: r.State, AssigneeID: r.AssigneeID, DecidedBy: r.DecidedBy,
				DecisionNote: r.DecisionNote, CreatedAt: r.CreatedAt, DecidedAt: r.DecidedAt,
			})
		}
		return build(out, err)
	}
}

// AssignAppeal assigns assigneeID to appeal id, guarded on state,
// observedAssigneeID (optimistic concurrency, mirrors AssignReport) and
// EXISTS(users). Returns whether a row was affected; zero means CONFLICT.
// No authority re-check of its own — the low-level primitive, used by
// AssignAppealTx (the service's actual entry point) and directly by tests
// that only want to manipulate the row's state.
func (d *DB) AssignAppeal(ctx context.Context, id, assigneeID, observedAssigneeID int64) (bool, error) {
	n, err := d.q.AssignAppeal(ctx, dbgen.AssignAppealParams{AssigneeID: assigneeID, ID: id, ObservedAssigneeID: observedAssigneeID})
	if err != nil {
		return false, fmt.Errorf("AssignAppeal: %w", err)
	}
	return n == 1, nil
}

// appealAssignPreBeginTxHook, when non-nil, runs immediately before
// AssignAppealTx's BeginTx — the same test barrier shape as
// forceReassignPreBeginTxHook, for the plain (non-forced) assign path.
// Test-only (nil in production).
var appealAssignPreBeginTxHook func()

// AssignAppealTx is Assign's plain (non-forced) path, wrapped in its own
// transaction (P2 review, mirrors DecideAppealTx): the acting moderator's
// own authority (CanModerate bit, effective ban) is re-read fresh here,
// inside the SAME transaction as the guarded write, never trusted from the
// service's earlier (now possibly stale) requireModerate check. A revoked
// bit or a ban that landed before this transaction began refuses with
// ErrForbidden, before the write ever runs.
func (d *DB) AssignAppealTx(ctx context.Context, id, assigneeID, observedAssigneeID, actorID int64,
	checkAuthority func(rolePerms int64, banned bool, banExpires *string) error) (bool, error) {
	if appealAssignPreBeginTxHook != nil {
		appealAssignPreBeginTxHook()
	}
	tx, err := d.writer.BeginTx(ctx, nil)
	if err != nil {
		return false, fmt.Errorf("AssignAppealTx begin tx: %w", err)
	}
	defer tx.Rollback() //nolint:errcheck
	q := dbgen.New(tx)

	if checkAuthority != nil {
		rolePerms, banned, banExpires, ok := deciderAuthority(ctx, tx, actorID)
		if !ok || checkAuthority(rolePerms, banned, banExpires) != nil {
			return false, fmt.Errorf("AssignAppealTx: %w", ErrForbidden)
		}
	}

	n, err := q.AssignAppeal(ctx, dbgen.AssignAppealParams{AssigneeID: assigneeID, ID: id, ObservedAssigneeID: observedAssigneeID})
	if err != nil {
		return false, fmt.Errorf("AssignAppealTx: %w", err)
	}
	if n != 1 {
		return false, nil
	}
	if err := tx.Commit(); err != nil {
		return false, fmt.Errorf("AssignAppealTx commit: %w", err)
	}
	return true, nil
}

// AssignAppealForced is the appeal queue's force-reassign path. See
// forceReassignGuarded (report_queries.go) for the shared mechanics.
// checkAuthority is P2's fresh actor-authority re-check, run inside the
// same transaction as the target's fresh rank read.
func (d *DB) AssignAppealForced(ctx context.Context, id, assigneeID, observedAssigneeID, actorID int64,
	checkAuthority func(rolePerms int64, banned bool, banExpires *string) error) (bool, error) {
	return forceReassignGuarded(ctx, d.writer, actorID, observedAssigneeID, checkAuthority, func(q *dbgen.Queries) (int64, error) {
		return q.AssignAppeal(ctx, dbgen.AssignAppealParams{AssigneeID: assigneeID, ID: id, ObservedAssigneeID: observedAssigneeID})
	})
}

// deciderAuthority reads userID's role permissions and ban state fresh,
// inside tx (P2 review): the shared re-read DecideAppealTx, AssignAppealTx
// and forceReassignGuarded's checkAuthority all use, so a bit revoked or a
// ban landed between a caller's earlier authorization and this write is
// caught here rather than trusted stale. ok=false means the user no longer
// resolves to a role at all (erased, or a dangling role_id).
func deciderAuthority(ctx context.Context, tx *sql.Tx, userID int64) (rolePerms int64, banned bool, banExpires *string, ok bool) {
	err := tx.QueryRowContext(ctx,
		`SELECT r.permissions, u.banned, u.ban_expires FROM users u JOIN roles r ON r.id = u.role_id WHERE u.id = ?`, userID,
	).Scan(&rolePerms, &banned, &banExpires)
	if err != nil {
		return 0, false, nil, false
	}
	return rolePerms, banned, banExpires, true
}

// WithdrawAppeal withdraws appeal id — the appellant only, guarded to
// open/assigned states. Returns whether a row was affected; zero means
// CONFLICT.
func (d *DB) WithdrawAppeal(ctx context.Context, id, appellantID int64) (bool, error) {
	n, err := d.q.WithdrawAppeal(ctx, dbgen.WithdrawAppealParams{ID: id, AppellantID: appellantID})
	if err != nil {
		return false, fmt.Errorf("WithdrawAppeal: %w", err)
	}
	return n == 1, nil
}

// CountEligibleModerators counts every OTHER user (excluding excludeActorID,
// excludeAppellantID, id 0, and anyone effectively banned) whose role holds
// MODERATE_MEMBERS or Administrator — decision 8's self-review escape: the
// acting moderator may decide (or assign to themselves) their own appeal
// only when this count is zero. permBit/adminBit are passed in from the
// permissions package (not imported here, to keep db free of a permissions
// dependency).
func (d *DB) CountEligibleModerators(ctx context.Context, excludeActorID, excludeAppellantID, permBit, adminBit int64) (int64, error) {
	n, err := d.q.CountUsersWithPermission(ctx, dbgen.CountUsersWithPermissionParams{
		ExcludeActorID: excludeActorID, ExcludeAppellantID: excludeAppellantID, PermBit: permBit, AdminBit: adminBit,
	})
	if err != nil {
		return 0, fmt.Errorf("CountEligibleModerators: %w", err)
	}
	return n, nil
}

// AppealWriteOutcome is the guarded-write result DecideAppealTx reports, so
// the service layer maps each reason to its own HTTP status without
// re-deriving it from a generic bool (F1/F2/F3/Claim 5 review).
type AppealWriteOutcome int

const (
	// AppealWriteOK: the write (and, for an overturn, its reversal) landed.
	AppealWriteOK AppealWriteOutcome = iota
	// AppealWriteConflict: the observed state/assignee was stale, or the
	// deciding/assigning moderator no longer resolves to a user at all.
	AppealWriteConflict
	// AppealWriteSelfReview: another eligible reviewer exists.
	AppealWriteSelfReview
	// AppealWriteReversalFailed: the decision's guarded UPDATE would have
	// succeeded, but overturning it hit a real reversal error (not "nothing
	// was active to reverse", which is not an error) — the whole
	// transaction rolled back, so the decision itself did not commit either
	// (F1: the appellant must never be told "overturned" while the
	// sanction it named is still, mechanically, in effect).
	AppealWriteReversalFailed
	// AppealWriteForbidden: the deciding moderator's own authority (the
	// CanModerate bit, or an effective ban) did not hold when re-checked
	// fresh inside this transaction — revoked, or a ban landed, after the
	// caller's earlier requireModerate check (P2 review).
	AppealWriteForbidden
)

// appealReversalHookForTest, when non-nil, forces applyAppealReversalTx to
// fail regardless of kind — the revert-proof seam for F1's own test ("a
// forced failure inside the reversal → nothing committed"). Test-only (nil
// in production); set via SetAppealReversalHookForTest (export_test.go).
var appealReversalHookForTest func() error

// ReversalAuditActionFor names the audit action a kind's reversal writes
// (item 4 review): the same words B5-9 already uses for a human moderator
// taking the identical effect (service/moderation.go), so an operator
// reading the audit log sees one consistent vocabulary regardless of
// whether a human or an overturned appeal caused it. ok=false for
// "removal" (nothing happens -- the content is gone, so nothing to audit).
// Exported for the service layer, which writes this audit row itself
// AFTER DecideAppealTx commits (best-effort, like every other audit write
// in this codebase — see DecideAppealTx's own doc comment).
func ReversalAuditActionFor(kind string) (action string, ok bool) {
	switch kind {
	case "timeout":
		return "user_untimeout", true
	case "ban":
		return "user_unban", true
	case "warning":
		return "user_warning_acknowledged", true
	default: // "removal"
		return "", false
	}
}

// applyAppealReversalTx runs overturn's kind-specific reversal on the SAME
// transaction as the decision's own guarded UPDATE (F1 review: this used to
// run AFTER the decision committed, through outrank-gated service methods,
// so a decider lacking THOSE gates — or a crash between the two writes —
// could leave the appellant told "overturned" while still sanctioned; it is
// now a store-level consequence of the decision, not a second moderation
// action, so it never calls ModerationService and never re-checks outrank).
// Zero rows affected is NOT an error (N1: the appealed timeout may already
// be superseded/lifted, or the appealed ban may already be superseded by a
// later ban action — "nothing to reverse" is a valid outcome and the
// decision still commits); only a genuine execution error aborts. Returns
// whether the reversal actually changed anything, so the caller only
// writes a reversal audit row (item 4) when something real happened —
// claiming "user_untimeout" for a reversal that found nothing active would
// misdescribe the audit log.
func applyAppealReversalTx(ctx context.Context, tx *sql.Tx, q *dbgen.Queries, kind string, actionID, targetID int64) (affected bool, err error) {
	if appealReversalHookForTest != nil {
		if err := appealReversalHookForTest(); err != nil {
			return false, err
		}
	}
	switch kind {
	case "timeout":
		n, err := q.LiftTimeoutByActionID(ctx, actionID)
		if err != nil {
			return false, fmt.Errorf("lift timeout: %w", err)
		}
		return n > 0, nil
	case "ban":
		// Hand-rolled: sqlc's SQLite analyzer does not correctly bind a
		// second distinct parameter reused inside a NOT EXISTS subquery
		// here (confirmed against v1.30 — the generated Go function silently
		// dropped the second bind), so this one statement runs directly
		// rather than through dbgen. See LiftBanIfCurrent's history for
		// the shape decision 8/F1/N1 need: unban only when no STRICTLY
		// NEWER 'ban' action exists for the same target — ban, unban,
		// re-ban, overturn the first ban must leave the user banned. The
		// tie-break is the row's id, not created_at: created_at is
		// datetime('now')'s second resolution, and a ban/unban/re-ban
		// sequence in one test (or one busy moderator) can land two ban
		// rows in the same wall-clock second, making a created_at ">"
		// comparison silently always-false and wrongly unbanning (caught by
		// TestAppeal_OverturnFirstBanDoesNotUnbanAfterReban). moderation_actions.id
		// is an autoincrement primary key, so a strictly higher id always
		// means a strictly later insert, with no resolution floor.
		res, err := tx.ExecContext(ctx, `
			UPDATE users
			   SET banned = 0, ban_reason = NULL, ban_expires = NULL
			 WHERE id = ?
			   AND banned = 1
			   AND NOT EXISTS (
			       SELECT 1 FROM moderation_actions
			        WHERE target_id = ? AND kind = 'ban' AND id > ?
			   )`, targetID, targetID, actionID)
		if err != nil {
			return false, fmt.Errorf("lift ban: %w", err)
		}
		n, err := res.RowsAffected()
		return n > 0, err
	case "warning":
		n, err := q.AcknowledgeWarning(ctx, dbgen.AcknowledgeWarningParams{ID: actionID, TargetID: targetID})
		if err != nil {
			return false, fmt.Errorf("acknowledge warning: %w", err)
		}
		return n > 0, nil
	case "removal":
		// Nothing to restore — the content is gone.
		return false, nil
	}
	return false, nil
}

// AppealedAction is the sliver of the appealed moderation_actions row
// DecideAppealTx's reversal needs, resolved once by the caller (which
// already loaded the full row for its own checks) rather than re-read here.
type AppealedAction struct {
	ID       int64
	Kind     string
	TargetID int64
}

// appealDecidePreBeginTxHook, when non-nil, runs immediately before
// DecideAppealTx's BeginTx — the barrier a test uses to revoke the
// decider's bit or ban them in the exact gap between the service's earlier
// requireModerate check and this transaction's own fresh authority read
// (P2 review). Test-only (nil in production).
var appealDecidePreBeginTxHook func()

// DecideAppealTx decides appealID in ONE transaction: a fresh authority
// re-check (checkAuthority, P2), the self-review eligibility test (when
// checkSelfReview) run only after confirming the row is still the one the
// caller observed (P3: no point paying for the eligibility EXISTS on an
// appeal that is already stale), the guarded UPDATE (Claim 5: on the
// OBSERVED state/assignee, not a bare "open or assigned"), and — for an
// overturn — the reversal, all run on the same connection. checkSelfReview
// is true when decidedBy took the appealed action; soleModerator reports
// whether the escape actually applied, for the caller's audit detail;
// reversalApplied reports whether the overturn's reversal actually changed
// anything (N1: a superseded/already-lifted action reverses to a no-op),
// so the caller (item 4: the reversal's own audit row is best-effort, like
// every other audit write in this codebase — D8 policy — so it is written
// AFTER this commits, not inside it, or a rolled-back transaction could
// still leave an audit row claiming an effect that never landed) knows
// whether to write one.
func (d *DB) DecideAppealTx(
	ctx context.Context,
	appealID int64,
	observedState string,
	observedAssigneeID int64,
	outcome string,
	decidedBy int64,
	note string,
	checkSelfReview bool,
	appellantID, permBit, adminBit int64,
	action AppealedAction,
	checkAuthority func(rolePerms int64, banned bool, banExpires *string) error,
) (result AppealWriteOutcome, soleModeratorUsed, reversalApplied bool, err error) {
	if appealDecidePreBeginTxHook != nil {
		appealDecidePreBeginTxHook()
	}
	tx, err := d.writer.BeginTx(ctx, nil)
	if err != nil {
		return AppealWriteConflict, false, false, fmt.Errorf("DecideAppealTx begin tx: %w", err)
	}
	defer tx.Rollback() //nolint:errcheck
	q := dbgen.New(tx)

	// P2: the decider's own authority, re-read fresh — never trusted from
	// before this transaction began.
	if checkAuthority != nil {
		rolePerms, banned, banExpires, ok := deciderAuthority(ctx, tx, decidedBy)
		if !ok {
			return AppealWriteConflict, false, false, nil
		}
		if checkAuthority(rolePerms, banned, banExpires) != nil {
			return AppealWriteForbidden, false, false, nil
		}
	}

	// P3: reject a stale/terminal appeal BEFORE the eligibility test below —
	// the exact row+state+assignee the caller observed, the same guard the
	// UPDATE itself applies, run first so a decide that is going to fail its
	// guarded write anyway never pays for the eligibility EXISTS first.
	rowStillObserved, err := q.AppealObservedRowExists(ctx, dbgen.AppealObservedRowExistsParams{
		ID: appealID, ObservedState: observedState, ObservedAssigneeID: observedAssigneeID,
	})
	if err != nil {
		return AppealWriteConflict, false, false, fmt.Errorf("DecideAppealTx observed-row check: %w", err)
	}
	if rowStillObserved == 0 {
		return AppealWriteConflict, false, false, nil
	}

	if checkSelfReview {
		eligible, err := q.EligibleModeratorExists(ctx, dbgen.EligibleModeratorExistsParams{
			ExcludeActorID: decidedBy, ExcludeAppellantID: appellantID, PermBit: permBit, AdminBit: adminBit,
		})
		if err != nil {
			return AppealWriteConflict, false, false, fmt.Errorf("DecideAppealTx eligibility: %w", err)
		}
		if eligible > 0 {
			return AppealWriteSelfReview, false, false, nil
		}
		soleModeratorUsed = true
	}

	n, err := q.DecideAppeal(ctx, dbgen.DecideAppealParams{
		NewState: outcome, DecidedBy: decidedBy, DecisionNote: note, ID: appealID,
		ObservedState: observedState, ObservedAssigneeID: observedAssigneeID,
	})
	if err != nil {
		return AppealWriteConflict, false, false, fmt.Errorf("DecideAppealTx: %w", err)
	}
	if n != 1 {
		return AppealWriteConflict, false, false, nil
	}

	// F1: the reversal runs and is checked INSIDE this transaction, before
	// the decision commits. A decider lacking the reversal's own gates (or a
	// crash between the two writes) must never leave the appellant told
	// "overturned" while still sanctioned — so if the reversal fails, the
	// decision UPDATE above is rolled back with it, not just left uncommitted
	// on its own.
	if outcome == "overturned" {
		reversalApplied, err = applyAppealReversalTx(ctx, tx, q, action.Kind, action.ID, action.TargetID)
		if err != nil {
			return AppealWriteReversalFailed, false, false, fmt.Errorf("DecideAppealTx reversal: %w", err)
		}
	}

	if err := tx.Commit(); err != nil {
		return AppealWriteConflict, false, false, fmt.Errorf("DecideAppealTx commit: %w", err)
	}
	return AppealWriteOK, soleModeratorUsed, reversalApplied, nil
}

// GetModerationAction returns one moderation_actions row by id, or
// ErrNotFound — B5-10's appeal submission and decision both need the
// appealed action's own kind, target and actor.
func (d *DB) GetModerationAction(ctx context.Context, id int64) (*ModerationAction, error) {
	r, err := d.q.GetModerationActionByID(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("GetModerationAction: %w", err)
	}
	a := moderationActionFromRow(moderationActionRow(r))
	return &a, nil
}
