package db

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/J3vb/OwnCord/Server/db/dbgen"
)

// Report is a row of the reports table (migration 048, B5-8). ReporterToken
// and SubjectToken are filled by erasure (the audit_log two-token pattern,
// migrations 038/041): a zero id plus a non-empty token means that principal
// erased their account. PublicID is the only identifier ever exposed
// outside the server — the sequential ID is internal (foreign keys, audit
// target_id) and must never reach an API response, a route parameter or a
// mod_queue frame (Codex review: a bit holder who can see reports 1 and 3
// but never 2 in any queue view they can read infers report 2 is about
// them).
type Report struct {
	ID            int64
	PublicID      string
	ReporterID    int64
	ReporterToken string
	SubjectID     int64
	SubjectToken  string
	TargetType    string
	TargetRef     string
	ChannelID     *int64
	Reason        string
	Detail        string
	State         string
	AssigneeID    int64
	Outcome       string
	CreatedAt     string
	UpdatedAt     string
	ClosedAt      *string
}

// ReportQueueRow is one row of the moderation queue listing, with reporter
// and subject usernames resolved for display. Never carries the reason
// detail's free text or the evidence/notes.
type ReportQueueRow struct {
	ID           int64
	PublicID     string
	ReporterID   int64
	SubjectID    int64
	TargetType   string
	TargetRef    string
	ChannelID    *int64
	Reason       string
	State        string
	AssigneeID   int64
	Outcome      string
	CreatedAt    string
	UpdatedAt    string
	ClosedAt     *string
	ReporterName string
	SubjectName  string
}

// ReportSummary is one row of a reporter's own view (GET /api/v1/reports/mine):
// never the assignee, never the notes.
type ReportSummary struct {
	ID         int64
	PublicID   string
	TargetType string
	Reason     string
	State      string
	Outcome    string
	CreatedAt  string
	ClosedAt   *string
}

// ReportEvidenceRow is one row of a report's evidence snapshot.
type ReportEvidenceRow struct {
	ReportID    int64
	Seq         int64
	MessageID   *int64
	AuthorID    int64
	AuthorToken string
	Content     string
	Attachments string
	CapturedAt  string
}

// ReportNoteRow is one internal note on a report.
type ReportNoteRow struct {
	ID          int64
	ReportID    int64
	AuthorID    int64
	AuthorToken string
	Body        string
	CreatedAt   string
}

// ReportEvidenceInput is one evidence row queued for FileReport's
// transaction, seq relative to the reported item (0).
type ReportEvidenceInput struct {
	Seq             int64
	MessageID       *int64
	AuthorID        int64
	Content         string
	AttachmentsJSON string
}

// ReportEvent is one row of report_events, this feature's own immutable
// history (second Codex review): action is "created", "assigned", "noted"
// or "closed"; detail is the state or outcome word only, never free text.
// ActorToken is filled by erasure the same way AuditEntry's is (B4-10):
// actor_id goes to 0, the token records that the acting principal erased.
type ReportEvent struct {
	ID         int64
	ReportID   int64
	ActorID    int64
	ActorToken string
	Action     string
	Detail     string
	CreatedAt  string
}

func reportFromRow(r dbgen.Report) Report {
	return Report{
		ID: r.ID, PublicID: r.PublicID, ReporterID: r.ReporterID, ReporterToken: strOrEmpty(r.ReporterToken),
		SubjectID: r.SubjectID, SubjectToken: strOrEmpty(r.SubjectToken),
		TargetType: r.TargetType, TargetRef: r.TargetRef, ChannelID: r.ChannelID,
		Reason: r.Reason, Detail: r.Detail, State: r.State, AssigneeID: r.AssigneeID,
		Outcome: r.Outcome, CreatedAt: r.CreatedAt, UpdatedAt: r.UpdatedAt, ClosedAt: r.ClosedAt,
	}
}

func strOrEmpty(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

// FileReport inserts a report row, its evidence snapshot and its opening
// report_events row in ONE writer transaction (Codex review, P1-4, widened
// by a second review): several autocommits here would let an erasure that
// lands between the report insert and an evidence insert leave restored
// content or a since-erased author id in a row that EraseAccount already ran
// its unlink pass over. publicID is generated by the caller (crypto/rand,
// service layer) before this runs. A violation of idx_reports_active_unique
// (migration 048) — two simultaneous filings of the same reporter+target
// both reaching this INSERT — surfaces as db.ErrConflict. InsertReport's own
// EXISTS guards (a second review widening) turn a reporter or subject erased
// between the caller's resolution and this transaction into a zero-row
// RETURNING, surfaced here as db.ErrNotFound. An evidence row whose author
// was erased in that same window is silently dropped (its own guard), not
// an abort — the snapshot is simply short one context row, the same
// shape the retention sweep already leaves behind.
func (d *DB) FileReport(ctx context.Context, publicID string, reporterID, subjectID int64, targetType, targetRef string, channelID *int64, reason, detail string, evidence []ReportEvidenceInput) (int64, error) {
	tx, err := d.writer.BeginTx(ctx, nil)
	if err != nil {
		return 0, fmt.Errorf("FileReport begin tx: %w", err)
	}
	defer tx.Rollback() //nolint:errcheck
	q := dbgen.New(tx)

	id, err := q.InsertReport(ctx, dbgen.InsertReportParams{
		PublicID: publicID, ReporterID: reporterID, SubjectID: subjectID, TargetType: targetType,
		TargetRef: targetRef, ChannelID: channelID, Reason: reason, Detail: detail,
	})
	if err != nil {
		if IsUniqueConstraintError(err) {
			return 0, fmt.Errorf("FileReport: %w", ErrConflict)
		}
		if errors.Is(err, sql.ErrNoRows) {
			return 0, fmt.Errorf("FileReport: reporter or subject no longer exists: %w", ErrNotFound)
		}
		return 0, fmt.Errorf("FileReport insert report: %w", err)
	}
	for _, e := range evidence {
		if err := q.InsertReportEvidence(ctx, dbgen.InsertReportEvidenceParams{
			ReportID: id, Seq: e.Seq, MessageID: e.MessageID, AuthorID: e.AuthorID,
			Content: e.Content, Attachments: e.AttachmentsJSON,
		}); err != nil {
			return 0, fmt.Errorf("FileReport insert evidence: %w", err)
		}
	}
	// The opening report_events row, in the same transaction: never the
	// shared audit_log (second Codex review), actor 0 (the system actor,
	// same reasoning as the removed report_create audit row: the reporter's
	// identity is already on the reports row itself, for the same
	// bit-holding readers to see — this column need not repeat it).
	if err := q.InsertReportEvent(ctx, dbgen.InsertReportEventParams{ReportID: id, ActorID: 0, Action: "created", Detail: reason}); err != nil {
		return 0, fmt.Errorf("FileReport insert event: %w", err)
	}
	if err := tx.Commit(); err != nil {
		return 0, fmt.Errorf("FileReport commit: %w", err)
	}
	return id, nil
}

// GetReport returns one report by id, or ErrNotFound.
func (d *DB) GetReport(ctx context.Context, id int64) (*Report, error) {
	r, err := d.q.GetReportByID(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("GetReport: %w", err)
	}
	rep := reportFromRow(r)
	return &rep, nil
}

// GetReportByPublicID resolves the opaque public id every route parameter
// and API response carries to the report row, or ErrNotFound.
func (d *DB) GetReportByPublicID(ctx context.Context, publicID string) (*Report, error) {
	r, err := d.q.GetReportByPublicID(ctx, publicID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("GetReportByPublicID: %w", err)
	}
	rep := reportFromRow(r)
	return &rep, nil
}

// FindOpenOrAssignedReport is the duplicate-report FAST-PATH check: the same
// reporter, same target, an open or assigned report already exists.
// Returns 0, nil when none does. This alone is not race-proof — see
// idx_reports_active_unique, which FileReport's constraint-violation
// mapping actually enforces.
func (d *DB) FindOpenOrAssignedReport(ctx context.Context, reporterID int64, targetType, targetRef string) (int64, error) {
	id, err := d.q.FindOpenOrAssignedReport(ctx, dbgen.FindOpenOrAssignedReportParams{
		ReporterID: reporterID, TargetType: targetType, TargetRef: targetRef,
	})
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return 0, nil
		}
		return 0, fmt.Errorf("FindOpenOrAssignedReport: %w", err)
	}
	return id, nil
}

func queueRowFrom(id int64, publicID string, reporterID, subjectID int64, targetType, targetRef string, channelID *int64, reason, state string, assigneeID int64, outcome, createdAt, updatedAt string, closedAt *string, reporterName, subjectName string) ReportQueueRow {
	return ReportQueueRow{
		ID: id, PublicID: publicID, ReporterID: reporterID, SubjectID: subjectID, TargetType: targetType,
		TargetRef: targetRef, ChannelID: channelID, Reason: reason, State: state,
		AssigneeID: assigneeID, Outcome: outcome, CreatedAt: createdAt, UpdatedAt: updatedAt,
		ClosedAt: closedAt, ReporterName: reporterName, SubjectName: subjectName,
	}
}

// ListReportsQueue returns the queue view for one state filter: "open",
// "assigned", "closed" (every terminal state), or "" for the default
// open+assigned view.
func (d *DB) ListReportsQueue(ctx context.Context, state string) ([]ReportQueueRow, error) {
	switch state {
	case "open", "assigned":
		rows, err := d.q.ListReportsByState(ctx, state)
		if err != nil {
			return nil, fmt.Errorf("ListReportsQueue: %w", err)
		}
		out := make([]ReportQueueRow, 0, len(rows))
		for i := range rows {
			r := &rows[i]
			out = append(out, queueRowFrom(r.ID, r.PublicID, r.ReporterID, r.SubjectID, r.TargetType, r.TargetRef,
				r.ChannelID, r.Reason, r.State, r.AssigneeID, r.Outcome, r.CreatedAt, r.UpdatedAt,
				r.ClosedAt, r.ReporterName, r.SubjectName))
		}
		return out, nil
	case "closed":
		rows, err := d.q.ListReportsClosed(ctx)
		if err != nil {
			return nil, fmt.Errorf("ListReportsQueue: %w", err)
		}
		out := make([]ReportQueueRow, 0, len(rows))
		for i := range rows {
			r := &rows[i]
			out = append(out, queueRowFrom(r.ID, r.PublicID, r.ReporterID, r.SubjectID, r.TargetType, r.TargetRef,
				r.ChannelID, r.Reason, r.State, r.AssigneeID, r.Outcome, r.CreatedAt, r.UpdatedAt,
				r.ClosedAt, r.ReporterName, r.SubjectName))
		}
		return out, nil
	default:
		rows, err := d.q.ListReportsOpenOrAssigned(ctx)
		if err != nil {
			return nil, fmt.Errorf("ListReportsQueue: %w", err)
		}
		out := make([]ReportQueueRow, 0, len(rows))
		for i := range rows {
			r := &rows[i]
			out = append(out, queueRowFrom(r.ID, r.PublicID, r.ReporterID, r.SubjectID, r.TargetType, r.TargetRef,
				r.ChannelID, r.Reason, r.State, r.AssigneeID, r.Outcome, r.CreatedAt, r.UpdatedAt,
				r.ClosedAt, r.ReporterName, r.SubjectName))
		}
		return out, nil
	}
}

// ListReportsMine is the reporter's own view.
func (d *DB) ListReportsMine(ctx context.Context, reporterID int64) ([]ReportSummary, error) {
	rows, err := d.q.ListReportsMine(ctx, reporterID)
	if err != nil {
		return nil, fmt.Errorf("ListReportsMine: %w", err)
	}
	out := make([]ReportSummary, 0, len(rows))
	for _, r := range rows {
		out = append(out, ReportSummary{
			ID: r.ID, PublicID: r.PublicID, TargetType: r.TargetType, Reason: r.Reason, State: r.State,
			Outcome: r.Outcome, CreatedAt: r.CreatedAt, ClosedAt: r.ClosedAt,
		})
	}
	return out, nil
}

// AssignReport assigns assigneeID to report id, guarded on state,
// observedAssigneeID (optimistic concurrency: whoever the caller last read
// as the assignee — a concurrent reassignment moves this out from under a
// racing caller so its outrank verdict, computed against the stale value,
// can never be applied) and EXISTS(users) (a moderator erased between
// requirePerm and this write cannot land as the new assignee). Returns
// whether a row was affected; zero means CONFLICT for any of the three
// reasons.
func (d *DB) AssignReport(ctx context.Context, id, assigneeID, observedAssigneeID int64) (bool, error) {
	n, err := d.q.AssignReport(ctx, dbgen.AssignReportParams{AssigneeID: assigneeID, ID: id, ObservedAssigneeID: observedAssigneeID})
	if err != nil {
		return false, fmt.Errorf("AssignReport: %w", err)
	}
	return n == 1, nil
}

// forceReassignGuarded is the shared machinery behind AssignReportForced and
// AssignAppealForced (B5-10): the observed assignee's CURRENT role position
// is read through this same transaction's connection, and compared to
// actorRolePosition, immediately before doUpdate runs — closing the gap the
// plain outrank check leaves, where the read (of the target's role) and the
// write happen as two separate statements, one of which SQLite's
// single-writer serialization does not otherwise force together. Returns
// (true, nil) on success, (false, nil) for the ordinary state/observed/
// existence conflict doUpdate's own guard already covers (including the
// observed assignee no longer resolving to any role at all, erased
// mid-race — nothing to outrank, and doUpdate's own EXISTS(users) guard
// would refuse it too), and (false, ErrForbidden) when actorRolePosition
// does not outrank the assignee's fresh position — the caller maps that to
// a 403, distinctly from the 409 the plain conflict gets.
func forceReassignGuarded(ctx context.Context, writer *sql.DB, observedAssigneeID, actorRolePosition int64, doUpdate func(*dbgen.Queries) (int64, error)) (bool, error) {
	tx, err := writer.BeginTx(ctx, nil)
	if err != nil {
		return false, fmt.Errorf("forceReassignGuarded begin tx: %w", err)
	}
	defer tx.Rollback() //nolint:errcheck
	q := dbgen.New(tx)

	targetRole, err := q.GetRoleForUser(ctx, observedAssigneeID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return false, nil
		}
		return false, fmt.Errorf("forceReassignGuarded role lookup: %w", err)
	}
	if actorRolePosition <= targetRole.Position {
		return false, ErrForbidden
	}

	n, err := doUpdate(q)
	if err != nil {
		return false, fmt.Errorf("forceReassignGuarded: %w", err)
	}
	if n != 1 {
		return false, nil
	}
	if err := tx.Commit(); err != nil {
		return false, fmt.Errorf("forceReassignGuarded commit: %w", err)
	}
	return true, nil
}

// AssignReportForced is the report queue's force-reassign path. See
// forceReassignGuarded for the shared mechanics.
func (d *DB) AssignReportForced(ctx context.Context, id, assigneeID, observedAssigneeID, actorRolePosition int64) (bool, error) {
	return forceReassignGuarded(ctx, d.writer, observedAssigneeID, actorRolePosition, func(q *dbgen.Queries) (int64, error) {
		return q.AssignReport(ctx, dbgen.AssignReportParams{AssigneeID: assigneeID, ID: id, ObservedAssigneeID: observedAssigneeID})
	})
}

// CloseReport closes report id with outcome, guarded to open/assigned
// states. state must be "resolved" or "dismissed". Returns whether a row
// was affected; zero means CONFLICT.
func (d *DB) CloseReport(ctx context.Context, id int64, state, outcome string) (bool, error) {
	n, err := d.q.CloseReport(ctx, dbgen.CloseReportParams{State: state, Outcome: outcome, ID: id})
	if err != nil {
		return false, fmt.Errorf("CloseReport: %w", err)
	}
	return n == 1, nil
}

// InsertReportEvidence writes one snapshot row. attachmentsJSON is a JSON
// list of {id, filename, mime, size} references, never bytes and never
// stored_as (S5, decision 7).
func (d *DB) InsertReportEvidence(ctx context.Context, reportID, seq int64, messageID *int64, authorID int64, content, attachmentsJSON string) error {
	if err := d.q.InsertReportEvidence(ctx, dbgen.InsertReportEvidenceParams{
		ReportID: reportID, Seq: seq, MessageID: messageID, AuthorID: authorID,
		Content: content, Attachments: attachmentsJSON,
	}); err != nil {
		return fmt.Errorf("InsertReportEvidence: %w", err)
	}
	return nil
}

// ListReportEvidence returns a report's snapshot, ordered by seq.
func (d *DB) ListReportEvidence(ctx context.Context, reportID int64) ([]ReportEvidenceRow, error) {
	rows, err := d.q.ListReportEvidence(ctx, reportID)
	if err != nil {
		return nil, fmt.Errorf("ListReportEvidence: %w", err)
	}
	out := make([]ReportEvidenceRow, 0, len(rows))
	for _, r := range rows {
		out = append(out, ReportEvidenceRow{
			ReportID: r.ReportID, Seq: r.Seq, MessageID: r.MessageID, AuthorID: r.AuthorID,
			AuthorToken: strOrEmpty(r.AuthorToken), Content: r.Content, Attachments: r.Attachments,
			CapturedAt: r.CapturedAt,
		})
	}
	return out, nil
}

// InsertReportNote adds one internal note, guarded on EXISTS(users): a
// moderator erased between requirePerm and this write cannot land as the
// note's author. Returns whether the row was inserted; false means the
// caller answers 409.
func (d *DB) InsertReportNote(ctx context.Context, reportID, authorID int64, body string) (bool, error) {
	n, err := d.q.InsertReportNote(ctx, dbgen.InsertReportNoteParams{ReportID: reportID, AuthorID: authorID, Body: body})
	if err != nil {
		return false, fmt.Errorf("InsertReportNote: %w", err)
	}
	return n == 1, nil
}

// ListReportNotes returns a report's internal notes, oldest first.
func (d *DB) ListReportNotes(ctx context.Context, reportID int64) ([]ReportNoteRow, error) {
	rows, err := d.q.ListReportNotes(ctx, reportID)
	if err != nil {
		return nil, fmt.Errorf("ListReportNotes: %w", err)
	}
	out := make([]ReportNoteRow, 0, len(rows))
	for _, r := range rows {
		out = append(out, ReportNoteRow{
			ID: r.ID, ReportID: r.ReportID, AuthorID: r.AuthorID,
			AuthorToken: strOrEmpty(r.AuthorToken), Body: r.Body, CreatedAt: r.CreatedAt,
		})
	}
	return out, nil
}

// InsertReportEvent appends one row to report_events, this feature's own
// immutable history (second Codex review) — never the shared audit_log,
// which a VIEW_AUDIT_LOG holder could read regardless of whether they hold
// MODERATE_MEMBERS. detail is the state or outcome word only, never free
// text (AssertSafeDetails and TestReportEvents_EveryMutationWritesOne both
// hold this).
func (d *DB) InsertReportEvent(ctx context.Context, reportID, actorID int64, action, detail string) error {
	if err := d.q.InsertReportEvent(ctx, dbgen.InsertReportEventParams{
		ReportID: reportID, ActorID: actorID, Action: action, Detail: detail,
	}); err != nil {
		return fmt.Errorf("InsertReportEvent: %w", err)
	}
	return nil
}

func eventFromRow(r dbgen.ReportEvent) ReportEvent {
	return ReportEvent{
		ID: r.ID, ReportID: r.ReportID, ActorID: r.ActorID, ActorToken: strOrEmpty(r.ActorToken),
		Action: r.Action, Detail: r.Detail, CreatedAt: r.CreatedAt,
	}
}

// ListReportEvents returns a report's immutable history, oldest first —
// exposed only inside the queue detail (MODERATE_MEMBERS bit AND the
// confidentiality guard, ReportService.Get's existing gate).
func (d *DB) ListReportEvents(ctx context.Context, reportID int64) ([]ReportEvent, error) {
	rows, err := d.q.ListReportEvents(ctx, reportID)
	if err != nil {
		return nil, fmt.Errorf("ListReportEvents: %w", err)
	}
	out := make([]ReportEvent, 0, len(rows))
	for _, r := range rows {
		out = append(out, eventFromRow(r))
	}
	return out, nil
}

// PruneReportContentOlderThan deletes the evidence and notes, and clears the
// detail, of every report closed before cutoff (a "YYYY-MM-DD HH:MM:SS" UTC
// string comparable with SQLite's datetime('now')). The reports row itself
// is kept — content is bounded, the outcome is indefinite (S5-d). Returns
// the number of reports whose detail was cleared, which is 0 exactly when
// nothing in range had any content left to prune.
func (d *DB) PruneReportContentOlderThan(ctx context.Context, cutoff string) (int64, error) {
	if _, err := d.q.PruneReportEvidenceOlderThan(ctx, &cutoff); err != nil {
		return 0, fmt.Errorf("PruneReportContentOlderThan evidence: %w", err)
	}
	if _, err := d.q.PruneReportNotesOlderThan(ctx, &cutoff); err != nil {
		return 0, fmt.Errorf("PruneReportContentOlderThan notes: %w", err)
	}
	n, err := d.q.PruneReportDetailOlderThan(ctx, &cutoff)
	if err != nil {
		return 0, fmt.Errorf("PruneReportContentOlderThan detail: %w", err)
	}
	return n, nil
}
